- chroma-manager/tests/framework/integration/existing_filesystem_configuration/cluster_setup
- chroma-manager/tests/framework/integration/existing_filesystem_configuration/filesystem_setup
- chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main
- chroma-manager/tests/framework/integration/existing_filesystem_configuration/run_tests
- chroma-manager/tests/framework/integration/installation_and_upgrade/cluster_setup
- chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests
- chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup
- chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/jenkins_steps/main
- chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/run_tests
- chroma-manager/tests/framework/integration/shared_storage_configuration/simulator/cluster_setup
- chroma-manager/tests/framework/integration/shared_storage_configuration/simulator/run_tests
- chroma-manager/tests/framework/integration/upgrade_os/cluster_setup
- chroma-manager/tests/framework/integration/upgrade_os/run_tests
- chroma-manager/tests/framework/integration/utils/install_client.sh
- chroma-manager/tests/framework/services/cluster_setup
- chroma-manager/tests/framework/services/run_tests
- chroma-manager/tests/framework/utils/collect_reports.sh
- chroma-manager/tests/framework/utils/provisioner_interface/provision_cluster
This is the stack of changs I need to get SSI and EFS tests running
from our GitHub repo.
> Changes needed to run SSI and EFS tests from GitHub

- chroma-manager/tests/framework/integration/installation_and_upgrade/jenkins_steps/main
- chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests
- chroma-manager/tests/framework/integration/shared_storage_configuration/simulator/cluster_setup
- chroma-manager/tests/framework/integration/shared_storage_configuration/simulator/jenkins_steps/main
- chroma-manager/tests/framework/integration/shared_storage_configuration/simulator/run_tests
- chroma-manager/tests/framework/services/cluster_setup
- chroma-manager/tests/framework/services/jenkins_steps/main
- chroma-manager/tests/framework/services/run_tests
- chroma-manager/tests/framework/unit/jenkins_steps/main
- chroma-manager/tests/framework/utils/defaults.sh
- include/Makefile.version
Fixes #17
These patches are needed so that CI testing works on the new jenkins.
> Patches needed for the rest of tests

- chroma-manager/tests/integration/core/remote_operations.py
In this case we are trying to diagnose:
test: INFO: SSH address = lotus-56vm5.lotus.hpdd.lab.intel.com, args = {'username': 'root'}
paramiko.transport: ERROR: Socket exception: Connection reset by peer (104)
> Leverage the host test in #29 for more errors

- Makefile
- Vagrantfile
- chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup
- chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/jenkins_steps/main
- chroma-manager/tests/framework/integration/utils/install_client.sh
- chroma-manager/tests/framework/utils/cluster_setup.sh
- chroma-manager/tests/framework/utils/defaults.sh
- chroma-manager/tests/framework/utils/provisioner_interface/provision_cluster
- chroma-manager/tests/framework/utils/provisioner_interface/provisioner_json2test_json.py
- chroma-manager/tests/integration/core/clear_ha_el6.sh
- chroma-manager/tests/integration/core/clear_ha_el7.sh
- chroma-manager/tests/integration/core/remote_operations.py
- edit_network
- edit_scsi
- provisioner_output-vagrant.json
- vagrant-virsh
Changes needed so that one can run "make ssi_tests" locally using Vagrant
to build a cluster to run the tests.
Supports the SSI test initially.
> Locally run tests using Vagrant and libvirt/qemu/kvm

- chroma-manager/chroma_core/migrations/0034_remove_unused_tables.py
Historically we moved the old alert tables to 'unused_chroma_core_'[alert] so
we could undo them, we later changed to deleting them (changed in
0024_auto__del_event__add_commandalert__add_getlnetstatejob__del_field_aler.py)
However the rename threw a fatal error (which wasn't fatal) in the logs and
people got confused. Now we are confident of the original migration we can
change it to a delete and add a migration to clean up any undeleted tables
from previous migrations.
- Change rename to be delete in 0024_auto__del_event__add_commandale
- Clean up renamed tables in the new migration.
> SQL "Fatal Errors" in install.log

- chroma-manager/MANIFEST.in
- chroma-manager/chroma_core/management/commands/realtime.py
- chroma-manager/chroma_core/management/commands/view_server.py
- chroma-manager/ui-modules/package-lock.json
- chroma-manager/ui-modules/package.json
- Update view-server path.
- Bump deps.
> Push node deps to latest available.

- .gitignore
- chroma-manager/tests/integration/core/api_testcase_with_test_reset.py
- include/Makefile.version
Fixes #158.
Update the package naming from ee -> iml. In addition, bump the version to 4.0.0.
> Update package naming

- chroma-manager/ui-modules/package-lock.json
- chroma-manager/ui-modules/package.json
Bump the GUI version to v6.0.13.
> Update GUI to v6.0.13

- chroma-manager/tests/integration/core/remote_operations.py
> Add a wait to ensure service stops before proceeding.

- .gitignore
- chroma-bundles/Makefile
- chroma-manager/scripts/deploy_build
- chroma-manager/tests/utils/install.exp
- chroma-manager/tests/utils/upgrade.exp
It appears we didn't fully remove all EULA code.
Remove the rest of it.
> Remove EULA remnants

- chroma-manager/ui-modules/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/287)
> bump old-gui to 2.1.1

- chroma-manager/scripts/fake_ipmi_kvm.py
- Removed a line that contained the phrase: "DO NOT DISTRIBUTE"
Signed-off-by: Peter Robinson <peter.timothy.robinson@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/288)
> Fix due to IPDLT Scan

- chroma-manager/ui-modules/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/295)
> Bump old-gui to latest

- chroma-dependencies/Makefile
Fixes #36
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/302)
> Update coverage to not pull from dropbox

- chroma-manager/storage_server.repo
- chroma-manager/tests/framework/utils/defaults.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/308)
> Pin to Lustre Jenkins 2.10.1 GA

- chroma-manager/Makefile
- chroma-manager/chroma-manager.spec
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/344)
> Build fixes

- chroma-manager/tests/integration/core/remote_operations.py
- chroma-manager/tests/integration/existing_filesystem_configuration/utils/create_lustre_filesystem.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/357)
> Ensure we are stopping agent during EFS cleanup

- chroma-manager/chroma-manager.spec
- chroma-manager/chroma_core/migrations/0037_remove_rsyslog_types.py
- chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests
Fixes #359.
Signed-off-by: Will Johnson <william.c1.johnson@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/388)
> IML-359 Add rsyslog model back and create migration

- scripts/deploy_build
A script to make it easy to deploy a build to a cluster
including a dev cluster or a Vagrant cluster, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/428)
> Add a script to deploy to a cluster

- chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/jenkins_steps/main
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/431)
> Allow overriding the location of the $RELEASE_ARCHIVE

- chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup
- chroma-manager/tests/framework/utils/defaults.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/436)
> Set directories to FQPN in tests

- chroma-manager/tests/integration/utils/chroma_log_collector.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/437)
> Install iml-diagnostics for log collection

- chroma-manager/tests/framework/integration/existing_filesystem_configuration/cluster_setup
- chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests
- chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup
- chroma-manager/tests/framework/utils/defaults.sh
Make sure the URLs to the Lustre build are the same as what's
in set_defaults().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/463)
> Fix local storage_server.repo override

- chroma-manager/tests/framework/utils/provisioner_interface/provision_cluster
- chroma-manager/tests/framework/utils/provisioner_interface/release_cluster
Add some debug to see what might be going wrong during test
timeouts (and possibly aborts).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/461)
> Fully qualify provisioner semaphore

- chroma-manager/chroma-manager.conf.template
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/432)
> add iml-device-aggregator endpoint to nginx configuration

- .github/ISSUE_TEMPLATE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/502)
> prompt for iml-diagnostics

- chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice_lvm.py
So that tests don't halt waiting for an answer they will never get.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/486)
> Assume yes answer to {vg,lv}create

- chroma-manager/Makefile
- chroma-manager/tests/framework/test_reporting/jenkins_steps/main
- chroma-manager/tests/framework/utils/selective_auto_pass.sh
- chroma-manager/tests/integration/shared_storage_configuration/test_anonymous_access_control.py
Now that the simulator has been removed, there are still a few
areas we can cleanup.
Remove some more sim related code.
> Post sim cleanup

- chroma-manager/tests/framework/services/run_tests
Signed-off-by: Minh Diep <minh.diep@intel.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/525)
> Use ~/chromatest for report

- chroma-manager/tests/framework/integration/existing_filesystem_configuration/cluster_setup
- chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests
- chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/524)
> Add more testing directives environment vars

- chroma-agent/chroma-agent.spec
- chroma-agent/chroma_agent/lib/yum_utils.py
- chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests
- chroma-manager/tests/framework/integration/utils/upgrade_os.sh
- chroma-manager/tests/framework/utils/defaults.sh
- chroma-manager/tests/framework/utils/selective_auto_pass.sh
- chroma-manager/tests/integration/installation_and_upgrade/test_update_with_yum.py
- chroma-manager/tests/integration/shared_storage_configuration/test_updates.py
Fixes #512
Have our upgrade test work from the most recent 4.x release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/513)
> Remove agent stop/disable/enable/start from RPM + 4.x -> 4.x Upgrades

- chroma-agent/chroma-agent.spec
> Pin device-scanner <2

- chroma-agent/chroma-agent.spec
- chroma-bundles/chroma_support.repo
- chroma-bundles/include/find_deps.py
- chroma-manager/chroma-manager.spec
- chroma-manager/storage_server.repo
- chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup
- chroma-manager/tests/framework/utils/defaults.sh
- chroma-manager/tests/framework/utils/install_deps.sh
patch stack of reactive architecture for use in development and testing
previous in stack https://github.com/intel-hpdd/intel-manager-for-lustre/pull/561
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/467)
> Reactive stack

- chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main
exit test run on first failure
> Failfast efs

- chroma-agent/chroma_agent/device_plugins/block_devices.py
Because the agent pulls data from device-scanner,
it is very important that we wait for udev to settle
before pulling a new state so we don't pull
an intermediate state.
> Settle before reading from device-scanner

- chroma-agent/chroma_agent/device_plugins/audit/lustre/__init__.py
- chroma-agent/tests/actions_plugins/test_manage_target.py
- chroma-agent/tests/audit/test_client_audit.py
- chroma-agent/tests/device_plugins/test_block_devices.py
- chroma-agent/tests/metrics/test_lustre.py
- chroma-agent/tests/test_utils.py
- chroma-dependencies/Makefile
> Fix unit tests

- chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice_lvm.py
> fix efs lvm create

- Makefile
- chroma-agent/Makefile
- chroma-bundles/Makefile
- chroma-bundles/chroma-manager/Makefile
- chroma-bundles/chroma_support.repo.in
- chroma-bundles/include/Makefile.bundle
- chroma-bundles/include/find_deps.py
- chroma-dependencies/Makefile
- chroma-manager/Makefile
- chroma-manager/storage_server.repo.in
- chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main
- chroma-manager/tests/framework/integration/installation_and_upgrade/cluster_setup
- chroma-manager/tests/framework/integration/installation_and_upgrade/jenkins_steps/main
- chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/jenkins_steps/main
- chroma-manager/tests/framework/services/jenkins_steps/main
- chroma-manager/tests/framework/unit/jenkins_steps/main
- chroma-manager/tests/framework/utils/defaults.sh.in
Allow the MFL COPR repo to be definable per build as MFL_COPR_REPO
in Makefile
> Per build configurable MFL repo

- chroma-agent/tests/actions_plugins/test_manage_target.py
- chroma-agent/tests/actions_plugins/test_manage_targets.py
- chroma-agent/tests/device_plugins/test_corosync.py
- chroma-agent/tests/device_plugins/test_lustre.py
- chroma-agent/tests/test_corosync_config.py
- chroma-agent/tests/test_fencing.py
Relates to changes made in https://github.com/intel-hpdd/iml-common/pull/41
> Fixup tests to accommodate changes in iml-common#41

- chroma-bundles/install
- chroma-manager/storage_server.repo
- chroma-manager/tests/framework/utils/defaults.sh
> CentOS 7.5 and Lustre 2.10.4

- Makefile
- chroma-agent/Makefile
- chroma-bundles/Makefile
- chroma-dependencies/Makefile
- chroma-manager/Makefile
- scripts/jenkins_build
> Add clean_substs to be used between builds

- chroma-manager/chroma-manager.conf.template
> Update favicon location

- chroma-manager/chroma_core/migrations/0023_auto__add_unconfigurersyslogjob__add_getcorosyncstatejob__add_pacemake.py
- chroma-manager/chroma_core/migrations/0039_add_primary_umtm_stepresults.py
> Fix migration issue.

- MANIFEST.in
- Makefile
- python-iml-manager.spec.in
Fix rpm and make warnings during build
> Cleanup build warnings

- .travis.yml
Add continuous deployment to the manager.
> Add continuous deployment

- chroma-manager.conf.template
- iml-manager-redirect.conf
- python-iml-manager.spec.in
> Ensure redirect happens from port http to https

- scripts/fake_ipmi_vbox.py
Fix the vbox fencing script so it doesn't hang.
> Fix vbox fencing script

- chroma_core/services/plugin_runner/resource_manager.py
Fixes #677 
When creating a pool that both:
- Doesn't have a backing partition (mpath setup)
- Has one backing VDev
The resource_manager chooses the path of the ancestor. This happens here:
https://github.com/whamcloud/integrated-manager-for-lustre/blob/7ff102df7828f4798aa2bda530754960b020cb99/chroma_core/services/plugin_runner/resource_manager.py#L560-L563
This is masking that some devices are pools and presenting a disk id instead.
Check for a `device_type` callable returning `zfs` to indicate we are dealing with a pool.
> ZfsPools with a single ancestor choose ancestor path

- Makefile
- provisioner_output-vagrant-efs.json.in
- tests/framework/integration/existing_filesystem_configuration/cluster_setup
- tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main
- tests/framework/integration/existing_filesystem_configuration/run_tests
- tests/framework/integration/shared_storage_configuration/full_cluster/jenkins_steps/main
- tests/framework/utils/provisioner_interface/provision_cluster
- tests/framework/utils/provisioner_interface/provisioner_json2test_json.py
- tests/integration/existing_filesystem_configuration/utils/create_lustre_filesystem.py
- tests/integration/utils/test_blockdevices/test_blockdevice_zfs.py
- tests/integration/utils/test_filesystems/test_filesystem.py
Get EFS Testing working with Vagrant provisioning.  …
Now that we are running SSI testing with Vagrant,
see if we can do the same for EFS testing.
> Get EFS Testing working with Vagrant provisioning

- .dockerignore
- docker-compose.yml
Instead of hosting the docker-compose file in a separate repo,
move it in here so it's colocated with the dockerfiles.
> Add docker-compose.yml file

- base.dockerfile
> Add dep on git when building base dockerfile

- storage_server.repo.in
- tests/framework/utils/defaults.sh.in
> Add support for Lustre 2.10.5

- storage_server.repo.in
- tests/framework/integration/utils/install_client.sh
- tests/integration/core/chroma_integration_testcase.py
- tests/integration/core/remote_operations.py
The removed the tests requirement for DNF.
> Convert dnf to yum usage.

- tests/integration/shared_storage_configuration/test_corosync.py
> Wait for IML manager to say pacemaker is running

- chroma-manager/chroma_core/south_migrations/0040_table_update_notify.py
Add table_update_notify migration.
> Table Update Notify Migration

- tests/integration/shared_storage_configuration/test_power_control.py
> Wait for server boot after PDU restart

- chroma-bundles/install
> Fix detection of rhel7.6

- chroma-manager/chroma_core/lib/service_config.py
> Only clear sessions if db is populated

- chroma-manager/chroma_core/south_migrations/0039_add_primary_umtm_stepresults.py
* Fix migration issue.
* fix migration in 0039
* CR updates
> Fix migration issue. (#647)

- chroma_api/alert.py
> Set needs_update on hosts when updates are available

- .copr/Makefile
- README.md
- azure-pipelines.yml
- ci/azure-build-check.yml
- ci/azure-clippy.yml
- ci/azure-install-rust.yml
- ci/azure-release.yml
- ci/azure-rustfmt.yml
- ci/azure-test-stable.yml
This patch adds CI checks for rust components using Azure pipelines.
Signed-off-by: Joe Grund <jgrund@whamcloud.com>
> Add CI checks for Rust components

- tests/integration/shared_storage_configuration/test_filesystem_dne.py
- tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py
> Revert LU-9725 skip

- azure-pipelines.yml
- ci/azure-release.yml
> Fixup auth

- Cargo.lock
- iml-warp-drive/Cargo.toml
- iml-warp-drive/src/locks.rs
- iml-warp-drive/src/main.rs
- iml-warp-drive/src/users.rs
- iml-warp-drive/systemd-units/iml-warp-drive.service
- rust-iml.spec
Use the parking_lot mutex, and add some better logging.
> Use parking_lot mutex

- chroma_core/services/rpc.py
- python-iml-manager.spec.in
- requirements.txt
We are currently using a custom build of jsonschema == 0.8
The latest in EPEL is 2.5.
Unpin from our custom version and use the one in EPEL.
> Unpin jsonschema

- .travis.yml
- chroma-manager/chroma-manager.conf.template
- chroma-manager/chroma_api/action.py
- chroma-manager/chroma_api/system_status.py
- chroma-manager/chroma_api/urls.py
- chroma-manager/chroma_api/utils.py
- chroma-manager/chroma_cli/handlers.py
- chroma-manager/chroma_core/lib/service_config.py
- chroma-manager/chroma_core/management/commands/print-settings.py
- chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py
- chroma-manager/chroma_core/services/job_scheduler/job_scheduler_client.py
- chroma-manager/chroma_core/services/job_scheduler/lock_cache.py
- chroma-manager/settings.py
- chroma-manager/tests/integration/core/api_testcase_with_test_reset.py
- chroma-manager/tests/integration/shared_storage_configuration/test_shutdown_reboot.py
- chroma-manager/tests/unit/chroma_api/chroma_api_test_case.py
- chroma-manager/tests/unit/chroma_api/test_misc.py
- chroma-manager/tests/unit/chroma_api/test_sorting_actions.py
- chroma-manager/tests/unit/chroma_core/services/job_scheduler/test_available_jobs.py
- chroma-manager/tests/unit/chroma_core/services/job_scheduler/test_available_transitions.py
- chroma-manager/tests/unit/lib/iml_unit_test_case.py
- chroma-manager/tests/unit/services/job_scheduler/job_test_case.py
- chroma-manager/tests/utils/http_requests.py
- chroma-manager/wsgi.py
- chroma_api/action.py
- tests/integration/existing_filesystem_configuration/test_filesystem_detection.py
- tests/integration/shared_storage_configuration/test_anonymous_access_control.py
- tests/integration/shared_storage_configuration/test_available_jobs_and_trans.py
- tests/integration/shared_storage_configuration/test_client_mount_management.py
This patch pulls out the core python bits from the aggregated locks and actions patches and puts them into a single base patch upon which other patches will live on top of.
> Locks and Actions Base

- Cargo.lock
- iml-agent-comms/Cargo.toml
- iml-agent-comms/src/flush_queue.rs
- iml-agent-comms/src/host.rs
- iml-agent-comms/src/main.rs
- iml-agent-comms/src/session.rs
- iml-agent/Cargo.toml
- iml-agent/src/agent_error.rs
- iml-agent/src/daemon_plugins/action_runner.rs
- iml-agent/src/http_comms/session.rs
- iml-agent/src/poller.rs
- iml-agent/src/reader.rs
Use the parking-lot Mutex over the std::sync::Mutex.
> Use parking-lot Mutex

- iml-services/tests/action_runner_tests.rs
An action_runner integration test was intermittently hanging.
I think this is because I was using a while loop which didn't yield long
enough for another thread to gain access to the mutex and place a value
in.
Use a loop_fn instead, with a delay of 10 milliseconds to yield the mutex back.
> Fix hanging test

- tests/framework/integration/upgrade_os/jenkins_steps/main
Use the cleanup.sh script for upgrade testing.
> Use the cleanup.sh script

- Cargo.lock
- iml-agent/Cargo.toml
- iml-agent/src/fs.rs
> Support streaming of directory contents

- tests/integration/core/api_testcase_with_test_reset.py
> Ensure ZFS settings are retained across reboots

- lustre-client.repo
- lustre-server.repo
- tests/framework/utils/defaults.sh.in
> Use Lustre 2.12.1 from download site when available

- tests/framework/integration/installation_and_upgrade/run_tests
Try using 4.0.10.1 and it's new copr repo for upgrade testing.
> Try using 4.0.10.1 for upgrades

- tests/integration/core/api_testcase_with_test_reset.py
> Fix iml_zfs_module_parameters.conf

- ci/azure-5.0-release-pipeline.yml
- ci/azure-devel-release-pipeline.yml
> Do not build PRs for 5.0

- .copr/Makefile
- MANIFEST.in
- python-iml-manager.spec
> Scripts folder missing under /usr/share/chroma-manager

- tests/integration/shared_storage_configuration/test_corosync.py
> Ensure hosts are talking to each other.

- chroma_core/models/host.py
- tests/unit/chroma_core/helpers/mock_agent_rpc.py
If selinux is not "Disabled", then reboot node.
Fixes Issues #934 #925 
> Check selinux status in RebootIfNeeded

- iml-power-control.service
- Load power-control service after rabbitmq-server.service
> Load power-control service after rabbitmq-server.service

- iml-wasm-components/Cargo.lock
- iml-wasm-components/iml-action-dropdown/Cargo.toml
> Bump wasm bindgen dep

- chroma_core/services/plugin_runner/resource_manager.py
> Minor fixup for Resource Manager

- base_managed_ib_RH7.profile
- lustre-server-mlnx.repo
This adds a profile that will support Mellanox OFED.
Fixes Issue #702 
> Add Managed MLNX Profile

- iml-wasm-components/Cargo.lock
- iml-wasm-components/iml-action-dropdown/src/snapshots/tests__group_actions_by_label_1.snap
- iml-wasm-components/iml-action-dropdown/src/snapshots/tests__group_actions_by_label_2.snap
- iml-wasm-components/iml-action-dropdown/src/snapshots/tests__locks_list.snap
Fix wasm insta snapshots so they contain
the expected trailing comma.
> Fix wasm snapshots

- ci/template/azure-test-coverage.yml
Fixup the covergage test by refreshing ubuntu repos before attempting
install.
> Fixup coverage test

- Cargo.lock
- iml-agent-comms/Cargo.toml
- iml-agent/Cargo.toml
- iml-agent/src/agent_error.rs
- iml-agent/src/http_comms/hyper_client.rs
- iml-agent/src/http_comms/mailbox_client.rs
- iml-agent/src/http_comms/mod.rs
- iml-agent/src/server_properties.rs
- iml-services/Cargo.toml
- iml-warp-drive/Cargo.toml
- tokio-runtime-shutdown/Cargo.toml
Implement a client to stream data to <-> from the iml_mailbox service.
- bump deps.
> Implement mailbox_client

- Cargo.lock
- iml-agent/src/action_plugins/action_plugin.rs
- iml-agent/src/action_plugins/stratagem/server.rs
- iml-agent/src/cli.rs
Add a new action that will stream all `MailboxFiles` given in parallel.
> Add stream_fidlists action.

- iml-wasm-components/Cargo.lock
- iml-wasm-components/iml-action-dropdown/Cargo.toml
- iml-wasm-components/iml-action-dropdown/src/fetch_actions.rs
- iml-wasm-components/iml-action-dropdown/src/lib.rs
> Bump seed to the latest version.

- ci/azure-5.0-release-pipeline.yml
- ci/azure-test-pipeline.yml
- ci/template/azure-build-check.yml
- ci/template/azure-install-rust.yml
- ci/template/azure-release.yml
- iml-wasm-components/.copr/Makefile
- iml-wasm-components/build.sh
- iml-wasm-components/iml-action-dropdown/Cargo.toml
- iml-wasm-components/iml-action-dropdown/src/lib.rs
- iml-wasm-components/iml-duration-picker/cargo.toml
- iml-wasm-components/iml-duration-picker/src/lib.rs
- iml-wasm-components/iml-tooltip/src/lib.rs
Add a new seed component for choosing a duration.
> Add duration picker component

- iml-agent/src/action_plugins/stratagem/server.rs
- iml-agent/src/cli.rs
A few visual fixups for the iml-agent cli.
> Some small fixups for agent cli

- base.repo.in
- chroma_core/lib/service_config.py
- docker/docker-compose.override.yml
- docker/docker-compose.yml
- python-iml-manager.spec
- tests/framework/chroma_support.repo.in
> Add influxdb to base.repo and Requires

- iml-agent/src/action_plugins/action_plugin.rs
The agent plugin types can be simplified slightly by using `fn` instead
of `Fn`.
> Simplify plugin types

- iml-agent/src/action_plugins/action_plugin.rs
- iml-agent/src/action_plugins/stratagem/action_warning.rs
- iml-agent/src/lib.rs
> Wire up client action plugins

- Cargo.lock
- Cargo.toml
- iml-agent/Cargo.toml
- iml-manager-env/src/lib.rs
- iml-postgres/Cargo.toml
- iml-postgres/src/lib.rs
Add a new crate so services can utilize postgres
within rust.
> Add iml-postgres crate

- iml-agent/src/action_plugins/stratagem/server.rs
- iml-agent/src/cli.rs
warn and purge should be mutally exclusive rules.
While were updating the agent, add flags to report and purge and make
them optional.
> Split config between warn and purge rules

- Cargo.lock
- Cargo.toml
- iml-manager-cli/Cargo.toml
- iml-manager-cli/src/api_utils.rs
- iml-manager-cli/src/lib.rs
- iml-manager-cli/src/main.rs
- iml-manager-cli/src/manager_cli_error.rs
- iml-manager-client/Cargo.toml
- iml-manager-client/src/lib.rs
so it can be used between modules.
> Extract manager API client

- iml-wasm-components/iml-environment/Cargo.toml
- iml-wasm-components/iml-environment/src/lib.rs
- iml-wasm-components/iml-utils/Cargo.toml
- iml-wasm-components/iml-utils/src/lib.rs
Add some new modules to help with utility fns
and environment in the browser.
> Add util and enviroment wasm modules

- Cargo.lock
- iml-agent-comms/Cargo.toml
- iml-agent/Cargo.toml
- iml-manager-cli/Cargo.toml
- iml-rabbit/Cargo.toml
- iml-services/Cargo.toml
- iml-wire-types/Cargo.toml
- iml-wire-types/src/lib.rs
> Add alert endpoint type

- iml-wasm-components/Cargo.lock
- iml-wasm-components/Cargo.toml
- iml-wasm-components/iml-popover/Cargo.toml
- iml-wasm-components/iml-popover/src/lib.rs
Create a popover component in seed.
> Create popover component

- iml-wasm-components/Cargo.lock
- iml-wasm-components/Cargo.toml
- iml-wasm-components/iml-alert-indicator/Cargo.toml
- iml-wasm-components/iml-alert-indicator/src/lib.rs
Implement the alert indicator component in seed.
> Implement Alert indicator

- lustre-client.repo
- lustre-server-patchless.repo
- lustre-server.repo
- tests/framework/utils/defaults.sh.in
> Add support for Lustre 2.12.2

- Cargo.lock
- iml-wire-types/Cargo.toml
- iml-wire-types/src/lib.rs
> Add a few PartialEq derives

- tests/integration/shared_storage_configuration/test_anonymous_access_control.py
> Fix TestAnonymousAccessControl

- tests/integration/installation_and_upgrade/test_data_consistancy.py
Add stratagem endpoints to end point exception
> Add stratagem endpoints to end point exception

- .copr/Makefile
- Makefile
Allow building against lustre or lustre-client locally.
> Fix local build of rust rpms

- iml-wasm-components/Cargo.lock
- iml-wasm-components/Cargo.toml
- iml-wasm-components/iml-toggle/Cargo.toml
- iml-wasm-components/iml-toggle/toggle.rs
> Implement toggle module

- iml-wasm-components/Cargo.lock
- iml-wasm-components/bootstrap-components/bootstrap.rs
- iml-wasm-components/iml-stratagem/Cargo.toml
- iml-wasm-components/iml-stratagem/src/inode_error.rs
- iml-wasm-components/iml-stratagem/src/inode_table.rs
- iml-wasm-components/iml-stratagem/src/lib.rs
Implement inode users component
> Gh 1051 Implement inode users component

- Cargo.lock
- iml-warp-drive/Cargo.toml
- iml-wasm-components/Cargo.lock
- iml-wasm-components/iml-fs-page/fs-page.rs
- iml-wire-types/Cargo.toml
- python-iml-manager.spec
> Add rust-iml-cli as manager req

- chroma_core/lib/detection.py
> Add mount_point for detect scan in monitored mode.

- chroma_core/lib/util.py
- chroma_core/models/filesystem.py
- chroma_core/services/job_scheduler/job_scheduler.py
> Skip All MDTs not MDT0 for filesystem "unavailable" state

- chroma_core/models/stratagem.py
Create/destroy systemd service and timer.
Fixes #1048
> Add (Un)Configure stratagem timer

- Cargo.lock
- chroma_core/models/stratagem.py
- iml-agent/src/action_plugins/stratagem/server.rs
> Integrate with newest upstream changes

- chroma_api/stratagem.py
- chroma_core/lib/service_config.py
- chroma_core/models/stratagem.py
- grafana/dashboards/stratagem-dashboard-1.json
- grafana/grafana-iml.ini
- iml-wasm-components/Cargo.lock
- iml-wasm-components/Cargo.toml
- iml-wasm-components/iml-duration-picker/Cargo.toml
- iml-wasm-components/iml-duration-picker/src/lib.rs
- iml-wasm-components/iml-environment/src/lib.rs
- iml-wasm-components/iml-fs/Cargo.toml
- iml-wasm-components/iml-fs/src/fs_detail_page.rs
- iml-wasm-components/iml-grafana-chart/src/lib.rs
- iml-wasm-components/iml-stratagem/Cargo.toml
- iml-wasm-components/iml-stratagem/src/add_stratagem_button.rs
- iml-wasm-components/iml-stratagem/src/delete_stratagem_button.rs
- iml-wasm-components/iml-stratagem/src/enable_stratagem_button.rs
- iml-wasm-components/iml-stratagem/src/inode_table.rs
- iml-wasm-components/iml-stratagem/src/lib.rs
- iml-wasm-components/iml-stratagem/src/update_stratagem_button.rs
- iml-wasm-components/iml-toggle/toggle.rs
- iml-wasm-components/iml-tooltip/src/lib.rs
- iml-wasm-components/iml-wasm/Cargo.toml
- iml-wasm-components/iml-wasm/src/lib.rs
> Implement stratagem configuration component

- chroma_core/models/target.py
> Remove mtm when removing target

- chroma_core/lib/util.py
> Fix splitting devices with hyphenated filesystem names

- Cargo.lock
- iml-agent/Cargo.toml
- iml-agent/src/action_plugins/stratagem/action_warning.rs
- iml-agent/src/agent_error.rs
- iml-fs/src/lib.rs
> Write filepaths instead of csv data

- chroma_core/models/stratagem.py
- iml-agent/src/action_plugins/stratagem/server.rs
> Do not count directories

- Cargo.lock
- iml-agent-comms/Cargo.toml
- iml-agent/src/action_plugins/stratagem/action_warning.rs
- iml-manager-cli/Cargo.toml
> Add trailing newline to each 1000 fid chunks.

- iml-wasm-components/iml-fs/src/fs_detail_page.rs
> Fix table formatting

- iml-wasm-components/iml-stratagem/src/lib.rs
> Make last column potentially fixed for stratagem config.

- chroma_api/stratagem.py
- chroma_core/models/stratagem.py
- iml-manager-cli/src/manager_cli_error.rs
Check durations are non-negative
Fixes #1128
> Stratagem API checks

- iml-wasm-components/Cargo.lock
- iml-wasm-components/iml-stratagem/Cargo.toml
- iml-wasm-components/iml-stratagem/src/delete_stratagem_button.rs
- iml-wasm-components/iml-stratagem/src/enable_stratagem_button.rs
- iml-wasm-components/iml-stratagem/src/inode_table.rs
- iml-wasm-components/iml-stratagem/src/lib.rs
- iml-wasm-components/iml-stratagem/src/update_stratagem_button.rs
- Update button text to read "Update"
- Update button text to read "Enable"
- Update button text to read "Delete"
- Show last known scan time on inode chart (Still need to do this for
the file size distribution graph)
- Always display the inode table and the graph
> Stratagem Updates

- iml-agent/src/action_plugins/stratagem/action_purge.rs
- iml-agent/src/cli.rs
- liblustreapi-types/build.rs
- liblustreapi-types/src/bindings.rs
- liblustreapi/src/lib.rs
> Optionally use llapi_rmfids if it's available

- chroma_core/lib/service_config.py
Add usage info for repos and profile sub commands
Remove unreferenced profiles and packages when re-registering profile.
Fixes #1086
> Chroma config profile

- Cargo.lock
- chroma_core/lib/stratagem.py
- chroma_core/models/stratagem.py
- grafana/dashboards/stratagem-dashboard-1.json
- iml-agent/Cargo.toml
- iml-agent/src/action_plugins/stratagem/server.rs
- iml-agent/src/cli.rs
- iml-wasm-components/iml-fs/src/fs_detail_page.rs
- iml-wasm-components/iml-stratagem/src/inode_table.rs
- iml-wasm-components/iml-stratagem/src/lib.rs
> Add support for returning sizes of file counts.

- iml-warp-drive/src/main.rs
> Fix warp-drive to start server after API request finishes.

- iml-manager-cli/src/stratagem.rs
replace the word configure with interval.
> Update stratagem cli wording

- iml-manager-cli/src/api_utils.rs
- iml-manager-cli/src/stratagem.rs
- iml-manager-client/src/lib.rs
- iml-wire-types/src/lib.rs
> Add command to update stratagem interval

- Cargo.lock
- iml-agent/Cargo.toml
- iml-agent/src/action_plugins/action_plugin.rs
- iml-agent/src/action_plugins/stratagem/action_purge.rs
- iml-agent/src/action_plugins/stratagem/action_warning.rs
- iml-agent/src/cli.rs
- iml-agent/src/daemon_plugins/daemon_plugin.rs
- iml-agent/src/http_comms/agent_client.rs
- iml-agent/src/http_comms/mailbox_client.rs
- iml-agent/src/http_comms/session.rs
- iml-agent/src/main.rs
- iml-agent/src/poller.rs
- iml-agent/src/reader.rs
> Use tracing instead of log

- tests/framework/integration/existing_filesystem_configuration/cluster_setup
- tests/framework/integration/installation_and_upgrade/run_tests
- tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup.in
- tests/framework/utils/selective_auto_pass.sh
> Add support for manager-side pragma

- .travis.yml
- ci/azure-5.0-release-pipeline.yml
- python-iml-manager.spec
- scm_version.py
- setup.py
> Update IML version to 5.1.0

- iml-wasm-components/iml-wasm-components.spec
- python-iml-manager.spec
> Rev minimum versions of deps for 5.1

- chroma_core/models/stratagem.py
> Fix serial scanning

- chroma_core/models/stratagem.py
- chroma_core/services/job_scheduler/job_scheduler.py
- chroma_core/south_migrations/0046_auto__add_sendstratagemresultstoclientjob__add_stratagemconfiguration_.py
> Fix race condition clearing temp table

- chroma_core/models/host.py
- chroma_core/models/utils.py
> Lower all alerts associated with a host when it is removed

- iml-wire-types/wire-types.rs
> Add ComponentState structs and sub enums

- iml-wire-types/wire-types.rs
> RunState::Stopped for inactive and disabled

- python-iml-manager.spec
- rust-iml.spec
Rust services need to be bumped to 0.1.2
> Bump rust iml to 0.1.2

- rust-iml.spec
> - Fix date in changelog

- .travis.yml
> Fix travis unit test failures

- python-iml-manager.spec
> Remove old egg info upon upgrade.

- lustre-client-mlnx.repo
- lustre-client.repo
- lustre-server-mlnx.repo
- lustre-server-patchless.repo
- lustre-server.repo
- tests/framework/utils/defaults.sh.in
Fixes #1260.
Description:
Support 2.12.3 RC
> GH-1260 - Support Lustre 2.12.3

- tests/framework/chroma_support.repo.in
This fixes variablility in yum $releasever variable.
> Lock influxdb yum repo to "7"

- base_managed_patchless.profile
- tests/framework/integration/existing_filesystem_configuration/cluster_setup
- tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup.in
2.12.3 patchless only runs on el7.7
Issue #1267
> Fix patchless validate for 2.12.3

- Cargo.lock
- iml-agent/Cargo.toml
- iml-agent/src/action_plugins/action_plugin.rs
- iml-agent/src/action_plugins/check_ha.rs
- iml-agent/src/action_plugins/stratagem/action_purge.rs
- iml-agent/src/action_plugins/stratagem/action_warning.rs
- iml-agent/src/action_plugins/stratagem/server.rs
- iml-agent/src/agent_error.rs
- iml-agent/src/cli.rs
- iml-agent/src/cmd.rs
- iml-agent/src/daemon_plugins/action_runner.rs
- iml-agent/src/daemon_plugins/daemon_plugin.rs
- iml-agent/src/http_comms/agent_client.rs
- iml-agent/src/http_comms/crypto_client.rs
- iml-agent/src/http_comms/hyper_client.rs
- iml-agent/src/http_comms/mailbox_client.rs
- iml-agent/src/http_comms/session.rs
- iml-agent/src/main.rs
- iml-agent/src/poller.rs
- iml-agent/src/reader.rs
- iml-agent/src/systemd.rs
- liblustreapi-types/Cargo.toml
- liblustreapi/Cargo.toml
- liblustreapi/src/error.rs
- liblustreapi/src/lib.rs
> Batch purge operations.

- chroma_core/lib/service_config.py
Which should be equivalent enough
> Swap rabbitmq stop / start with restart

- chroma_cli/parser.py
- chroma_core/models/host.py
- docker/iml-warp-drive.dockerfile
- requirements.test
- requirements.txt
- settings.py
- tests/integration/core/constants.py
- tests/services/test_agent_rpc.py
- tests/unit/chroma_api/test_stats.py
- tests/unit/chroma_api/test_target.py
- tests/unit/chroma_core/models/test_samples.py
- tests/unit/chroma_core/models/test_series.py
> Black formatting fixes.

- iml-agent/src/action_plugins/action_plugin.rs
- iml-agent/src/action_plugins/check_stonith.rs
- iml-agent/src/action_plugins/mod.rs
- iml-agent/src/agent_error.rs
- iml-agent/src/cli.rs
Call to check_stonith() to see if stonith is enabled and configured.
Return true/false plus explanitory text.
Fixes Issue #1191
> Agent check_stonith

- .github/workflows/wasm-ci.yml
- iml-manager-cli/src/api_utils.rs
- iml-manager-cli/src/update_repo_file.rs
Some of the wasm-ci checks are not checking the right thing. Fix them.
> Fixup action checks

- Cargo.lock
- iml-agent/src/action_plugins/action_plugin.rs
- iml-agent/src/daemon_plugins/daemon_plugin.rs
- iml-agent/src/systemd.rs
- iml-wire-types/wire-types.rs
Add some systemd action plugins so we can control remote systemd units
and query their state.
> Add systemd action plugins

- .travis.yml
> Fix service testing

- iml-wasm-components/Cargo.lock
> Bump wasm deps

- chroma_api/alert.py
- chroma_api/authentication.py
- chroma_api/command.py
- chroma_api/log.py
- chroma_api/session.py
- chroma_api/user.py
user.is_authenticated is now a property and the method form
will be removed in a later version.
> Fix RemovedInDjango20Warning for user.is_authenticated

- Cargo.lock
- iml-agent-comms/src/error.rs
- iml-agent-comms/src/main.rs
- iml-mailbox/src/lib.rs
- iml-mailbox/src/main.rs
- iml-services/iml-action-runner/src/error.rs
- iml-services/iml-action-runner/src/sender.rs
- iml-services/iml-action-runner/tests/action_runner_tests.rs
- iml-warp-drive/src/error.rs
Bump rust iml deps and account for new rejection system in warp.
> Bump deps (rust-iml)

- iml-manager-cli/src/api_utils.rs
- iml-manager-cli/src/server.rs
- iml-manager-cli/src/stratagem.rs
- iml-manager-client-3/src/lib.rs
- python-iml-manager.spec
- rust-iml.spec
> Backport #1339

- iml-wasm-components/Cargo.lock
> Bump wasm-bindgen version

- Cargo.lock
- iml-services/Cargo.toml
- iml-services/src/services/action_runner/main.rs
- iml-util/Cargo.toml
- iml-util/util.rs
- iml-wasm-components/Cargo.lock
- python-iml-manager.spec
- Integrate tokio utils for port / socket listeners
- Update action runner to run off either a unix socket or an http port
> Tokio utils

- chroma_api/alert.py
- chroma_api/authentication.py
- chroma_api/command.py
- chroma_api/log.py
- chroma_api/session.py
- chroma_api/user.py
This reverts commit 21973d6b33250b21c24d75a92264d8d342372626.
> Revert "Fix RemovedInDjango20Warning for user.is_authenticated (#1334)"

- iml-gui/crate/Cargo.lock
- iml-gui/crate/Cargo.toml
- iml-gui/crate/src/lib.rs
- iml-gui/entries/index.hbs
> Bump seed to latest version.

- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/partial/header.rs
> Use to string of Page for menu display

- chroma_core/lib/job.py
> Fix issue with possible non-existent host.fqdn during AgentException

- iml-gui/crate/src/components/breadcrumbs.rs
- iml-gui/crate/src/components/mod.rs
- iml-gui/crate/src/generated/css_classes.rs
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/partial/header.rs
- iml-gui/css/custom.css
https://github.com/whamcloud/integrated-manager-for-lustre/issues/1331.
**Normal**
**Overflow**
> Add breadcrumbs

- iml-agent/src/action_plugins/action_plugin.rs
- iml-agent/src/action_plugins/lctl.rs
- iml-agent/src/action_plugins/mod.rs
lctl(Vec<String>) -> String
Fixes Issue #1378 
> agent: Add lctl action plugin

- iml-manager-cli/src/main.rs
> Fixup manager cli name

- .travis.yml
- docker/iml-action-runner.dockerfile
- docker/iml-agent-comms.dockerfile
- docker/iml-manager-cli.dockerfile
- docker/iml-stratagem.dockerfile
- docker/iml-warp-drive.dockerfile
- docker/iml-wasm-components.dockerfile
- docker/rust-base.dockerfile
> Try parallel compose building

- chroma_api/filesystem.py
> Add missing imports

- iml-agent/src/action_plugins/action_plugin.rs
Add action_plugin action for get_kernel.
Fixes #1293 
> agent: Add get_kernel action to action_plugins

- iml-agent/src/action_plugins/action_plugin.rs
- iml-agent/src/action_plugins/mod.rs
- iml-agent/src/action_plugins/package.rs
- iml-agent/src/action_plugins/package_installed.rs
- iml-agent/src/action_plugins/package_version.rs
- iml-agent/src/cli.rs
- iml-agent/src/rpm.rs
> Implement getting RPM package version

- iml-agent-comms/src/main.rs
- iml-agent/src/action_plugins/ntp/action_configure.rs
- iml-agent/src/reader.rs
- iml-services/iml-action-runner/src/main.rs
- iml-services/iml-action-runner/src/sender.rs
- iml-services/iml-action-runner/tests/action_runner_tests.rs
- iml-warp-drive/src/main.rs
> Fix formatting for rust 1.40

- iml-gui/crate/src/components/mod.rs
- iml-gui/crate/src/components/paging.rs
> Implement paging component

- Cargo.lock
- iml-agent-comms/Cargo.toml
- iml-agent/Cargo.toml
- iml-fs/Cargo.toml
- iml-fs/src/lib.rs
- iml-mailbox/Cargo.toml
- iml-mailbox/src/lib.rs
- iml-manager-cli/Cargo.toml
- iml-manager-client/Cargo.toml
- iml-rabbit/Cargo.toml
- iml-request-retry/Cargo.toml
- iml-services/iml-action-runner/Cargo.toml
- iml-services/iml-stratagem/Cargo.toml
- iml-util/Cargo.toml
- iml-warp-drive/Cargo.toml
- iml-warp-drive/src/main.rs
- liblustreapi/Cargo.toml
- tokio-runtime-shutdown/Cargo.toml
This patch refactors warp and reqwest usages based on latest changes.
> Bump warp and reqwest to latest in github

- Cargo.lock
- iml-agent/Cargo.toml
- iml-agent/src/cli.rs
- iml-manager-cli/Cargo.toml
- iml-manager-cli/src/display_utils.rs
- liblustreapi-types/build.rs
Remove termion dep which is not compatible with Windows.
> Remove termion

- iml-agent/src/action_plugins/action_plugin.rs
- iml-agent/src/action_plugins/kernel_module.rs
- iml-agent/src/cli.rs
Handle second part of point 2 of https://github.com/whamcloud/integrated-manager-for-lustre/issues/1187#issuecomment-559830336
> Implement getting kernel module version

- tests/unit/chroma_core/helpers/mock_agent_rpc.py
- tests/unit/services/job_scheduler/host/test_host.py
- tests/unit/services/job_scheduler/host/test_host_contact.py
> Reenable job_scheduler/host tests

- .dockerignore
- base.dockerfile.dockerignore
- docker/base.dockerfile
- docker/iml-wasm-components.dockerfile
- docker/rust-base.dockerfile
- docker/setup.dockerfile
> Trim down docker image size

- iml-agent/src/action_plugins/action_plugin.rs
- iml-fs/src/lib.rs
- iml-util/util.rs
- number-formatter/src/lib.rs
> Fix a few clippy warnings

- Cargo.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1444)
> Commit Cargo.lock

- Cargo.lock
- iml-agent/src/daemon_plugins/ostpool.rs
- iml-manager-cli/src/ostpool.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1450)
> A few small fixups

- iml-manager-cli/src/server.rs
- vagrant/Vagrantfile
- vagrant/scripts/install_iml_local.sh
- vagrant/scripts/install_iml_local_agent.sh
This patch implements provisioning / installation of both Python and
Rust code from the local repo on both the manager and agent nodes.
Previously only the python code was built / installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1455)
> Implement full local provisioning

- .copr/Makefile
- .github/actions/copr/action.yml
- .github/workflows/devel-release.yml
- .github/workflows/iml-docker-ci.yml
- .github/workflows/prod-release.yml
- iml-docker.spec
Create a new spec / rpm `iml-docker` that will install the
docker-compose.yml into the expected place.
Fixes #1457.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1459)
> Implement spec and CI for iml-docker

- vagrant/Vagrantfile
Fixes #1469.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1474)
> Make memory and cpu configurable in Vagrant

- iml-gui/crate/src/components/lnet_status.rs
- iml-gui/crate/src/components/mod.rs
- iml-gui/crate/src/lib.rs
Fixes #1465.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1466)
> Implement LNet Status Indicator component

- iml-agent/src/action_plugins/check_ha.rs
- iml-agent/src/action_plugins/snapshots/check_ha_test_mixed_mode.xml
- iml-agent/src/cli.rs
- iml-wire-types/wire-types.rs
check_ha use ComponentState
convert current check_ha to get_ha_resource_list()
Issue #1190 #1232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1288)
> check_ha use ComponentState

- Cargo.lock
- iml-agent-comms/Cargo.toml
- iml-mailbox/Cargo.toml
- iml-request-retry/Cargo.toml
- iml-services/iml-action-runner/Cargo.toml
- iml-warp-drive/Cargo.toml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1492)
> Bump warp to 0.2

- .copr/Makefile
Fixes #1490.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1491)
> Disable buildtools repo when we are done using it.

- tests/framework/test_reporting/aggregate_test_results.py
- tests/utils/http_requests.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1507)
> Attempt to fix insecure request warnings in Jenkins.

- vagrant/scripts/install_iml_local.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1508)
> Stop local manager install on error

- iml-services/iml-ostpool/src/main.rs
Fixes #1509 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1510)
> Account for missing FS in iml-ostpool service

- chroma_core/models/host.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1516)
> fixup formatting

- iml-gui/crate/src/components/activity_indicator.rs
- iml-gui/crate/src/components/font_awesome.rs
- iml-gui/crate/src/components/paging.rs
- iml-gui/crate/src/components/tree.rs
- iml-gui/crate/src/page/partial/header.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1441)
> Use class _mt_1 for font_awesome where needed

- Cargo.lock
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1547)
> Switch to new Cargo.lock format

- chroma_core/lib/service_config.py
Update profile usage also
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1545)
> Add chroma-config profile list

- iml-gui/crate/src/auth.rs
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/filesystem_detail.rs
- iml-gui/crate/src/page/login.rs
- iml-gui/crate/src/page/mod.rs
- iml-gui/crate/src/page/ostpool_detail.rs
- iml-gui/crate/src/page/server.rs
- iml-gui/crate/src/page/server_detail.rs
- iml-gui/crate/src/page/target_detail.rs
- iml-gui/crate/src/page/user_detail.rs
- iml-gui/crate/src/page/volume_detail.rs
- iml-gui/crate/src/route.rs
Fixes #1539.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1543)
> Add page enum

- iml-manager-cli/src/error.rs
- iml-manager-cli/src/server.rs
Fix another clippy error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1550)
> Fix clippy error

- docker/docker-compose.yml
- docker/iml-mailbox.dockerfile
- docker/iml-mailbox/iml-mailbox.conf
- docker/iml-mailbox/iml-mailbox.service
- docker/setup-nginx
A dedicated docker service needs to be created to represent the mailbox that is used to store large amounts of data that can be streamed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1411)
> Integrate Mailbox into docker

- .github/workflows/devel-release.yml
- .github/workflows/iml-docker-ci.yml
- .github/workflows/iml-gui.yml
- .github/workflows/prod-release.yml
- Ensure all workflows only run once.
- Update devel and prod deployments so iml-docker rpm get's built
correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1561)
> Cleanup github actions

- iml-mailbox/src/lib.rs
- iml-mailbox/src/main.rs
If an incoming stream outpaces processing in the mailbox, it will close
before all lines have been flushed to disk.
If this occurs, we may end up trying to process things (ex report /
purge of fids) with an incomplete list.
This patch synchonizes writing all lines to disk such that a connection
will not close until the EOF has been processed and the data is flushed
to disk.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1560)
> Synchronize file processing with incoming streams

- iml-gui/crate/src/components/alert_indicator.rs
- iml-gui/crate/src/components/attrs.rs
- iml-gui/crate/src/components/lock_indicator.rs
- iml-gui/crate/src/components/mod.rs
- iml-gui/crate/src/components/tooltip.rs
Closes #1558.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1563)
> Create a module with common attributes

- iml-gui/crate/Cargo.lock
- iml-gui/crate/Cargo.toml
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/login.rs
Bump to seed 0.6.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1564)
> Bump to latest seed

- iml-gui/crate/src/components/tree.rs
I was planning to reuse it, but probably I will not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1572)
> Refactor get_targets_by_fs_id()

- Cargo.lock
- chroma_core/migrations/0009_django_content_type_json_notify.py
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/test_utils/fixtures.rs
- iml-postgres/Cargo.toml
- iml-warp-drive/Cargo.toml
- iml-warp-drive/src/cache.rs
- iml-warp-drive/src/db_record.rs
- iml-wire-types/Cargo.toml
- iml-wire-types/src/db.rs
- iml-wire-types/src/lib.rs
- iml-wire-types/src/warp_drive.rs
Fixes #1576.
COPR Module Manager: managerforlustre/content-type-arc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1580)
> Allow conversion from `CompositeId` to an erased `ArcCache` record

- docker/docker-compose.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1579)
> Try to use alpine images for postgres and rabbit.

- iml-gui/configs/webpack.config.js
- iml-gui/crate/Cargo.lock
- iml-gui/crate/src/components/action_dropdown/confirm_action_modal.rs
- iml-gui/crate/src/components/action_dropdown/mod.rs
- iml-gui/crate/src/components/dropdown.rs
- iml-gui/crate/src/components/lnet_status.rs
- iml-gui/crate/src/components/lock_indicator.rs
- iml-gui/crate/src/components/mod.rs
- iml-gui/crate/src/components/modal.rs
- iml-gui/crate/src/components/paging.rs
- iml-gui/crate/src/components/tooltip.rs
- iml-gui/crate/src/extensions.rs
- iml-gui/crate/src/generated/css_classes.rs
- iml-gui/crate/src/key_codes.rs
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/server.rs
- iml-gui/css/custom.css
- iml-gui/package.json
- iml-gui/yarn.lock
- iml-wire-types/src/db.rs
- iml-wire-types/src/lib.rs
- iml-wire-types/src/warp_drive.rs
Fixes #1448.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1449)
> Implement action-dropdown

- Cargo.lock
- iml-manager-client/Cargo.toml
- iml-manager-client/src/lib.rs
- iml-request-retry/README.md
- iml-warp-drive/src/cache.rs
Fixes #1591.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1592)
> Implement get-retry

- iml-gui/crate/src/page/mod.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1596)
> Fixup page init

- iml-gui/crate/Cargo.lock
- iml-gui/crate/Cargo.toml
- iml-gui/crate/src/components/alert_indicator.rs
- iml-gui/crate/src/components/lnet_status.rs
- iml-gui/crate/src/components/lock_indicator.rs
- iml-gui/crate/src/components/mod.rs
- iml-gui/crate/src/components/pie_chart.rs
- iml-gui/crate/src/components/table.rs
- iml-gui/crate/src/components/tree.rs
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/dashboard.rs
- iml-gui/crate/src/page/filesystem.rs
- iml-gui/crate/src/page/filesystems.rs
- iml-gui/crate/src/page/mod.rs
- iml-gui/crate/src/page/servers.rs
- iml-gui/crate/src/route.rs
- iml-wire-types/src/lib.rs
Ref. #1354 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1497)
> Implement Filesystem pages

- .github/workflows/iml-gui.yml
- .github/workflows/rust-ci.yml
- .github/workflows/wasm-ci.yml
- Cargo.lock
- iml-gui/crate/src/page/filesystem.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1598)
> Commit forgotten Cargo.lock and require it being always committed on CI

- iml-job-scheduler-rpc/src/lib.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1599)
> ensure we close channel after making rpc call

- chroma_cli/handlers.py
- chroma_core/models/host.py
- chroma_core/models/host_jobs/test_host_contact.py
- chroma_help/help.py
If base packages (ServerProfile::base_packages) are installed and no yum repos are enabled
Assume everything is pre-installed
Fixes #1581
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1600)
> Conditionally skip yum check

- .copr/Makefile
- .dockerignore
- .github/workflows/devel-release.yml
- .github/workflows/iml-gui.yml
- Makefile
- chroma-manager.conf.template
- docker/Makefile
- docker/iml-gui.dockerfile
- docker/nginx.dockerfile
- iml-api/src/action.rs
- iml-gui/configs/webpack.config.js
- iml-gui/crate/src/event_source.rs
- iml-gui/crate/src/extensions.rs
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/notification.rs
- iml-gui/crate/src/route.rs
- iml-gui/entries/index.hbs
- iml-gui/entries/templates/favicons.hbs
- iml-gui/entries/templates/head_scripts.hbs
- iml-gui/package.json
- iml-gui/rust-iml-gui.spec
- iml-gui/yarn.lock
- python-iml-manager.spec
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1603)
> Package new GUI as RPM and docker image

- .copr/Makefile
- iml-docker.spec
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1613)
> Fixup deploys for iml-docker and rust-iml-gui

- Cargo.lock
- iml-agent/Cargo.toml
- iml-agent/src/cli.rs
- iml-manager-cli/Cargo.toml
- iml-manager-cli/src/main.rs
- iml-manager-cli/src/server.rs
- iml-manager-cli/src/stratagem.rs
- iml-timer/Cargo.toml
Move all StructOpt versions to 0.3
Issue #1487 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1614)
> Add Private key and Password auth types to server add

- iml-manager-cli/src/filesystem.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1616)
> Add filesystem detect command

- Makefile
- docker/docker-compose.yml
- docker/setup.sh
- iml-docker.spec
Setup dir: /etc/iml-docker/setup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1619)
> Add repos/profiles during setup

- iml-gui/crate/src/components/action_dropdown/confirm_action_modal.rs
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/filesystem.rs
- iml-gui/crate/src/page/filesystems.rs
Fixes #1622.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1623)
> Add paging / updates and removes to the filesystem page

- chroma_core/models/host_jobs/test_host_contact.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1624)
> Only check for rpms installed not repos disabled

- iml-gui/configs/webpack.config.js
- iml-gui/crate/src/event_source.rs
To what the defaults everywhere else are
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1626)
> Switch the default port

- iml-gui/crate/src/page/partial/header.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1625)
> Remove some pages from header

- iml-agent/src/action_plugins/high_availability/mod.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1629)
> Return empty list if resource list is empty in get_ha_resource_list

- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/filesystem.rs
- iml-gui/crate/src/page/mod.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1630)
> Pass in fs model during page conversion

- iml-manager-cli/src/filesystem.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1631)
> Only pass hosts argument to DetectTarget if there are hosts

- chroma_core/models/target.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1617)
> Don't allow "Remove" of mgs with MasterTicket

- docker/iml-cli-proxy.sh
- iml-docker.service
even systemctl return, we should make sure iml command work
Signed-off-by: Minh Diep <mdiep@whamcloud.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1646)
> Add wait for iml service to fully up

- iml-gui/crate/src/components/mod.rs
- iml-gui/crate/src/components/resource_links.rs
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/filesystem.rs
- iml-gui/crate/src/page/filesystems.rs
- iml-gui/crate/src/page/mgt.rs
- iml-gui/crate/src/page/mgts.rs
- iml-gui/crate/src/page/mod.rs
Fixes #1636.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1647)
> Add MGT page

- iml-gui/configs/webpack.config.js
- iml-gui/crate/Cargo.lock
- iml-gui/crate/Cargo.toml
- iml-gui/crate/src/components/grafana_chart.rs
- iml-gui/crate/src/components/mod.rs
- iml-gui/crate/src/components/stratagem/inode_table.rs
- iml-gui/crate/src/components/stratagem/mod.rs
- iml-gui/crate/src/page/filesystem.rs
Ref. #1621 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1648)
> Add grafana charts on the filesystem page

- iml-gui/crate/src/components/grafana_chart.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1656)
> Fix grafana iframe src

- docker/iml-cli-proxy.sh
Signed-off-by: Nathaniel Clark <Nathaniel.Clark@misrule.us>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1657)
> Detect tty for iml proxy cli

- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/status_section.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1659)
> Ensure help links aren't handled by internal routing

- iml-gui/crate/src/auth.rs
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/activity.rs
- iml-gui/crate/src/page/servers.rs
- iml-gui/crate/src/server_date.rs
- iml-gui/crate/src/status_section.rs
Closes #1633.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1662)
> Calculate relative time using server time

- Cargo.lock
- iml-agent/Cargo.toml
- iml-fs/Cargo.toml
- iml-mailbox/Cargo.toml
- iml-manager-cli/Cargo.toml
- iml-services/iml-action-runner/Cargo.toml
- iml-services/iml-ostpool/Cargo.toml
- iml-services/iml-postoffice/Cargo.toml
- iml-services/iml-stats/Cargo.toml
- iml-services/iml-stats/src/main.rs
- iml-wasm-components/Cargo.lock
- iml-wasm-components/iml-action-dropdown/Cargo.toml
- iml-wasm-components/iml-duration-picker/Cargo.toml
- iml-wasm-components/iml-environment/Cargo.toml
- iml-wasm-components/iml-fs/Cargo.toml
- iml-wasm-components/iml-sleep/Cargo.toml
- iml-wasm-components/iml-toggle/Cargo.toml
- iml-wasm-components/iml-tooltip/Cargo.toml
- iml-wasm-components/iml-utils/Cargo.toml
Fixes #1642.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1665)
> Add connected clients to influx

- chroma_core/lib/service_config.py
- docker/docker-compose.yml
Also disable daily reporting callout
Fixes #1673
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1674)
> influx: Disable HTTP logging

- iml-services/iml-stats/Cargo.toml
- iml-services/iml-stats/src/main.rs
To make it easy aggregating by filesystem name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1676)
> Add filesystem name to some influx stats

- Cargo.lock
- chroma_core/migrations/0011_auth_json_notify.py
- iml-gui/crate/src/components/resource_links.rs
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/filesystem.rs
- iml-gui/crate/src/page/users.rs
- iml-gui/crate/src/test_utils/fixtures.rs
- iml-services/iml-stats/src/main.rs
- iml-warp-drive/src/cache.rs
- iml-warp-drive/src/db_record.rs
- iml-wire-types/src/db.rs
- iml-wire-types/src/warp_drive.rs
Fixes #1637.
Implement basic user page.
Add new user will come in separate pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1677)
> Implement first pass of users page

- Cargo.lock
- chroma_api/user.py
- iml-gui/crate/Cargo.lock
- iml-gui/crate/Cargo.toml
- iml-gui/crate/src/components/mod.rs
- iml-gui/crate/src/components/toast.rs
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/login.rs
- iml-gui/crate/src/page/mod.rs
- iml-gui/crate/src/page/partial/header.rs
- iml-gui/crate/src/page/user.rs
- iml-gui/crate/src/route.rs
- iml-warp-drive/src/db_record.rs
- iml-wire-types/src/db.rs
Fixes #1678.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1681)
> Implmement User page

- chroma_core/lib/service_config.py
- docker/docker-compose.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1685)
> influx: disable query logging

- iml-gui/crate/src/components/table.rs
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/about.rs
- iml-gui/crate/src/page/jobstats.rs
- iml-gui/crate/src/page/mod.rs
- iml-gui/crate/src/page/ostpool.rs
- iml-gui/crate/src/page/ostpools.rs
- iml-gui/crate/src/page/power_control.rs
- iml-gui/crate/src/page/server_dashboard.rs
- iml-gui/crate/src/page/servers.rs
- iml-gui/crate/src/page/target_dashboard.rs
- iml-gui/crate/src/page/targets.rs
- iml-gui/crate/src/page/users.rs
- iml-gui/crate/src/page/volume.rs
- iml-gui/crate/src/page/volumes.rs
- iml-warp-drive/src/cache.rs
- iml-wire-types/src/db.rs
- iml-wire-types/src/warp_drive.rs
Fixes #1638.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1686)
> Implement volumes page

- chroma_api/user.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1689)
> fix black formatting

- iml-gui/crate/src/components/chart/fs_usage.rs
- iml-gui/crate/src/page/filesystem.rs
- iml-gui/crate/src/page/filesystems.rs
- iml-gui/crate/src/page/fs_dashboard.rs
- iml-gui/crate/src/page/mod.rs
Closes #1643 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1694)
> Get filesystem stats from influxdb

- iml-gui/crate/src/components/resource_links.rs
- iml-gui/crate/src/components/stratagem/inode_table.rs
- iml-gui/crate/src/components/stratagem/mod.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1697)
> Replace "N/A" with "---"

- vagrant/Vagrantfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1701)
> Add reboot for non iml lustre installs

- iml-gui/crate/Cargo.lock
- iml-gui/crate/Cargo.toml
- iml-gui/crate/src/components/dashboard/mod.rs
- iml-gui/crate/src/components/datepicker.rs
- iml-gui/crate/src/components/grafana_chart.rs
- iml-gui/crate/src/components/stratagem/mod.rs
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/dashboard.rs
- iml-gui/crate/src/page/fs_dashboard.rs
- iml-gui/crate/src/page/mod.rs
- iml-gui/crate/src/page/target_dashboard.rs
The charts should adjust their range based on the selected period.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1704)
> Update functionality of date picker on charts

- iml-services/iml-stats/src/main.rs
- Add `fs` tag to Target and BrwStats records
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1703)
> Add `fs` tag to Target and BrwStats records

- chroma_core/models/host.py
Restart agent for install as well as update packages
Fixes Issue whamcloud/iml-agent#140
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1714)
> Update profile should not deal with rpms

- chroma_core/models/host.py
Ensure we import the needed things to await a new session.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1718)
> Fix host await

- iml-gui/crate/src/extensions.rs
- iml-wire-types/src/lib.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1717)
> Remove unused imports

- iml-manager-cli/src/server.rs
Fixes #1664.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1724)
> Failed Preflight checks should print details

- iml-gui/entries/index.hbs
Fixes #1732.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1733)
> Add charset

- chroma_core/lib/detection.py
- tests/unit/services/job_scheduler/test_detection.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1745)
> Scan LVs in detect_scan to find failover peers

- iml-manager-cli/src/ostpool.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1758)
> Sort OSTs in OST pools display

- vagrant/Vagrantfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1764)
> Use 2.12.4 for client

- iml-gui/crate/src/status_section.rs
Closes #1728.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1756)
> Hide the Logs icon from the anonymous user

- vagrant/Vagrantfile
- vagrant/scripts/install_ldiskfs_no_iml.sh
- vagrant/scripts/install_zfs_no_iml.sh
Set ENV override of Lustre version
Set lustre version in single location
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1765)
> Make lustre version configurable and singular

- iml-gui/crate/src/page/filesystem.rs
- iml-gui/crate/src/page/filesystems.rs
Fixes #1766
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1767)
> Fix client count

- iml-agent/src/action_plugins/lamigo.rs
- iml-agent/src/action_plugins/lpurge.rs
- iml-agent/src/action_plugins/snapshots/iml_agent__action_plugins__lamigo__lamigo_tests__works.snap
- iml-agent/src/action_plugins/snapshots/iml_agent__action_plugins__lpurge__lpurge_conf_tests__works.snap
- iml-agent/systemd-units/settings.conf
This updates lamigo / lpurge code to match what shipped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1768)
> Fixup lamigo / lpurge code to mesh with HPv2

- Cargo.lock
- iml-agent/Cargo.toml
- iml-agent/src/action_plugins/action_plugin.rs
- iml-agent/src/action_plugins/high_availability/mod.rs
- iml-agent/src/lib.rs
- iml-systemd/Cargo.toml
- iml-systemd/src/lib.rs
- iml-systemd/src/systemd_error.rs
- iml-wire-types/src/lib.rs
Extract systemd into its own crate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1787)
> Extract systemd into its own crate

- vagrant/Vagrantfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1797)
> Fix iml-devel provision

- .github/workflows/iml-docker-ci.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1804)
> Cleanup after building to avoid No space errors

- Cargo.lock
- Cargo.toml
- iml-agent/Cargo.toml
- iml-systemd/Cargo.toml
Update systemd to 0.2.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1810)
> Update systemd to 0.2.0

- iml-gui/crate/src/page/filesystem.rs
- iml-gui/crate/src/page/filesystems.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1809)
> Change titles from Total to Available in GUI

- .gitignore
- iml-system-test-utils/src/ssh.rs
- vagrant/scripts/create_iml_diagnostics.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1829)
> - Fixup diagnostics

- iml-system-test-utils/src/ssh.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1845)
> Update sosreport permissions to be 777

- iml-manager-cli/src/server.rs
Add the ability to force-remove hosts via the IML CLI
[![asciicast](https://asciinema.org/a/Ezc0CWqYpSY6XqoNwrUUaqs5V.svg)](https://asciinema.org/a/Ezc0CWqYpSY6XqoNwrUUaqs5V)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1849)
> Add force-remove hosts to IML CLI

- iml-manager-cli/src/ostpool.rs
Fixes #1851.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1854)
> Fix OST pool CLI display

- Cargo.lock
- iml-system-test-utils/Cargo.toml
- iml-system-test-utils/src/lib.rs
- iml-system-test-utils/src/ssh.rs
- iml-system-test-utils/src/vagrant.rs
Switch to using tracing instead of println
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1857)
> Switch println to tracing::debug in test-utils

- chroma_core/models/stratagem.py
Fixes #1861.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1864)
> Fix volume lookup

- Cargo.lock
- iml-manager-env/src/lib.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1865)
> Transform env string to lowercase and trim

- Makefile
- vagrant/scripts/install_iml_local.sh
This will set the rpm dist to 10.UNIX_EPOCH
Use this build target in vargrant local build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1867)
> Add "make local" target to create dated releases

- .copr/Makefile
- iml-action-runner.service
- iml-action-runner.socket
- iml-agent-comms.service
- iml-api.service
- iml-corosync.service
- iml-device.service
- iml-gunicorn.service
- iml-http-agent.service
- iml-job-scheduler.service
- iml-lustre-audit.service
- iml-mailbox.service
- iml-manager.target
- iml-ntp.service
- iml-ostpool.service
- iml-plugin-runner.service
- iml-postoffice.service
- iml-power-control.service
- iml-rust-stats.service
- iml-syslog.service
- iml-system-test-utils/src/lib.rs
- iml-system-test-utils/src/ssh.rs
- iml-system-test-utils/src/vagrant.rs
- iml-warp-drive/systemd-units/iml-warp-drive.service
- python-iml-manager.spec
- rabbitmq-server-dropin.conf
Fixes #480.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1863)
> Try to use rabbitmq-server dropin

- iml-action-runner.service
- iml-agent-comms.service
- iml-agent/systemd-units/rust-iml-agent.service
- iml-api.service
- iml-corosync.service
- iml-device.service
- iml-gunicorn.service
- iml-http-agent.service
- iml-job-scheduler.service
- iml-lustre-audit.service
- iml-mailbox.service
- iml-ntp.service
- iml-ostpool.service
- iml-plugin-runner.service
- iml-postoffice.service
- iml-power-control.service
- iml-rust-stats.service
- iml-syslog.service
- settings.py
Adding an optional overrides file to the services will allow us to
override service environment variables easily.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1883)
> Add optional overrides file to services

- vagrant/scripts/install_iml_local.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1886)
> Fix missing gpgkey for local install

- Cargo.lock
- iml-agent/src/daemon_plugins/device.rs
- iml-agent/src/daemon_plugins/postoffice.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1888)
> Bump deps to latest

- iml-gui/crate/src/components/stratagem/mod.rs
- iml-gui/crate/src/components/stratagem/scan_stratagem_modal.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1898)
> Show command modal on manual stratagem scan

- Cargo.lock
- iml-services/iml-device/src/error.rs
- iml-services/iml-device/src/main.rs
Fixes #1902.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1914)
> Load devices at startup

- iml-manager-cli/src/display_utils.rs
Closes #1834.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1912)
> Do not print empty tables

- iml-system-docker-tests/Cargo.lock
- iml-system-docker-tests/src/lib.rs
- iml-system-docker-tests/tests/ldiskfs_test.rs
- iml-system-docker-tests/tests/stratagem_test.rs
- iml-system-rpm-tests/Cargo.lock
- iml-system-rpm-tests/src/lib.rs
- iml-system-rpm-tests/tests/stratagem_test.rs
- iml-system-test-utils/src/lib.rs
- iml-system-test-utils/src/ssh.rs
- iml-system-test-utils/src/vagrant.rs
- Implement ServerList trait
- Add hosts_to_ips function and map
- scp_up_parallel and scp_down_parallel
- sos reports for clients
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1900)
> Integration Test Host Updates

- iml-gui/crate/src/components/command_modal.rs
Precedes to the PR https://github.com/whamcloud/integrated-manager-for-lustre/pull/1899
Fixes #1878
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1882)
> Redundant load fix

- iml-gui/crate/src/components/command_modal.rs
Implements job cancellation
Includes the PR https://github.com/whamcloud/integrated-manager-for-lustre/pull/1882
Fixes #1876
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1899)
> Cancel jobs for command modal

- iml-orm/src/lib.rs
There is a common case where we need to compare a set of old items to a
set of new ones and figure out which ones need to be added / removed or changed.
Instead of writing this logic each time, we can create a trait that will
allow for comparisions and return the changes as `Additions`, `Updates`
and `Deletions`.
This is particularly useful for updating the db with input from daemon
plugins.
General use looks like:
```rust
let (add, update, remove) = new_items.get_changes(&old_items);
```
Returned items are all borrowed from new and old collections, so no
cloning is needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated- …
> Add trait for determining changes between old and new collections

- Pipfile
- Pipfile.lock
Integrate [pipenv](https://pypi.org/project/pipenv/)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1915)
> Integrate pipenv

- iml-docker.spec
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1938)
> Bump iml-docker to 0.3.0

- iml-action-client/src/lib.rs
- iml-agent/src/action_plugins/stratagem/action_purge.rs
- iml-agent/src/cli.rs
- iml-agent/src/daemon_plugins/stats.rs
- iml-manager-cli/src/display_utils.rs
- iml-manager-cli/src/server.rs
- iml-orm/src/hosts.rs
- iml-system-test-utils/src/iml.rs
- iml-system-test-utils/src/vagrant.rs
- iml-tracing/src/lib.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1943)
> Fix some clippy warnings

- chroma_core/models/stratagem.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1958)
> Fixup filesystem parameter in LustreClientMount

- grafana/dashboards/iml-metrics.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1966)
> Fix Bandwidth per server display

- iml-gui/crate/src/page/login.rs
- iml-gui/crate/src/page/partial/header.rs
- iml-wire-types/src/lib.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1967)
> Update branding matrix

- docker/power-control.dockerfile
- docker/python-service-base.dockerfile
- docker/rust-base.dockerfile
- iml-system-docker-tests/tests/stratagem_test.rs
- tests/framework/services/runner.sh.in
- vagrant/Vagrantfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1968)
> Fix stale EPEL metadata

- vagrant/Vagrantfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1970)
> Fixup IML 6.1 repo path

- chroma_core/migrations/0018_sfa_json_notify.py
add the sfacontroller table to listen / notify list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1973)
> Add missing sfa table

- grafana/dashboards/iml-metrics.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1976)
> grafana: Fix usage of "filesystem" where it should be "fs"

- iml-gui/crate/src/page/partial/footer.rs
Update footer branding
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1982)
> Update footer branding

- chroma_core/models/client_mount.py
Fix mount jobs such that they use the correct mount point
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1981)
> Fix mount jobs such that they use the correct mount point

- iml-agent/README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1993)
> Add iml-agent README

- docker/docker-compose.yml
closes #1991.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1992)
> Add resource bounds for influx and rabbitmq

- vagrant/README.md
- vagrant/Vagrantfile
Add lustre client setup to README
Fixes #2003
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2004)
> vagrant: Rename client lustre network target

- Cargo.lock
- iml-agent-comms/src/main.rs
- iml-agent-comms/src/messaging.rs
- iml-api/Cargo.toml
- iml-api/src/action.rs
- iml-api/src/error.rs
- iml-api/src/main.rs
- iml-job-scheduler-rpc/src/lib.rs
- iml-rabbit/Cargo.toml
- iml-rabbit/src/lib.rs
- iml-services/iml-action-runner/src/main.rs
- iml-services/iml-action-runner/src/receiver.rs
- iml-services/iml-action-runner/src/sender.rs
- iml-services/iml-action-runner/tests/action_runner_tests.rs
- iml-services/iml-device/src/error.rs
- iml-services/iml-device/src/main.rs
- iml-services/iml-ntp/src/main.rs
- iml-services/iml-ostpool/Cargo.toml
- iml-services/iml-ostpool/src/main.rs
- iml-services/iml-postoffice/src/main.rs
- iml-services/iml-service-queue/Cargo.toml
- iml-services/iml-service-queue/src/service_queue.rs
- iml-services/iml-stats/Cargo.toml
- iml-services/iml-stats/src/error.rs
- iml-services/iml-stats/src/main.rs
- iml-warp-drive/src/locks.rs
- iml-warp-drive/src/main.rs
Update lapin to the latest version and switch to using deadpool-lapin
for connection pooling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1972)
> Update lapin to latest

- chroma_core/models/client_mount.py
Fixes #2017.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2018)
> IML cannot detect filesystem when a client is mounted on a storage server

- iml-gui/crate/src/page/partial/footer.rs
Add copyright to footer for exascaler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2021)
> Add copyright to footer for exascaler.

- vagrant/scripts/create_ldiskfs_lvm_fs.sh
Fixes #2027 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2028)
> Ensure activation of LVs during creation

- iml-gui/crate/src/page/filesystem.rs
Fixes #2036.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2038)
> Fix fs detail overflow

- .copr/Makefile
- docker/power-control.dockerfile
- vagrant/Vagrantfile
Fixes #2048.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2049)
> Do not install postgres-devel

- iml-system-test-utils/src/iml.rs
Ref. c2dcd1e90c66f10bf7d1e65406b796bfab0d9ac1
Closes #2052.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2053)
> Fix "server add" invocation in tests

- vagrant/Vagrantfile
To see if it helps stability on boot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2055)
> Opt-out of NetworkManager for management network

- iml-system-docker-tests/src/lib.rs
- iml-system-docker-tests/tests/ldiskfs_test.rs
- iml-system-docker-tests/tests/stratagem_test.rs
- iml-system-docker-tests/tests/zfs_test.rs
- iml-system-rpm-tests/src/lib.rs
- iml-system-rpm-tests/tests/ldiskfs_test.rs
- iml-system-rpm-tests/tests/stratagem_test.rs
- iml-system-rpm-tests/tests/zfs_test.rs
- iml-system-test-utils/src/lib.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2061)
> Sync time across storage servers after reload

- chroma_core/lib/job.py
Add more information when encountering 'Error parsing json'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2066)
> Add more information when encountering 'Error parsing json'

- vagrant/README.md
- vagrant/Vagrantfile
- vagrant/scripts/mount_lustre_client.sh
Related #1832
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2078)
> vagrant: Add client mount provisioner

- iml-manager-env/src/lib.rs
Fix RUNNING_IN_DOCKER
Expand postgres connection string
Related to #1832 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2074)
> Update iml-manager-env for docker and postgres

- docker/docker-compose.yml
- iml-system-test-utils/src/lib.rs
- iml-system-test-utils/src/ssh.rs
- vagrant/Vagrantfile
- vagrant/scripts/enable_debug.sh
- vagrant/scripts/wait_for_ntp.sh
Update test debugging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2065)
> Update test debugging

- docker/grafana.dockerfile
This is needed due to https://github.com/docker-library/docker/issues/240
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2082)
> Specify python version

- iml-gui/crate/Cargo.lock
- iml-gui/crate/src/components/dropdown.rs
- iml-gui/crate/src/watch_state.rs
to make newest clippy happy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2081)
> Update mem::replace assignments

- Cargo.lock
- iml-agent/Cargo.toml
- iml-agent/src/daemon_plugins/snapshots/iml_agent__daemon_plugins__ntp__test__session_with_ntp_configured_by_iml.snap
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2083)
> Move snapshot location in agent testing

- .gitignore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2110)
> Add TAGS to gitignore

- Cargo.lock
- iml-agent/Cargo.toml
- iml-agent/src/action_plugins/action_plugin.rs
- iml-agent/src/action_plugins/lustre.rs
- iml-agent/src/action_plugins/lustre/snapshot.rs
- iml-agent/src/cli.rs
- iml-wire-types/Cargo.toml
- iml-wire-types/src/lib.rs
- iml-wire-types/src/snapshot.rs
[root@mds1 ~]# iml-agent snapshot create zfsmo foo -c 'hello world'
[root@mds1 ~]# lctl snapshot_list --fsname zfsmo
filesystem_name: zfsmo
snapshot_name: foo
modify_time: Mon Jul 27 19:55:18 2020
create_time: Mon Jul 27 19:55:18 2020
comment: hello world
snapshot_fsname: 6c80c077
status: not mount
filesystem_name: zfsmo
snapshot_name: test2
snapshot_fsname: 21fd4967
modify_time: Mon Jul 27 19:24:14 2020
create_time: Mon Jul 27 19:24:14 2020
status: not mount
[root@mds1 ~]# iml-agent snapshot destroy zfsmo test2
[root@mds1 ~]# lctl snapshot_list --fsname zfsmo
filesystem_name: zfsmo
snapshot_name: foo
modify_time: Mon Jul 27 19:55:18 2020
create_time: Mon Jul 27 19:55:18 2020
comment: hello world
snapshot_fsname: 6c80c077
status: not mount
Signed-off-by: Igor Pashev …
> Implement creating and destroying snapshots

- Makefile
Add all the packages that need to be built to the `all` target.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2120)
> Add all packages to all target

- Makefile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2087)
> Add "make check" to Makefile

- Cargo.lock
- iml-action-client/Cargo.toml
- iml-action-client/src/lib.rs
- iml-manager-env/src/lib.rs
Add invoke_rust_agent() to rust code.
Add cancel-able variant.
Related Issue #1832 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2122)
> action-client: Add invoke_rust_agent

- iml-system-docker-tests/tests/ldiskfs_test.rs
- iml-system-docker-tests/tests/zfs_test.rs
- iml-system-rpm-tests/tests/ldiskfs_test.rs
- iml-system-rpm-tests/tests/zfs_test.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2131)
> Fix cargo formatting of system tests

- Cargo.lock
- iml-rabbit/Cargo.toml
Work on #2072 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2115)
> Switch the iml-rabbit to rustls

- .github/workflows/iml-gui.yml
- iml-gui/crate/Cargo.lock
Due to https://github.com/rustwasm/wasm-bindgen/issues/2261.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2138)
> Fix firefox tests

- docker/iml-cli-proxy.sh
Related #1832
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2143)
> Quote arguments passed into docker iml

- vagrant/scripts/install_iml_docker_repouri.sh
Fixes #2015.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2151)
> Ensure upstream repo is used for docker

- iml-task-runner/src/main.rs
Ensure that active workers are released by running all tasks to
completion (try_join_all v.s. join_all).
In addition, add a check to skip a tick if the pool is overloaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2155)
> Ensure active_workers are released

- iml-task-runner/src/main.rs
- iml-wire-types/src/lib.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2164)
> Add a bunch of debug to the task-runner.

- Cargo.lock
- device-scanner/Cargo.lock
- device-scanner/device-scanner-daemon/Cargo.toml
- device-scanner/device-scanner-zedlets/Cargo.toml
- device-scanner/device-types/Cargo.toml
- device-scanner/device-types/src/devices.rs
- device-scanner/mount-emitter/Cargo.toml
- device-scanner/uevent-listener/Cargo.toml
- device-scanner/zed-enhancer/Cargo.toml
1. find_device_by_devpath
2. get_fs_uuid
3. find_device_by_id
4. get_id
5. children
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2163)
> Implement the Device enum:

- iml-services/iml-journal/src/main.rs
- sqlx-data.json
So query returns correct number of rows deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2168)
> Fix log deletion

- iml-agent/src/action_plugins/lustre/client.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2169)
> Fix missing space in fstab client mount

- vagrant/Vagrantfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2180)
> Forward Postgres port

- Cargo.lock
- chroma_core/management/commands/print-settings.py
- docker/docker-compose.yml
- iml-agent/Cargo.toml
- iml-agent/src/daemon_plugins/stats.rs
- iml-manager-env/src/lib.rs
- iml-services/iml-device/Cargo.toml
- iml-services/iml-device/src/error.rs
- iml-services/iml-device/src/lib.rs
- iml-services/iml-device/src/main.rs
- iml-services/iml-device/src/snapshots/iml_device__tests__deletions_only.snap
- iml-services/iml-device/src/snapshots/iml_device__tests__upserts_and_deletions.snap
- iml-services/iml-device/src/snapshots/iml_device__tests__upserts_only.snap
- iml-services/iml-stats/Cargo.toml
- iml-services/iml-stats/src/main.rs
- migrations/20200728203410_devices.sql
- sqlx-data.json
Add mgs fs to stats service
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2147)
> Add mgs fs to stats service

- .travis.yml
- iml-api/src/graphql.rs
- sqlx-data.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2188)
> Add a graphql endpoint to list targets

- .github/workflows/iml-gui.yml
- Cargo.lock
- docker/iml-gui.dockerfile
- iml-agent/src/action_plugins/lustre/client.rs
- iml-agent/src/action_plugins/stratagem/action_warning.rs
- iml-agent/src/crm_reader.rs
- iml-agent/src/daemon_plugins/corosync.rs
- iml-gui/crate/Cargo.lock
- iml-gui/crate/src/components/sfa_overview/mod.rs
- iml-mailbox/src/lib.rs
- iml-manager-cli/src/api.rs
- iml-rabbit/Cargo.toml
- iml-services/iml-action-runner/src/main.rs
- iml-services/iml-device/src/error.rs
- iml-services/iml-device/src/lib.rs
- iml-services/iml-journal/src/lib.rs
- iml-services/iml-ostpool/Cargo.toml
- iml-services/iml-ostpool/src/main.rs
- iml-services/iml-service-queue/src/service_queue.rs
- iml-services/iml-stats/src/main.rs
- iml-util/Cargo.toml
- iml-util/util.rs
- iml-wire-types/src/warp_drive.rs
Support Rust 1.46 and fix compile / clippy errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2193)
> Support Rust 1.46

- chroma_core/lib/detection.py
To be valid Python
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2190)
> Fix error handling syntax

- Cargo.lock
- device-scanner/Cargo.lock
- device-scanner/device-scanner-daemon/Cargo.toml
- device-scanner/device-types/Cargo.toml
- device-scanner/zed-enhancer/Cargo.toml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2195)
> Use non-github deps for libzfs crates

- iml-services/iml-journal/src/main.rs
- vagrant/Vagrantfile
Fixes #2187
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2214)
> Purge loop

- chroma-manager.conf.template
- iml-manager-cli/src/snapshots/iml_manager_cli__nginx__tests__replace_template_variables.snap
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2217)
> Bump nginx to support tlsv1.3

- iml-agent/README.md
- iml-agent/src/daemon_plugins/corosync.rs
- iml-agent/src/daemon_plugins/daemon_plugin.rs
- iml-agent/src/http_comms/session.rs
- iml-agent/src/poller.rs
Fixes #2219
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2221)
> Add deadline support for daemon plugins

- vagrant/Vagrantfile
- vagrant/local.cfg
Add
[clustershell](https://clustershell.readthedocs.io/en/latest/intro.html)
to manager / storage / client VMs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2227)
> Add clush to vagrant

- Cargo.lock
- iml-graphql-queries/src/lib.rs
- iml-graphql-queries/src/snapshot.rs
- iml-manager-cli/Cargo.toml
- iml-manager-cli/src/api_utils.rs
- iml-manager-cli/src/error.rs
- iml-manager-cli/src/snapshot.rs
- iml-manager-client/src/lib.rs
Complete commands for snapshot mount / unmount / create / destroy on the
manager cli.
This does not include snapshot intervals and retention.
[![asciicast](https://asciinema.org/a/GyjYD02SfGoZ72pX0JcI0Zwg7.svg)](https://asciinema.org/a/GyjYD02SfGoZ72pX0JcI0Zwg7)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2238)
> Finish snapshot management CLI

- iml-api/src/graphql.rs
- sqlx-data.json
Update the `targets` endpoint to work for the following three cases:
1. Without HA
1. With HA and no bans
1. With HA and some resources having bans
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2233)
> Target resources endpoint

- .github/workflows/iml-docker-ci.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2245)
> Hardcode docker compose version

- .copr/Makefile
- chroma-manager.conf.template
- chroma_core/management/commands/print-settings.py
- chroma_core/models/stratagem.py
- docker/docker-compose.yml
- docker/iml-timer/iml-timer.conf
- docker/nginx.dockerfile
- docker/setup-nginx
- iml-job-scheduler.service
- iml-manager-cli/src/nginx.rs
- iml-manager-cli/src/snapshots/iml_manager_cli__nginx__tests__replace_template_variables.snap
- iml-manager.target
- iml-timer.service
- python-iml-manager.spec
- rust-iml.spec
- settings.py
- vagrant/scripts/install_iml_local.sh
Add iml-timer service to rpm builds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2250)
> Add iml-timer service to rpm builds

- iml-gui/crate/src/page/snapshot/add_interval.rs
fix add_interval, which is broken on tip of master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2264)
> Fix add_interval.rs

- Cargo.lock
- iml-graphql-queries/src/snapshot.rs
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/snapshot/add_interval.rs
- iml-gui/crate/src/page/snapshot/list_interval.rs
- iml-gui/crate/src/page/snapshot/mod.rs
- iml-manager-cli/src/snapshot.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2266)
> Implement snapshot interval deletion support in GUI

- iml-services/iml-snapshot/src/main.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2277)
> Use transaction for table update

- iml-api/src/graphql.rs
- iml-graphql-queries/src/snapshot.rs
- iml-gui/crate/src/page/snapshot/create_retention.rs
- iml-gui/crate/src/page/snapshot/list_retention.rs
- iml-gui/crate/src/page/snapshot/mod.rs
- iml-manager-cli/src/display_utils.rs
- iml-manager-cli/src/snapshot.rs
- iml-wire-types/src/snapshot.rs
- migrations/20200831174542_snapshot.sql
- sqlx-data.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2279)
> Implement GUI for snapshot retention policies

- iml-manager-cli/src/display_utils.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2280)
> Use three dashes instead of two

- Cargo.lock
- iml-api/src/graphql.rs
- iml-graphql-queries/src/snapshot.rs
- iml-gui/crate/src/page/snapshot/create_retention.rs
- iml-manager-cli/src/snapshot.rs
- iml-services/iml-snapshot/Cargo.toml
- iml-services/iml-snapshot/src/client_monitor.rs
- iml-services/iml-snapshot/src/lib.rs
- iml-services/iml-snapshot/src/main.rs
- iml-services/iml-snapshot/src/retention.rs
- sqlx-data.json
Analyze the space left on each filesystem and compare against the configured retentions. If the threshold has been exceeded, begin removing snapshots as necessary and re-analyze until the amount of free space does not exceed the threshold.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2259)
> Retention analysis

- chroma_core/management/commands/print-settings.py
- docker/docker-compose.yml
- iml-api/src/main.rs
- iml-gui/crate/src/lib.rs
- iml-gui/crate/src/page/partial/header.rs
- iml-manager-env/src/lib.rs
- iml-wire-types/src/lib.rs
- settings.py
Implemenet feature flag support for snapshots
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2278)
> Implement feature flag support for snapshots

- iml-agent/src/action_plugins/stratagem/action_filesync.rs
- iml-agent/src/cli.rs
- iml-manager-cli/src/stratagem.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2289)
> 2288: remove "pull" as an option for filesync

- iml-manager-cli/src/main.rs
- rust-iml.spec
Closes #2283 
Not sure if it's worth or possible to hide "hidden" options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2285)
> Add shell completions for CLI

- chroma_core/management/commands/print-settings.py
- docker/docker-compose.yml
- iml-manager-env/src/lib.rs
- settings.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2303)
> Fix enable snapshot race

- Cargo.lock
- docker/docker-compose.yml
- iml-agent/Cargo.toml
- iml-manager-cli/Cargo.toml
- iml-services/iml-journal/Cargo.toml
- wbem-client/Cargo.toml
- wbem-client/src/cim_xml.rs
- wbem-client/src/snapshots/wbem_client__cim_xml__resp__tests__instance.snap
- wbem-client/src/snapshots/wbem_client__cim_xml__resp__tests__instance_list.snap
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2311)
> Account for empty ARRAY.VALUE

- Cargo.lock
- iml-agent/Cargo.toml
- iml-services/iml-stats/Cargo.toml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2313)
> Bump lustre-collector

- iml-manager-cli/src/snapshot.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2324)
> Change reserve_value to doc comment

- iml-agent/src/cli.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2329)
> Print better error messages for filesync/cloudsync from iml-agent

- iml-agent/src/action_plugins/stratagem/action_cloudsync.rs
- iml-agent/src/action_plugins/stratagem/action_filesync.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2326)
> filesync should only return fids that errored

- docker/python-service-base.dockerfile
- tests/framework/services/runner.sh.in
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2333)
> Add pbr to requirements

- chroma-manager.conf.template
- iml-api/src/graphql.rs
- iml-manager-cli/src/snapshots/iml_manager_cli__nginx__tests__replace_template_variables.snap
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2316)
> Add graphql schema listing support

- chroma_core/models/filesystem.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2339)
> Fix quoting for graphql query from FS

- device-scanner/zed-enhancer/systemd-units/zed-enhancer.service
To pick up installed ZEDLETs
Closes #2201.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2341)
> Reconfigure zfs-zed before start zed-enhancer

- iml-gui/crate/Cargo.lock
- iml-gui/crate/src/page/stratagem/mod.rs
- iml-gui/crate/src/page/stratagem/report.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2345)
> Fixup changed structure path

- iml-agent/src/action_plugins/action_plugin.rs
- iml-agent/src/action_plugins/lustre/client.rs
Blocks #1464 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2352)
> Add add/remove_fstab_entry agent actions

- iml-task-runner/src/main.rs
Move most of messages to tracing level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2346)
> task-runner: Decrease verbosity of debug level

- chroma_core/models/client_mount.py
Due to the use of reverse_dependencies, existing clients want to be unmounted
when adding a new server. This should not need to happen, but in
particular it should not happen when there is no filesystem detected.
Stop the reverse dependencies from propagating when there is no fs
detected yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2348)
> Stop client changes when adding / removing servers

- Cargo.lock
- iml-api/src/graphql/mod.rs
- iml-postgres/src/lib.rs
- iml-services/iml-corosync/src/lib.rs
- iml-services/iml-corosync/src/main.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2354)
> Extract a few common postgres fns

- chroma_core/models/stratagem.py
Fix bug when taking a lock in the generic file scan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2357)
> Fix Bug in generic file scan

- iml-agent/src/cli.rs
Ref. ad6daad5d834676b2e4068cacb40338e52eafba7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2368)
> Allow different CLI names for Agent CLI

- iml-agent/src/action_plugins/high_availability/mod.rs
- iml-agent/src/high_availability.rs
- iml-agent/src/snapshots/iml_agent__high_availability__tests__read_es.snap
Account for index in wait_resource and remove cruft code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2370)
> agent: Return cloned resources with index from crm mon output

- Cargo.lock
- iml-api/src/graphql/mod.rs
- iml-graphql-queries/src/lib.rs
- iml-graphql-queries/src/server_profile.rs
- iml-manager-cli/Cargo.toml
- iml-manager-cli/src/display_utils.rs
- iml-manager-cli/src/error.rs
- iml-manager-cli/src/profile.rs
- iml-wire-types/src/lib.rs
- sqlx-data.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2376)
> Switch server profiles CLI to GraphQL

- iml-api/src/graphql/mod.rs
- sqlx-data.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2394)
> Update resource ban query to filter nulls

- iml-api/src/graphql/mod.rs
- iml-graphql-queries/src/client_mount.rs
- iml-graphql-queries/src/lib.rs
- iml-gui/crate/src/page/filesystem.rs
- iml-manager-cli/src/filesystem.rs
- sqlx-data.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2392)
> Add a graphql endpoint to construct the clientmount command.

- iml-manager-cli/src/main.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2387)
> Search for config in different places

- iml-agent/src/cli.rs
- iml-agent/src/daemon_plugins/snapshot.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2405)
> agent: Fix clippy warnings

- iml-influx/src/lib.rs
- iml-manager-env/src/lib.rs
- iml-rabbit/src/lib.rs
- iml-request-retry/examples/demo-server-client.rs
- iml-request-retry/src/policy.rs
- iml-systemd/src/lib.rs
- iml-util/util.rs
Commit changes generated by:
`cargo +nightly clippy -Z unstable-options --fix`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2411)
> Commit clippy --fix changes

- Cargo.lock
- wbem-client/Cargo.toml
- wbem-client/src/lib.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2415)
> Add some extra tracing to the wbem-client

- iml-services/iml-device/src/main.rs
- iml-warp-drive/src/listen.rs
- iml-wire-types/src/warp_drive.rs
Filter identical record changes from warp-drive on update to not spam
the browser.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2418)
> Filter identical record changes from warp-drive

- README.md
- scripts/pre-commit
Formatting check supports both rust and python code.
Doesn't add the weight of doing a cargo build on a system
that doesn't support it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2417)
> Add Basic formatting pre-commit check

- iml-agent/src/http_comms/session.rs
Skip sending updates for all daemon plugins is the previous update is
equal to the current one within a session.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2419)
> Skip identical daemon plugin updates

- .github/workflows/rust-ci.yml
- Cargo.lock
- README.md
- iml-postgres/Cargo.toml
- iml-services/iml-journal/Cargo.toml
- iml-services/iml-journal/src/main.rs
- iml-wire-types/Cargo.toml
- tests/framework/services/runner.sh.in
rebase workspace support onto latest sqlx master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2422)
> Bump sqlx to latest

- iml-gui/crate/src/page/partial/header.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2423)
> Use cursor pointer on the Management menu

- iml-agent/src/cli.rs
- iml-api/src/graphql/filesystem.rs
- iml-api/src/graphql/mod.rs
- iml-api/src/graphql/stratagem.rs
- iml-api/src/graphql/task.rs
- iml-manager-cli/src/filesystem.rs
- iml-manager-cli/src/lib.rs
- iml-services/iml-device/src/main.rs
- iml-services/iml-journal/src/lib.rs
- iml-services/iml-snapshot/src/main.rs
- iml-services/iml-snapshot/src/retention.rs
- iml-system-test-utils/src/lib.rs
- iml-system-test-utils/src/snapshots.rs
Fix more clippy issues found by `cargo +nightly clippy -Z
unstable-options --fix`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2429)
> Fix more clippy issues

- iml-api/src/graphql/filesystem.rs
- iml-services/iml-device/src/lib.rs
- iml-services/iml-device/src/main.rs
- migrations/20201209221117_update_target_unique.sql
- sqlx-data.json
Fixes #2428.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2430)
> Support combined MGS / MDT

- iml-manager-cli/src/stratagem.rs
Cloudsync and filesync should support the same command lines
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2447)
> Fix for issue 2446
