docs/index.md
Fixes #8.
Create a docs dir for usage with github pages.
Signed-off-by: Joe Grund <grundjoseph@gmail.com>
=> Create docs dir for github pages

chroma-manager/tests/utils/json_cfg2sh.py
Fixes #10 
When enumerating ALL_NODES, json_cfg2sh.py is not including worker
nodes in that list.
Change-Id: I6e75356f2abbd344d8fa3cf877245fdb6fff66b0
=> json_cfg2sh.py does not include worker nodes in ALL_NODES

scripts/update_chroma-externals.py
This little hack works consistently on the new jenkins to fix up
an empty chroma-externals dir.  I would not work on our existing
(soon to be old) jenkins since builders are on separate nodes
there.
=> Hack to fix up chroma-externals when it's empty

chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main, chroma-manager/tests/framework/integration/existing_filesystem_configuration/run_tests, chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/jenkins_steps/main, chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/run_tests, chroma-manager/tests/framework/utils/cleanup.sh
There is an opportunity to DRY out the code that handles the end-of-test
processing and abort handling in the SSI and EFS tests.
This patch does that by moving some common code to a single function as
well as adding abort handling to the EFS test.
=> HYD-7331 DRY out end of test and abort handling

chroma-manager/tests/framework/unit/jenkins_steps/main
Each invocation requires it's own database, so leverage the serial
identifier of the Jenkins workspace to point MFL at it's own data-
base.
=> Support multiple parallel unit-tests runs

chroma-manager/tests/integration/core/api_testcase_with_test_reset.py, chroma-manager/tests/integration/core/failover_testcase_mixin.py, chroma-manager/tests/integration/core/remote_operations.py, chroma-manager/tests/integration/core/utility_testcase.py
Chris Gearing has tended to not remove fetchhelps (through laziness) when
landing code. This means I get messages for failures that are really just
test failures and not related to the message. He has added them to a junk
mail filter!
But when this happens tests take additional time.
To fix this double whammy burger I've removed the fetch helps for
chris.gearing@intel.com and left just the one for HYD-4050 which goes to
Brian.
- Remove 5 fetchelp usages
- Change usage documentation to include names of current developers
Change-Id: I600ce5cde71dd27fa2c007d7266a3df3ceb988bd
=> HYD-6908 Remove unnecessary fetchhelp's

chroma-manager/tests/integration/core/remote_operations.py
Every now and then an ssh operation in one of our tests throws an
exception such as:
Traceback (most recent call last):
File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_lnet_functionality.py", line 15, in setUp
super(TestLNetFunctionality, self).setUp()
File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 137, in setUp
self.reset_cluster()
File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 626, in reset_cluster
self.remote_operations.unmount_clients()
File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 921, in unmount_clients
'mount')
File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 375, in _ssh_address …
=> SSHException: Error reading SSH protocol banner debug

chroma-manager/chroma_core/models/corosync2.py, chroma-manager/tests/integration/core/api_testcase_with_test_reset.py, chroma-manager/tests/unit/chroma_core/jobs/test_corosync2_jobs.py, cluster-sim/cluster_sim/fake_device_plugins.py, cluster-sim/cluster_sim/fake_server.py, cluster-sim/cluster_sim/simulator.py, cluster-sim/cluster_sim/utils.py
Simulator tests failing due to https://jira.hpdd.intel.com/browse/HYD-7340
In order to remove the race condition
- clear the simulator server data at the beginning of each test
- don't return information from pacemaker/corosync when packages not installed
Change-Id: Iece96863aa1e2111cf355ac048c41a2255ef0529
=> Fix bugs in simulator corosync configuration due to race conditions

chroma-manager/Makefile, chroma-manager/tests/framework/utils/make_develop.sh, chroma-manager/ui-modules/package.json, scripts/jenkins_build
Now that we are a single branch, and solidly focused on always using the
latest nodejs, remove the installation on the builder prior to build.
remove all refs to artifactory.
Signed-off-by: Joe Grund <grundjoseph@gmail.com>
=> Remove nodejs installation on the builder

chroma-manager/tests/framework/utils/cluster_setup.sh
Since caching metadata can result in coherency problems when
the metadata files are updated and the repomd.xml file is cached
and stale.
=> Instruct any caching proxies to only cache packages

chroma-agent/chroma_agent/log.py, chroma-agent/tests/chroma_common/lib/test_sandbox_exception.py, chroma-common/lib/exception_sandbox.py
The ExceptionSandBox class will log errors when debug is off and suppress the
exception from being propagated. It is thought that this may be unnecessary and
that suppressing exceptions and printing summary information regarding sandboxed
exceptions to debug log (in both debug and normal modes) is a more appropriate
approach.
- Remove ExceptionSandBox class, move logging and exception catching
functionality in to exceptionSandBox function
- Log a summarised traceback as debug when exception is thrown in sandbox
- Remove references to ExceptionSandBox
- Amend tests as necessary
Change-Id: I05d4216c72dd6cb1895ac30aa329d230db8aff63
=> HYD-7237 Reduce complexity of ExceptionSandbox

chroma-manager/tests/integration/core/chroma_integration_testcase.py, chroma-manager/tests/integration/core/failover_testcase_mixin.py
Make it standard practice to verify if filesystem has mounted targets on
expected hosts.
- verify that the fs has targets mounted on the primary hosts that we
set explicitly in set_volume_mounts during filesystem creation
=> HYD-7339 Verify targets mounted on expected hosts during create_filesystem_standard

chroma-manager/tests/utils/remote_firewall_control.py
Firewall seems to be occasionally disabled on manager host during
SSI runs. this causes intermittent test failures.
- Add command address and result to Exception output to clarify
=> Firewall intermittently disabled/inactive during SSI runs

chroma-manager/tests/framework/utils/selective_auto_pass.sh
It would be nice and resource friendly to be able to limit the tests we
run when trying to diagnose a problem.
Allow two commit message pragmas "Run-tests" and "Skip-tests" to specify
a list of tests to either run or skip.
- enhance check_for_autopass() to look for a commit pragma and limit
tests being run based on that
- pass the tests that were skipped
- reorder passes so that distribution support is before gui-bump
=> HYD-6355 For testing purposes limit tests that are run

chroma-agent/chroma_agent/action_plugins/manage_targets.py, chroma-agent/chroma_agent/device_plugins/corosync.py
We should be able to rely on finding any exceptions in the chroma agent
logs as being indications of defects.  We have even periodically
discussed having the test framework fail tests if exceptions are found
in the agent log(s).
This unfortunately is not quite true (yet).
There are expected exceptions when the agent scan starts before
Pacemaker has been installed.  Rather than letting these pollute the
logs, we should catch them.
=> HYD-7213 Exceptions found in agent logs for known conditions

chroma-manager/chroma_api/authentication.py, chroma-manager/chroma_core/lib/service_config.py
As we move towards a distributed model, we need a way to authenticate against the api besides username / password combo.
We currently proxy the session forward when needed, but this is sub-optimal.
This change is sub-optimal as well IMO (we should be using some sort of API gateway for auth and not concern ourselves with it in this service), but it enables further changes.
=> Add support for API key auth

chroma-manager/chroma_core/migrations/0032_health_status_procedure.py
We ask for status and count of alerts to represent
system health.
This call currently involves
1. Selecting every active row with a certain severity.
2. Reducing the rows into a count + maximum severity.
Instead of this, we can use a stored procedure. This will
centralize the information for any consumer, and allows us
to get the status with a simple call: `select * from health_status()`.
Then, we can couple this call with postgres listen + notify.
This will end up providing a reactive event flow, all in the postgres
level.
That means that a consumer can subscribe to changes from the
DB. This approach should scale as well.
=> Add Health Status stored procedure

chroma-manager/chroma_core/migrations/0033_api_key_procedure.py
#94 added support for API key auth. However to retrieve the key and username, each service would need to construct a custom query.
Instead of that, add a stored procedure where anyone who has db credentials can issue a call.
There is still somewhat of a barrier in that a user needs db credentials, but this lowers the bar until we have a shared settings
store over a key value structure.
=> Create Stored Procedure for retrieving the API un/key combo

chroma-manager/tests/framework/integration/installation_and_upgrade/cluster_setup, chroma-manager/tests/framework/integration/installation_and_upgrade/jenkins_steps/main, chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests
Fix the upgrade tests.
Since the version we are upgrading from didn't want EPEL enabled,
disable it before trying to install it.
=> Fix upgrade tests

Makefile, chroma-agent/Target, chroma-agent/chroma_agent/action_plugins/manage_node.py, chroma-agent/chroma_agent/agent_daemon.py, chroma-agent/chroma_agent/lib/agent_teardown_functions.py, chroma-agent/tests/actions_plugins/test_manage_target.py, chroma-agent/tests/chroma_common/blockdevices/test_blockdevice_zfs.py, chroma-agent/tests/chroma_common/blockdevices/test_exported_zfs_device.py, chroma-agent/tests/chroma_common/filesystems/test_filesystem_zfs.py, chroma-agent/tests/device_plugins/linux/test_zfs.py, chroma-common/blockdevices/blockdevice.py, chroma-common/blockdevices/blockdevice_zfs.py, chroma-common/lib/util.py, chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/shared_storage_configuration_cluster_cfg.json, chroma-manager/tests/integration/shared_storage_configuration/test_filesystem_same_name.py
Thread locks protect different threads from listing, importing or exporting the same zpool that another thread is using. This mechanism is implemented in chroma-common/blockdevices/blockdevice_zfs.py file ZfsDevice class. This is effective in protecting zpool transitions between threads running code within the same process.
Zpools can be imported and exported from other processes (which don't have knowledge of thread level locks) and interrupt the import-export sequences of IML. In order to avoid these race conditions,
global/file locks should be implemented which provide protection from these interruptions effective between different processes, not just between threads in the same process.
Implementing these global locks within the IML code will not prevent other non-IML processes from …
=> Use global locks to protect against zpool import-export sequence interruption

chroma-manager/tests/integration/shared_storage_configuration/test_filesystem_dne.py
Temporarily Disable `test_mdt0_undeletable` until LU-9725
is fixed upstream. 
I have added #128 to track re-enabling this test once upstream bug is fixed and verfied.
=> Temporarily disable test_mdt0_undeletable

chroma-manager/tests/integration/shared_storage_configuration/test_filesystem_dne.py
Temporarily Disable ``test_create_dne_filesystem until LU-9725 is fixed
upstream.
I have added to #128 to track re-enabling this test once upstream bug is
fixed and verfied.
=> Temporarily disable test_create_dne_filesystem

chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py
Temporarily Disable `test_create_filesystem_with_failover_oss` until
LU-9725 is fixed upstream.
I have added to #128 to track re-enabling this test once upstream bug
is fixed and verfied.
=> Temporarily disable test_create_filesystem_with_failover_oss

Makefile, chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/run_tests
Particularly in the case of running "make ssi_tests", if the caller
has $NOSE_ARGS set, pass those through to SSI's run_tests.
Such as:
$ NOSE_ARGS="-x" make ssi_tests
=> Pass NOSE_ARGS through from caller

chroma-manager/tests/integration/core/remote_operations.py
If the rc != expected_return_code, it would be useful to know what it was.
=> Add the rc to the assertion in _ssh_address

chroma-manager/chroma-manager.spec
Now that we have a rpm for detecting supervisor status over unix domain socket, add it to the manager as a dependency.
=> Add supervisor-status dep on the manager.

chroma-manager/tests/framework/utils/defaults.sh
Because this will always alert outside of Jenkins.
=> Only alert about TEI-3576 when running in Jenkins

chroma-dependencies/include/Makefile.jenkins_meta, chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main, chroma-manager/tests/framework/integration/installation_and_upgrade/jenkins_steps/main, chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests, chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/jenkins_steps/main, chroma-manager/tests/framework/integration/upgrade_os/jenkins_steps/main, chroma-manager/tests/framework/services/jenkins_steps/main, chroma-manager/tests/framework/test_reporting/aggregate_test_results.py, chroma-manager/tests/framework/test_reporting/jenkins_steps/main, chroma-manager/tests/framework/utils/defaults.sh
Remove all instances of jenkins auth.
We will not need it going forward.
=> Remove Jenkins auth

chroma-manager/tests/feature/cli/features/steps/standard_cli.py
behave tests intermittently fail due to a strange Syntax error within error handling code
fix is to change the print statement to a print function
=> print statement syntax fails intermittently in behave tests

chroma-manager/tests/integration/shared_storage_configuration/test_long_polling.py
Timeout is exceeded but we can see the command complaints shortly after
example: http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/777/arch=x86_64,distro=el7//consoleFull
this is an intermittent failure in SSI tests on 4.0.0
=> test_long_polling_locks fails due to exceeded timeout

chroma-manager/chroma_api/storage_resource.py
The realtime service relies on value equality of JSON objects to only emit changes downstream.
dehydration of parent classes was non-deterministic (order changed between requests).
This caused the realtime service to emit changes continually as subsequent JSON objects were not stable.
This patch makes the return call in the API consistent.
=> Make sure parent classes are sorted in a stable way.

Makefile
Change _vagrant destroy_ to be called with _force flag_ from within the _destroy_cluster_ base IML Makefile . Otherwise the user has to manually confirm destroying each VM and this is inconvenient in terms of the automation that make can provide.
This is a component of the work described in #201
=> vagrant destroy should be called with force within destroy_cluster Makefile target

chroma-agent/tests/device_plugins/test_action_runner.py
It looks like we need to add an extra
argument to mock_run to get our
unit tests passing again.
=> Add extra argument to mock

chroma-manager/tests/framework/integration/existing_filesystem_configuration/existing_filesystem_configuration_cluster_cfg.json, chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main, chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/shared_storage_configuration_cluster_cfg.json, chroma-manager/tests/integration/core/api_testcase_with_test_reset.py, chroma-manager/tests/integration/shared_storage_configuration/test_targets.py, chroma-manager/tests/simulator.json
_linux_ is the name of an O/S kernel.  _ldiskfs_ is the name of a filesystem type.  _ldiskfs_ is analogous to _zfs_.  _linux_ is not. 
Replace the use of _linux_ where _ldiskfs_ is really what is intended.
=> Rename "linux" to "ldiskfs"

chroma-manager/tests/integration/core/remote_operations.py, chroma-manager/tests/integration/core/utility_testcase.py, chroma-manager/tests/integration/existing_filesystem_configuration/utils/create_lustre_filesystem.py
Fixes #232
If we execute a remote command that expects input it will block
forever waiting for that input.
Make sure that remote commands don't wait for input by closing
stdin.  This will have the effect that any command reading stdin
(of which there shouldn't be any) get an EBADF which should fail
the command obviously enough that the developer can see why it
was looking for input and rectify that.
This of course does not apply when to _ssh_address() when it has
buffer set, so be conditional on that.
- update _ssh_address() and remote_command() to prefix command
with "exec 0<&-" to close that shell's stdin, effectively
causing any command that wants input to get a EBADF
- only if buffer == None for _ssh_address()
- experimentation yields that closing stdin can only be
done in the remote …
=> Remote commands should not expect input

chroma-bundles/Makefile, chroma-bundles/chroma_support.repo, chroma-bundles/include/find_deps.py, chroma-bundles/install, chroma-manager/MANIFEST.in, chroma-manager/Makefile, chroma-manager/chroma-manager.spec, chroma-manager/chroma_agent_comms/views.py, chroma-manager/setup.py, chroma-manager/storage_server.repo, cluster-sim/Makefile
This is done by first setting repo locations in chroma_support.repo
in the installation directory.  This file will NOT override an
existing /etc/yum.repos.d/chroma_support.repo file however.
Then once the manager is installed, storage server repo overrides
can be made to /usr/share/chroma-manager/storage_server.repo.  This
file is marked as a configuration file in the RPM so upgrades won't
override changes to this file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/277)
=> Allow the user to override repo locations

chroma-manager/storage_server.repo, chroma-manager/tests/framework/utils/defaults.sh
Now that we are nearing RC, and b2.10.1 is in RC1, we should pin IML against the b2.10.1RC.
This will ensure we are testing the code planned to be shipped, and are not having shifting updates of Lustre.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/286)
=> Pin repos to b2.10.1

chroma-manager/tests/integration/core/remote_operations.py
```run_iml_diagnostics``` is currently calling `iml-diagnostics` with the wrong flag, it should be a `-` instead of a `_`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/318)
=> Fix param for --all-logs in run_iml_diagnostics

chroma-agent/chroma-agent.spec, chroma-agent/chroma_agent/device_plugins/linux_components/block_devices.py, chroma-agent/chroma_agent/device_plugins/linux_components/mdraid.py, chroma-agent/chroma_agent/device_plugins/linux_components/zfs.py, chroma-agent/chroma_agent/lib/normalize_device_path.py, chroma-agent/tests/device_plugins/linux/test_linux.py, chroma-agent/tests/device_plugins/linux/test_zfs.py
This patch integrates the device-scanner repo into the iml-agent. It is a replacement for the `BlockDevices` class and imperative lookup of devices.
Instead, a device map is held in a daemon, and updated whenever a udev event is received over a unix domain socket.
As a first pass, the BlockDevices class is updated to query state from the scanner so it is still polling (but quicker). The ultimate goal will be to move from a poll model to a push model which will necessitate further changes downstream.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/306)
=> Integrate device-scanner in IML agent

chroma-manager/storage_server.repo, chroma-manager/tests/framework/utils/defaults.sh
Lustre 2.10.1 is officially released. Switch from using
review builds to the official download.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/313)
=> Pin to Lustre 2.10.1 Release

chroma-manager/tests/integration/core/clear_ha_el7.sh
Due to an overly-liberal RE, a trailing space was allowed
to be included in the interface name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/320)
=> Don't allow spaces in the interface name

chroma-agent/chroma_agent/action_plugins/manage_targets.py
'no such pool available' failure occurs occasionally when trying to import zpool that should exist. Retry import once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/326)
=> retry on 'no such pool' import error

chroma-agent/chroma_agent/action_plugins/device_plugin.py, chroma-agent/chroma_agent/action_plugins/manage_node.py, chroma-agent/chroma_agent/action_plugins/manage_targets.py, chroma-agent/tests/actions_plugins/test_manage_target.py, chroma-agent/tests/actions_plugins/test_plugins.py, chroma-agent/tests/test_manage_node.py, chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice_lvm.py
zpool force import should only be used when necessary. only use the force flag during a pacemaker operation after the initial import (without force) fails and returns a message indicating that the pool can be imported using the '-f' flag. This can occur when a host is fenced while having a pool imported and another host attempts to import that same pool.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/325)
=> only use force when prompted in the failure message

chroma-agent/chroma_agent/fence_chroma.py
Fixes #345
Due to an error with pcs parsing the output of a fence-agent's
metadata when that metadata contains non-ascii characters, switch
the non-ascii form of "registered trademark" to (R).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/348)
=> Replace non-ascii symbol with (R)

chroma-agent/chroma_agent/fence_chroma.py
Fixes #346
A duplicate port specification got added to the fence agent
unnecessarily.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/350)
=> Remove duplicate port argument from fence agent

chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py
_test_managed_filesystem_with_failover.py:TestManagedFilesystemWithFailover.test_managed_filesystem_with_failover_mgs_ disabled/skipped in ssi test suite in order to get #244 landed. Investigate this failure and find a fix so it can be re-enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/298)
=> Re-enable (and fix) test_managed_filesystem_with_failover_mgs in ssi test suite

chroma-manager/tests/integration/shared_storage_configuration/test_power_control.py
Skips test test_toggled_outlet_does_not_trigger_fencing_update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/341)
=> Skip test until #315 is fixed

chroma-manager/tests/integration/shared_storage_configuration/test_corosync.py
_test_corosync.py:TestCorosync.test_corosync_reverse_dependencies_ disabled/skipped in sim test suite in order to get #244 landed. Investigate this failure and find a fix so it can be re-enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/301)
=> Re-enable (and fix) test_corosync_reverse_dependencies in sim test suite

chroma-manager/tests/integration/shared_storage_configuration/test_filesystem_same_name.py
`test_same_name` is doing import / destroy / export on all servers at once.
It should only happen on the first server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/356)
=> Fixup test same name

chroma-agent/chroma_agent/device_plugins/linux_components/zfs.py, chroma-agent/tests/data/zfs_example_data.py, chroma-agent/tests/device_plugins/linux/test_zfs.py
It appears that there is a bug in `zpool import / status` parsing when a scrub has been performed (or any value matching `(\w+):[^/]`).
a completed scrub will contain a timestamp which will match the regex:
```
re.split('(\w+):[^/]', 'scrub repaired 0B in 0h0m with 0 errors on Sun Oct 22 15:25:35 2017')
Out[2]:
['scrub repaired 0B in 0h0m with 0 errors on Sun Oct 22 ',
'15',
'',
'5',
'5 2017']
```
Ideally we could use a parser-combinator for this output (which would be sensitive to point of match ), but for now we should avoid splitting on values with ':'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/358)
=> zpool parsing bug when scrub in status

chroma-bundles/install
Clearly an extra '1' digit was inserted.  Remove it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/300)
=> Change exit value from install to -1 from -11

chroma-bundles/install, chroma-manager/chroma-manager.spec
Fixes #360
There was a design committed to retire old bundles when upgrades
were done but this doesn't really work as designed since it
leaves agents pointing at repos that don't exist immediately
after the manager upgrade is completed.
Instead, empty the retired bundles but make them valid (but
empty) repos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/365)
=> Don't merge old bundles with new

chroma-manager/chroma_core/models/log.py, chroma-manager/tests/unit/chroma_api/test_log.py
- #274
- Changed the log sorting to be based off of "datetime" instead of "id"
- Fixed tests: Reverse sorted lists to satisfy the assert compare list equal test.
- One list is defined by the test, the 2nd list is returned from the api.
Signed-off-by: Peter Robinson <peter.timothy.robinson@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/366)
=> Fix log sorting

chroma-manager/storage_server.repo
Instead of using a single server specific URL for the
GPG key location, use a redirecting URL for resiliency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/376)
=> Replace single-server URL with redirecting URL

Makefile, chroma-agent/chroma_agent/action_plugins/agent_updates.py, chroma-manager/tests/framework/integration/installation_and_upgrade/cluster_setup, chroma-manager/tests/framework/integration/installation_and_upgrade/jenkins_steps/main, chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests, chroma-manager/tests/framework/integration/utils/install_client.sh, chroma-manager/tests/framework/integration/utils/node_lib.sh, chroma-manager/tests/framework/utils/selective_auto_pass.sh, chroma-manager/tests/integration/core/api_testcase_with_test_reset.py, chroma-manager/tests/integration/installation_and_upgrade/test_create_filesystem.py, chroma-manager/tests/integration/installation_and_upgrade/test_update_with_yum.py, chroma-manager/tests/integration/shared_storage_configuration/test_updates.py, chroma-manager/tests/utils/install-3.x.exp
Reverts commit 2c7ff95c3e500c074d5e72a621f9b6ea6868e7a8 to
enable upgrade testing again.
Remove two failing tests:
- test_data_consistancy.py
- due to #359
- test_update_with_yum.py:TestYumUpdate.test_no_retired_repos
- retiring repos/bundles can't really work the way it was
designed/written due to removing repos that would still be
configured on the storage servers
- this likely won't get fixed before we just remove bundles/
repos altogether
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/370)
=> Upgrade using the 3.x -> 4.0 manual upgrade

chroma-manager/chroma-manager.conf.template, chroma-manager/chroma-manager.spec
In nginx release 1.11.6 the variable $ssl_client_s_dn
had it's value format updated to meet an RFC spec.
https://github.com/nginx/nginx/commit/71c93a
Adjust our parsing to account for the new format and
require version >= 1.11.6 nginx.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/391)
=> Nginx 1.12 fix

Makefile, Vagrantfile, chroma-manager/tests/framework/utils/provisioner_interface/provision_cluster
So that testing in Vagrant aligns better with testing in CI.
Also, make sure the Vagrant box is at the required version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/389)
=> Move resetting of Vagrant cluster to provisioning

chroma-manager/tests/framework/integration/existing_filesystem_configuration/cluster_setup, chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup
If available.
This allows a local storage server repo to override the default storage repo
in EFS and SSI tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/394)
=> Use a local storage-server repo definition

Vagrantfile
Let's see all of the gory details of booting up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/408)
=> Boot CentOS nodes in Vagrant verbosely

Makefile, Vagrantfile, chroma-manager/tests/framework/integration/installation_and_upgrade/cluster_setup, chroma-manager/tests/framework/integration/installation_and_upgrade/jenkins_steps/main, chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests, chroma-manager/tests/framework/integration/upgrade_os/jenkins_steps/main, chroma-manager/tests/framework/integration/utils/upgrade_os.sh, chroma-manager/tests/framework/utils/provisioner_interface/provision_cluster, provisioner_output-vagrant-upgrade.json
Upgrades need to start on EL 7.3:
- update the Vagrant file to use an EL 7.3 image
- need to automate this in some way for only upgrade testing
- probably as part of moving vagrant reset to provisioning
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/390)
=> Run upgrade test in Vagrant

include/Makefile.version
Our code for reading tags assumes an annotated tag.
This is sub-optimal for releasing software using Github.
A typical software release on Github follows this process:
1. Go to the releases tab on the project and create a release (this creates a lightweight tag in the process).
2. Your build system (Travis etc...) will pick up on the release, and build the software. It will then publish it to the relevant spot (registry etc...).
We currently do not follow this workflow. Our build script is expecting an annotated tag, which means we need to:
1. Tag locally.
2. Push the tag to origin
3. Create a release from that existing tag.
4. Trigger and mark a build by hand.
5. Upload the artifact back to the release page.
We should additionally add a job that follows what Typical cloud CI providers …
=> Read lightweight tags for release

chroma-manager/tests/framework/utils/defaults.sh, chroma-manager/tests/framework/utils/provisioner_interface/provision_cluster
These changes allow one to run (say) SSI tests from your
local machine using your dev cluster as the place to run
the test.
An example commandline for running SSI tests for example:
$ make PROVISIONER="ssh <idsid>@ssi-builder.lotus.hpdd.lab.intel.com \\
OS=stdin sudo provision" ssi_tests
This should work equally well for efs_tests or upgrade_tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/411)
=> Changes needed to provision dev clusters

chroma-manager/tests/integration/core/api_testcase_with_test_reset.py, chroma-manager/tests/integration/installation_and_upgrade/test_update_with_yum.py
Because we can get an EBUSY on the root disk when trying to
partprobe it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/397)
=> Limit partprobing to storage disks

chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup, chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/jenkins_steps/main
Changes to allow one to run an SSI test on a GA release of
IML with additional storage server repos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/412)
=> Run SSI on GA with add'l storage server repos

chroma-manager/storage_server.repo, chroma-manager/tests/framework/utils/defaults.sh
Now that 2.10.2 is out we should use it in IML.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/423)
=> Bump to Lustre 2.10.2

chroma-agent/chroma_agent/device_plugins/linux_components/block_devices.py
We currently have two (at least) representations of
device paths.
Ideally, we should (and will) remove all duplicate
copies of data, but for now make sure we iterate adding
items to the normalized device path in reverse so
the end result is equivalent to the path chosen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/424)
=> Sync normalized device table with paths

chroma-manager/chroma_core/plugins/block_devices.py
Currently exported pools are reported in `device-aggregator` output. Given the manager should not be reporting exported zpools as suitable volumes we want to detect exported state and not report.
Although if a zpool is available on a secondary host (but still inactive/exported) we do want to be able to list it as a secondary mount. Therefore in this case it could be reported as ACTIVE whilst imported on the primary.
Another situation may arise where a zpool is not imported on any hosts but the constituent drives are visible, in this case we don't want to be displaying the underlying disk partitions used in a zpool as usable volumes. In this case the primary partition can be identified as *FS_TYPE=zfs_member* and the disk identifier as well as partitions 1 & 9 can be marked as not usable. …
=> Mark exported pools as not usable so they don't appear in volumes page

chroma-agent/chroma-agent.spec, chroma-manager/chroma-manager.spec, chroma-manager/chroma_core/plugins/block_devices.py
Update manager to require `iml-device-aggregator` and agent to require `iml-scanner-proxy` (which itself requires `iml-device-scanner2`).
requirements include
* availability of relevant packages via relevant repositories (currently temporarily sourced from bintray)
* landing of https://github.com/intel-hpdd/scanner-proxy/pull/7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/464)
=> Update manager and agent dependencies for reactive architecture

chroma-agent/chroma_agent/action_plugins/manage_targets.py
Fixes #476
In:
https://github.com/intel-hpdd/intel-manager-for-lustre/blob/5312a68772791aefa940f1774ff878df163f7d2d/chroma-agent/chroma_agent/action_plugins/manage_targets.py#L428-L451
we do not export the device(zpool) if it imports and the subsequent target mount fails.
The simplest approach (since the pools are managed by IML), is to export the pool if the target mount fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/479)
=> Pools need to be exported if target mount fails

.github/stale.yml
Add `stale.yml` to enable
the [stale](https://probot.github.io/apps/stale/) app for IML.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/489)
=> Enable stale probot app

chroma-agent/chroma-agent.spec
Now that device-scanner is going to be
backwards compatible, unpin it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/490)
=> Unpin device-scanner

chroma-manager/tests/framework/utils/selective_auto_pass.sh
Allow one to set test environment values with an Environment:
pragma in the commit message.
Used by adding a line to the commit message that starts with
the word Environment: followed by environment variables to set
such as "NOSE_ARGS=-x TESTS=tests/integration/shared_storage_configuration/test_conf_params.py:TestConfParams.test_writeconf_conf_params"
(without the quotes) as an example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/487)
=> Environment: pragma in commit message

chroma-agent/Target, chroma-agent/chroma_agent/action_plugins/manage_targets.py, chroma-agent/chroma_agent/lib/shell.py, chroma-bundles/install, chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests, chroma-manager/tests/framework/integration/utils/install_client.sh, chroma-manager/tests/framework/integration/utils/node_lib.sh, chroma-manager/tests/framework/integration/utils/reboot_node.sh, chroma-manager/tests/framework/utils/defaults.sh, chroma-manager/tests/framework/utils/selective_auto_pass.sh, chroma-manager/tests/services/test_nginx.py
Fixes #485
IML 3.1 only supports up to EL 7.3 so start upgrade testing
from RHEL 7.3, not 7.4.
RHEL 7.5's Python doesn't support SSLv2 so allow attribute
exception in any SSLv2 tests.
Auto-pass upgrade testing on CentOS because RHEL 7.5 won't
upgrade CentOS 7.3 due to distro packaging incompatibilities.
Slight change in crm_mon where it now reports on resources while
they are starting so only report locations of Started resources
and not Starting resources.  Additionally, a target that is
"Stopping" has not completed the transistion from "Started" (i.e.
running) to Stopped, so count it as running until it completes
the transition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Support RHEL 7.5

chroma-agent/chroma_agent/device_plugins/systemd_journal.py
starting the agent produces a journal entry like:
```json
{
"source": "dracut",
"message": "-rwxr-xr-x   1 root     root          422 Aug  5  2017
usr/bin/dracut-cmdline-ask",
"severity": 7,
"datetime": "2018-03-16T23:48:25.848126+00:00"
}
```
This breaks our current systemd_journal handling, as we expect
everything to have a SYSLOG_FACILITY
Fixes #504.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/518)
=> GH-504 Starting agent pushes journal entry without facility

chroma-bundles/install
We need to always be able to change the repos used for an
IML installation on every upgrade.
Users who want to override any of those repos need to do
so in the copy that is in the install dir *before* they
do an installation/upgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/523)
=> Always replace the chroma_support.repo during install

chroma-manager/tests/integration/core/utility_testcase.py
This makes it easier to discover who a _fetch_help() is
waiting for.
=> Put recipients in the key_file in _fetch_help()

chroma-manager/tests/integration/core/remote_operations.py
Workers are an IML managed resource and should be manipulated
using IML, not outside of it.
Fixes: #548
=> Don't unmount workers in unmount_clients()

chroma-manager/chroma_core/plugins/block_devices.py
Fixup zfs parsing in manager block_devices to work with new device-scanner.
TODO:
* process vdev tree not just the root node in https://github.com/intel-hpdd/intel-manager-for-lustre/pull/456 when enumerating zpool disks in https://github.com/intel-hpdd/intel-manager-for-lustre/pull/456/files#diff-9b785746172b9590b8d0bc97151ee6edR377
=> Fixup zfs parsing in manager block_devices

chroma-manager/tests/framework/utils/provisioner_interface/provision_cluster, chroma-manager/tests/framework/utils/provisioner_interface/test_json2provisioner_json.py
Caller can set $OVERRIDE_BUILD_JOB_NAME and
$OVERRIDE_BUILD_JOB_BUILD_NUMBER to override the chroma repo
that is supplied by the provisioner.
Fix a related bug so that we only modify test config's
"repos" once.
- if the caller has already set them, don't [re-]set them in
test_json2provisioner_json.py.
=> Allow caller to override provisioned chroma repo

chroma-manager/tests/integration/run_tests
In order to efficiently debug and fix failures, we should stop
on the first failure. This will allow us to collect
diagnostics relevant to the failure, and possibly debug
the nodes. It also prevents previous failures from
compounding and effecting future test cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/505)
=> Fail fast SSI tests

chroma-agent/10-device-scanner.socket.conf, chroma-agent/10-device-scanner.target.conf, chroma-agent/Makefile, chroma-agent/chroma-agent.service, chroma-agent/chroma-agent.spec, chroma-agent/iml-storage-server.target, chroma-manager/agent-bootstrap-script.template, chroma-manager/scripts/deploy_build, chroma-manager/tests/framework/integration/existing_filesystem_configuration/cluster_setup, chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests, chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup, chroma-manager/tests/integration/core/remote_operations.py, scripts/deploy_build
Fixes #572
Now that we are creating smaller stand-alone services, we need the ability to start / stop them in tandem.
We can create either a iml-storage-server.target or dummy iml-storage-server.service unit to control starting / stopping these services in tandem.
This will handle the following services (so far) either directly or indirectly:
chroma-agent
device-scanner
scanner-proxy
mount-emitter
Things we need to consider:
We should repopulate the scanner if the service has stopped, but not if it has been running since boot.
=> Create service grouping systemd units

chroma-agent/chroma_agent/device_plugins/block_devices.py, chroma-agent/chroma_agent/device_plugins/lustre.py
localMounts are currently being cached at module load time, and are
never evaluated afterwards.
This is causing us a bunch of issues where mount state is not as
expected.
Remove the caching, so we evaulate local mounts each time we call the
function.
=> Remove caching of localMounts

chroma-manager/tests/framework/utils/selective_auto_pass.sh
Can be use by adding "COPR Module: owner/project" as a pragam to
your commit message.
=> Add a pragma to use COPR modules

chroma-agent/chroma_agent/device_plugins/lustre.py, chroma-manager/tests/integration/existing_filesystem_configuration/utils/create_lustre_filesystem.py
Derive necessary information (lustre fs Target label and relevant lv uuid) from `device-scanner` local mount output and provide this in the output of the lustre agent device plug-in.
Fix a bug when using fstab to persist mount info when previous lvm mount unit remains in cache and subsequent mount operation on different fstype attempts to bind to it.
=> EFS fix detection of LVM mounts

chroma-manager/tests/integration/existing_filesystem_configuration/utils/create_lustre_filesystem.py, chroma-manager/tests/integration/utils/test_filesystems/test_filesystem.py
Install packages in parallel during EFS tests, this can be done when creating the lustre file system and before running tests due to the assumption that all device types for targets are the same in a test.
Changes can be easily reverted if we need to have a mix of device types for EFS testing in the future.
Fixes #591 
Duplicates #591
=> Efs install parallel2

chroma-agent/chroma_agent/device_plugins/linux_network.py
We are currently determining if LNet is loaded by looking for "lnet"
inside of "/proc/modules." Furthermore, we are checking to see if lnet
is up by looking at "/proc/sys/lnet/stats". This is a problem for a
couple of reasons:
1. We shouldn't have to rely on looking at these files
2. What if the files change (and they are in an upcoming version of
Lustre).
A better solution is to:
1. use the result of "udevadm info --path /sys/module/lnet" to determine if lnet is loaded
2. Use the result of "lnetctl net show" to determine if lnet is started
By doing this, we are using reliable commands and are no longer coupled
to these files.
=> Fix LNet Detection

chroma-manager/tests/integration/core/api_testcase_with_test_reset.py, chroma-manager/tests/integration/existing_filesystem_configuration/utils/create_lustre_filesystem.py, chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice.py, chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice_linux.py, chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice_lvm.py, chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice_zfs.py
EFS tests are failing because during test reset we wipe disks and then create a gpt partition, subsequently vgcreate cannot operate on the base disk (because it now has a partition).
Initially create gpt partition before creating zpool but not after wiping disks to avoid the above.
Separate out actions for preparing a device into wiping the signatures and actually creating the device, create a new commands method to reset device calling both wipe and create.
Fixes #587
=> Separate prepare_device_commands into wipe_signatures and create_device

chroma-manager/tests/integration/core/api_testcase_with_test_reset.py, chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice_zfs.py
`zpool labelclear` was attempting to use the disk partition. However, it was using the zpool name with a `part1` suffix which meant the label was never cleared.
In addition, clearing the device was happening twice, so for now switch back from reseting the device to creating it.
=> Fix zpool labelclear

chroma-manager/tests/integration/core/stats_testcase_mixin.py, chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py
This is a failure within the check_stats routine.
http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/5482/
```
(tests.integration.shared_storage_configuration.test_managed_filesystem_with_failover.TestManagedFilesystemWithFailover) ... FAIL
FAIL
Traceback (most recent call last):
File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 72, in test_create_filesystem_with_failover_mds
filesystem_id, volumes_expected_hosts_in_normal_state = self._test_create_filesystem_with_failover()
File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 36, in _test_create_filesystem_with_failover …
```
=> SSI: Verification of metrics fails intermittently

chroma-manager/chroma-manager.conf.template, chroma-manager/chroma-manager.spec, chroma-manager/chroma_core/management/commands/nginx.py, chroma-manager/chroma_core/plugins/block_devices.py, chroma-manager/scripts/nginx_settings.py, chroma-manager/settings.py
Exceptions occurring in `plugin_runner.log` due to failing connection attempts to the device aggregator socket:
```
[2018-05-20 20:15:03,293: ERROR/service_thread] Exception in main loop.  backtrace: Traceback (most recent call last):
File "/usr/share/chroma-manager/chroma_core/services/__init__.py", line 75, in run
self.service.run()
File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/agent_daemon.py", line 62, in run
self._queue.serve(session_callback = self.on_message)
File "/usr/share/chroma-manager/chroma_core/services/queue.py", line 106, in serve
return ServiceQueue.serve(self, self.__route_message)
File "/usr/share/chroma-manager/chroma_core/services/queue.py", line 70, in serve
callback(message)
File "/usr/share/chroma-manager/chroma_core/services/queue.py", line …
```
=> Exception in plugin_runner log when accessing aggregator socket

chroma-manager/tests/integration/shared_storage_configuration/test_ha_clustering.py, chroma-manager/tests/integration/shared_storage_configuration/test_volumes.py
There could be volumes that are available on a node, depending on how
it was provisioned, that while perfectly valid for a Lustre target,
are not the ha-capable, shared volumes we are interested in.
=> Account for any non-shared/non-ha volumes available

chroma-manager/chroma_core/lib/service_config.py, chroma-manager/iml-manager.target
We need to make sure that when starting the
iml-manager.target, we both require the device-aggregator
and wait for postgres + rabbitmq to be up.
=> Add more service ordering

chroma-manager/tests/integration/core/api_testcase_with_test_reset.py
Related to #645, update some multihost parameters
for test to decrease likelyhood of suspension when
MMP writes do not occur over a time interval. Also
log the last 100 MMP writes.
=> Update zfs multihost parameters for test

chroma-manager/chroma_core/plugins/block_devices.py, chroma-manager/chroma_core/plugins/linux.py, chroma-manager/chroma_core/services/plugin_runner/resource_manager.py
Each disk used in a zpool normally has partitions 1 & 9, these are displayed when the zpool is not imported on any monitored or managed storage server in IML as volumes available for lustre targets.
The aforementioned partitions should not be displayed as usable.
Correct behaviour should be as follows:
* With a clean disk, disk label should be displayed as usable volume 
* `# zpool create -f testPool5 /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk5`
disk label should disappear and zpool name should be displayed as usable volume
* `# zpool export -a`
zpool name should disappear and no entries related to disk/zpool should be present (including no disk partitions)
* `# zpool import -a`
zpool name should appear as a usable volume
* `# zpool destroy testPool5`
zpool name should disappear and no …
=> Exported zpool disk partitions displayed as usable volumes

iml-corosync.service, iml-http-agent.service, iml-job-scheduler.service, iml-lustre-audit.service, iml-manager.target, iml-plugin-runner.service, iml-stats.service, iml-syslog.service
We have a number of services that need to come up after
rabbitmq-server.
Add the `After` directive to ensure they are started after
rabbitmq-server.
=> Add ordering on rabbitmq-server

python-iml-manager.spec.in
Nginx in EPEL already default to worker_process auto.
We don't need to alter it anymore in the spec.
=> Remove worker_process changes.

chroma_core/lib/service_config.py, iml-settings-populator.service
Add a flag `service_config.py` that checks if
we are running in docker. We can use this flag
to skip setup of services that have been extracted into their
own container.
In addition, changes the requires to a wants for `iml-settings-populator`
so we don't die if postgres isn't present.
=> Add flag if running in docker

Vagrantfile
Since we are using vagrant from scl,
and the scl vagrant is prior to
the move to vagrant cloud, we need to
forcfully override the server url
so things keep working.
- Replace default url.
- Do some linting cleanups.
=> Fixup Vagrantfile to work with scl

chroma_api/alert.py
There is a bug with updates_available in that we don't
check for boolean `True` / `False`, but instead for truthiness,
This means a valid value of `False` will cause validation to fail.
Fix this.
=> Fix bug with updates_available available field.

python-iml-manager.spec.in
Update the triggerun so it fires correctly for the python2-iml-manager
subpackage.
=> Update config move.

chroma_core/management/commands/print-settings.py, chroma_core/migrations/0040_table_update_notify.py, chroma_core/migrations/0041_table_update_notify.py
Add triggers for broadcasting Insert | Update | Delete changes on all
relevant chroma_core_* tables.
This will use Postgres NOTIFY to send a comma separated list of
operation name and id.
We should be using `json_build_object` but that's not available till
postgres 9.3.
Building off of this, any process with a client connection can do a
`LISTEN table_update` and will be asynchronously notified of changes on
the table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/130)
=> Add Notify triggers for relevant chroma_core_* tables. 

.travis.yml, docker-compose.yml
We are currently using docker cloud
to build images upon landing something in the IML repo.
This currently has two downsides:
1. manager-service-base needs to be built / pushed before everything
else builds, but there is not a way to sequence that.
2. There are very long queueing times in docker cloud, leading to large
lags between landing some changes and it moving to production.
By moving the continuous integration step to travis we alieviate both of
these issues.
=> Build docker images in travis

chroma_agent_comms/views.py, chroma_core/plugins/linux.py, python-iml-manager.spec.in
Always try to use device-aggregator data first, but allow IML 4.0
to pass device data via linux plugin (/agent/message).
=> Accept linux plugin device data

chroma-manager.py, chroma_core/services/rpc.py, docker-compose.yml
Upon trying IML in docker on a larger system, I noticed a few areas of
improvement.
1. We should scale down our gunicorn workers a bit (max out at 8).
This improves memory usage considerably while still maintaining the same
level of responsiveness.
2. Add a retry to intermittent queue connection issues. While
debugging https://success.docker.com/article/ipvs-connection-timeout-issue I
noticed that kombu (rabbitMQ client lib) has a retry option. I've added
this to at least notify that we have an issue and might retry.
3. The RabbitMQ container can be ephemeral; there is nothing durable
that needs to be stored. In addition we can use the management version
which will allow us to view connections / queues / exchanges etc... over
port 15672.
=> IML container tuning

chroma_core/lib/service_config.py
When processes are asked to start, either them or if they are running, reload their configs.
=> Restart nginx after upgrade

chroma_core/models/host.py, chroma_core/models/server_profile.py
List required packages so it will get saved on client so update checker can look at it.
Also add step to refresh profile on server upgrade.
Related to Issue #744 
=> Add packages to profile on client

tests/integration/core/chroma_integration_testcase.py, tests/integration/core/failover_testcase_mixin.py, tests/integration/core/remote_operations.py
RealRemoteOperations.await_server_boot() should wait for pacemaker to be
quiescent before returning.
This now not only waits for node to be online in pacemaker, but also
waits for all resources to be started.
=> await_server_boot should wait for resources

chroma_core/lib/service_config.py
The iml-settings.conf file was being created using redirection, which is not
an atomic operation. The result of doing this is that the file will be
created without contents. This ultimately leads to multiple docker
containers thinking environment variables are available when they
actually aren't and causes the process running in the container to
crash.
This patch changes how the iml-settings.conf file is created by first
redirecting into a temp file and then using the `mv` command to move it
to /var/lib/chroma/iml-settings.conf. The mv command is atomic and
guarantees that the contents will be available when the file exists.
=> Create iml-settings file using atomic operation

tests/integration/shared_storage_configuration/test_storage_server_authentication.py
Fixes #778
https://github.com/whamcloud/integrated-manager-for-lustre/blob/5f8dcc3615388527c833df348617119352f51d07/tests/integration/shared_storage_configuration/test_storage_server_authentication.py#L10
Is using the wrong path. It should be `"/etc/iml/"`.
```
Traceback (most recent call last):
File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_storage_server_authentication.py", line 18, in test_server_authentication
"%s/private.pem.save" % self.SECURITY_FILE_DIR,
File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 325, in copy_file
self._ssh_address(address, "cp %s %s" % (current_file_path, new_file_path))
File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 236, in _ssh_address
% (rc, …
```
=> SSI: test_server_authentication using wrong path

chroma-manager/iml-corosync.service, chroma-manager/iml-http-agent.service, chroma-manager/iml-job-scheduler.service, chroma-manager/iml-lustre-audit.service, chroma-manager/iml-manager.target, chroma-manager/iml-plugin-runner.service, chroma-manager/iml-stats.service, chroma-manager/iml-syslog.service
We have a number of services that need to come up after
rabbitmq-server.
Add the `After` directive to ensure they are started after
rabbitmq-server.
=> Add ordering on rabbitmq-server (#665)

chroma_core/models/lnet_configuration.py, chroma_core/models/power_control.py, chroma_core/south_migrations/0042_power_control_type_remove_null_options.py, chroma_core/south_migrations/0043_alter_power_control_type_option_default.py
The `PowerControlType` model specifies that default_options can be null.
If this happens, a template can end up sending power control commands to
the agent with `None` for options.
Update the model and add a SchemaMigration / DataMigration to convert
all Null options to "".
=> Enforce default-options are non-null

tests/integration/core/chroma_integration_testcase.py, tests/integration/core/utility_testcase.py
We have a fetch-help call that's currently a noop as emails
aren't going out.
Remove it.
=> Remove fetch-help from server install

chroma_core/services/http_agent/__init__.py
There is a typo when stopping the `http_agent`.
We call `tx_svc_thread.join()` twice but we really want to call
`rx_svc_thread.join()` the second time.
=> Join rx_svc_thread

chroma_core/lib/util.py
Comparison [here](https://github.com/AlexTalker/integrated-manager-for-lustre/blob/master/chroma_core/lib/detection.py#L237) fails if I have an `InfiniBand` interface utilized by `LNet`.
This happens because `normalize_nid` doesn't act the same as the [agent](https://github.com/whamcloud/iml-agent/blob/master/chroma_agent/device_plugins/linux_network.py#L248).
Example of such metadata for `MGS`:
```
checking for existing Lustre data: found
Reading CONFIGS/mountdata
Read previous values:
Target:     MGS
Index:      unassigned
Lustre FS:  
Mount type: ldiskfs
Flags:      0x1004
(MGS no_primnode )
Persistent mount opts: user_xattr,errors=remount-ro
Parameters:    failover.node=:10.239.239.1@o2ib:10.239.239.2@o2ib
Permanent disk data:
Target:     MGS
Index:      unassigned
Lustre FS:  
Mount …
```
=> Fixed NID without network ID for all types of networks

chroma_cli/parser.py, chroma_core/models/command.py, chroma_core/models/corosync.py, chroma_core/models/corosync2.py, chroma_core/models/corosync_common.py, chroma_core/models/host.py, chroma_core/models/pacemaker.py, chroma_core/models/target.py, chroma_core/services/job_scheduler/job_scheduler.py, tests/unit/services/job_scheduler/test_job_scheduler.py, tests/utils/http_requests.py
We're intermittently seeing the following errors in the
job_scheduler.log:
```
[2019-01-08 17:43:03,166: CRITICAL/job_scheduler] Unhandled exception in RunJobThread: Traceback (most recent call last):
File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 270, in run
self._run()
File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 294, in _run
self.job.id, step_klass=klass, args=clean_args, step_index=step_index, step_count=len(self.steps)
File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 197, in getter
self.put(deepcopy((name, args, kwargs)))
File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
y = copier(x, memo)
File "/usr/lib64/python2.7/copy.py", line 237, in …
```
=> Fix jobscheduler bug.

chroma_core/lib/service_config.py
If repos aren't created as enabled, they won't be used by default.  This fixes that issue.
Follow up to #812
Fixes #820
=> Enable locally created repos

.travis.yml
Fixes #842.
Description:
the `nginx.dockerfile` copies in `imlteam/iml-wasm-components`:
https://github.com/whamcloud/integrated-manager-for-lustre/blob/5907acc63ea2054e9bb5e45cddac020da6907500/docker/nginx.dockerfile#L20
but `imlteam/iml-wasm-components` is not built anywhere.
Add building of `imlteam/iml-wasm-components` to the docker ci publish job.
=> Add iml-wasm-components docker build to CD step in travis file

iml-agent-comms/src/flush_queue.rs, iml-agent-comms/src/host.rs, iml-agent/src/http_comms/session.rs, iml-agent/src/poller.rs, iml-agent/src/reader.rs, iml-services/src/services/action_runner/receiver.rs, iml-services/src/services/action_runner/sender.rs, iml-wire-types/src/lib.rs
If we get a request error from checking on pending manager commands,
terminate all the agent sessions.
- Update flush_queue to use Either instead of Box.
- Make session reset_empty always resets.
- Make sure sessions terminate when manager is unreachable
=> Terminate all agent sessions on manager connection loss

Cargo.lock, iml-agent-comms/src/main.rs, iml-agent-comms/src/messaging.rs, iml-rabbit/src/lib.rs
Channels must be closed when finished so we don't leave "dead" channels.
Implement a `close_channel` fn for `iml-rabbit` and use it in
`send_message`.
=> Ensure channels are closed when finished

iml-agent-comms/src/flush_queue.rs, iml-agent-comms/src/host.rs, iml-agent-comms/src/main.rs, iml-agent-comms/src/messaging.rs, iml-agent-comms/src/session.rs, iml-agent/src/action_plugins/action_plugin.rs, iml-services/src/services/action_runner/main.rs, iml-services/src/services/action_runner/receiver.rs, iml-services/src/services/action_runner/sender.rs, iml-wire-types/src/lib.rs
In iml-agent-comms we are overly-aggressive when removing hosts.
Instead of removing and re-creating the hosts, we should only look to clear out any stale sessions.
Fixes #876.
=> Hosts can be removed / re-added prematurely

chroma_core/services/lustre_audit/update_scan.py
Unfortunately, I came across something broken again.
If I do fail-over a target from primary node, after short amount of time(about 7 minutes usually),
charts on dashboard, related to the target, shows "No data available" sign for everything.
I noticed that action happens just after the fail-over and the log shows this:
```
http-agent_1         | ::ffff:172.27.0.17 - - [2019-02-12 10:18:26] "POST /agent/message/ HTTP/1.0" 200 115 0.002040
device-aggregator_1  | Aggregator received update with devices from host lustre2.rd.com
lustre-audit_1       | [2019-02-12 10:18:26,405: WARNING/chroma_core.services.lustre_audit.update_scan] Discarding metrics for unknown target: fs1-OST0
000 (VolumeNode matching query does not exist.)                                        
lustre-audit_1       | …
```
=> "No data available" when target is active on failover node

chroma_core/lib/metrics.py, chroma_core/models/stats.py
Hello again
The problem in this case that if only one value is returned from the model,
and `rate` operator specified(which is default for `fetch_jobs`), then related "Jobstats" page
says that no data is available.
However, that's not true.
In any way, you seem to have strange representation of timestamps since on the server side they tend to change up to 10 seconds and highly depend on client-side time, which is strange since you do display charts correctly BUT the user may not find associated `Jobstats` by clicking on the heat-map chart, since the values falls out of transformed `begin` and `end` range.
Also, hell knows why you do not show target names on the chart but the `PK` instead.
=> Jobstats: Do not return empty list when only one point fall in range

iml-wasm-components/Cargo.lock, iml-wasm-components/iml-action-dropdown/Cargo.toml
wasm-bindgen is out of date with upstream.
To avoid having this problem, unpin the patch version
of wasm-bindgen.
=> Bump Wasm deps

python-iml-manager.spec.in
There are some package renames that need to be explicitly obsoleted.
=> Obsolete old packages

Cargo.lock, iml-agent/Cargo.toml, iml-agent/src/agent_error.rs, iml-agent/src/http_comms/agent_client.rs, iml-agent/src/http_comms/crypto_client.rs
Fixes #907.
In order to process data as it comes in, it would be useful to have streaming support for GET requests.
Add streaming support for GET requests, and add a lib to emit data line by line.
=> Add line-delimited streaming support to crypto-client

python-iml-manager.spec
This allows httpd to be installed on nodes where IML repository is available.
This is needed for correct robinhood installation.
Fixes Issue #731 
=> Remove obsoletes for httpd

docker/docker-compose.yml, python-iml-manager.spec, scm_version.py
When deriving `PACKAGE_VERSION`, ensure we use the `version` property.
Fixes #922.
=> Pull version from pkg_resources

chroma_core/models/corosync2.py, tests/unit/chroma_core/jobs/test_corosync2_jobs.py
Set hostname to FQDN so that corosync and pacemaker work nicely
when ring0 is crossover.
Fixes #816 
=> Set FQDN so HA works when hostname != FQDN

tests/integration/core/api_testcase_with_test_reset.py
60 seconds is twice the default SCSI timeout
=> Bump multihost I/O timeout to 60 seconds

python-iml-manager.spec, scm_version.py
Make sure the old Django-south is obsoleted when we install newer IML.
=> Obsolete Django-south

chroma_core/lib/service_config.py, python-iml-manager.spec, scm_version.py
In Django 1.6 sessions internal representation changed to remove pickling.  
In order to upgrade cleanly, we need to wipe out all the old sessions so downstream services can rely on sessions being in the new format.  
=> Clear old sessions before upgrading

iml-agent-comms/src/flush_queue.rs, iml-agent-comms/src/host.rs, iml-agent-comms/src/main.rs, iml-agent/src/action_plugins/stratagem/server.rs, iml-agent/src/main.rs, iml-agent/src/reader.rs
Fixes #878.
If a session is cancelled, an older session may sit draining on the flush_queue up until timeout.
Have the flush_queue take a oneshot channel that will resolve when a session is terminated.
The other half of the channel should be held by a session, and should fire on session termination.
=> flush_queue should take a oneshot channel for cancelation

chroma_core/models/target.py
We currently wait for an hour for a target to mount which may be a bit excessive.
Instead wait for 10 minutes.
=> Shorten target mount timeout

.travis.yml
Make publishing docker containers a manual process, so we don't build
new containers for every master landing.
=> Make docker publish manual process

chroma_core/lib/job.py, chroma_core/lib/util.py, iml-agent/src/action_plugins/stratagem/server.rs, iml-agent/src/daemon_plugins/action_runner.rs, iml-manager.target, python-iml-manager.spec, requirements.txt, tests/unit/chroma_core/lib/test_util.py
Create a bridge such that the manager python steps can invoke actions
on an agent running in rust.
=> Create bridge between rust and python layer in the manager

Cargo.lock, iml-agent/Cargo.toml, iml-agent/src/action_plugins/action_plugin.rs, iml-agent/src/agent_error.rs, iml-agent/src/env.rs, iml-agent/src/server_properties.rs
Fixes #959.
Instead of converting an `ImlAgentError` into a `serde_json::Value`,
convert it to a string using the `Display` trait.
- Lint fixups.
- Bump deps.
=> Ensure action plugin output reflects action result

iml-agent/src/action_plugins/stratagem/server.rs, iml-agent/src/cli.rs
Update the scan output so original rule names (arguments) are
preserved. The output of the scan will now look like:
```json
{
"Ok": [
{
"group_counters": [
{
"counters": [
{
"count": 1,
"have_flist": false,
"name": "Other"
},
{
"count": 0,
"have_flist": false,
"name": "smaller_than_1M"
},
{
"count": 0,
"have_flist": false,
"name": "not_smaller_than_1M_and_smaller_than_1G"
},
{
"count": 1,
"have_flist": false,
"name": "not_smaller_than_1G"
},
{
"count": 0,
"have_flist": false,
"name": "not_smaller_than_1T"
}
],
"name": "size_distribution"
},
{
"counters": [
{
"count": 2,
"have_flist": false,
"name": "Other"
},
{
"count": 0,
"have_flist": true,
"name": "shell_cmd_of_rule_0"
},
{
"count": 0,
"have_flist": true,
"name": "shell_cmd_of_rule_1"
}
],
"name": "warn_purge_times"
}
]
}, …
```
=> Update scan output

iml-wasm-components/.copr/Makefile, iml-wasm-components/Cargo.lock, iml-wasm-components/Cargo.toml, iml-wasm-components/iml-action-dropdown/Cargo.toml, iml-wasm-components/iml-action-dropdown/src/action_items.rs, iml-wasm-components/iml-action-dropdown/src/lib.rs, iml-wasm-components/iml-action-dropdown/src/sleep.rs, iml-wasm-components/iml-tooltip/Cargo.toml, iml-wasm-components/iml-tooltip/src/lib.rs
Split the tooltip component into it's own crate
=> Split off the tooltip into new crate

.copr/Makefile, Cargo.lock, Cargo.toml, chroma_core/lib/service_config.py, iml-agent/Cargo.toml, iml-agent/src/action_plugins/stratagem/server.rs, iml-agent/src/agent_error.rs, iml-agent/src/http_comms/mailbox_client.rs, iml-agent/src/lib.rs, iml-fs/Cargo.toml, iml-fs/src/lib.rs, iml-mailbox/Cargo.toml, iml-mailbox/src/lib.rs, iml-mailbox/src/main.rs, iml-manager-cli/src/main.rs, python-iml-manager.spec
Instead of streaming lines from the agent, stream the bytes directly.
The receiver will split on lines instead.
In addition, extract async fs actions so they are reusable between
crates.
=> Fixup mailbox streaming

chroma_core/services/job_scheduler/job_scheduler.py
Steps do not currently pass in the previous step results. This patch
will enable the result of a step to be passed into the next running
step.
=> Propagate step results to next step during job execution

chroma-manager.conf.template
The body for a mailbox POST may be quite large.
set `client_max_body_size` to `0m` so nginx does not check for a maximum
size and return a 413 response.
=> Remove max-body for mailbox endpoint

chroma_core/lib/job.py
Create a wrapper for invoke_rust_agent that will handle errors at the
base Job level so that the handling does not have to be done in each
job.
=> Add invoke_rust_agent_expect_result

iml-manager-cli/src/api_utils.rs, iml-manager-cli/src/lib.rs, iml-manager-cli/src/main.rs, iml-manager-cli/src/manager_cli_error.rs, iml-wire-types/src/lib.rs
When running a manager CLI call, it may return a `Command` resource.
When this occurs we should wait for it to complete while showing a nice
progress message.
=> Wait for cmd

iml-wasm-components/Cargo.lock, iml-wasm-components/Cargo.toml, iml-wasm-components/iml-action-dropdown/Cargo.toml, iml-wasm-components/iml-action-dropdown/src/lib.rs, iml-wasm-components/iml-wasm/Cargo.toml, iml-wasm-components/iml-wasm/src/lib.rs
So we can expose multiple modules from the root.
=> Add top-level wasm package

Cargo.lock, iml-wire-types/Cargo.toml, iml-wire-types/src/lib.rs
Add types cooresponding to /api/action so they can be shared.
=> Add action types

Cargo.lock, iml-agent/src/action_plugins/stratagem/action_purge.rs, iml-agent/src/action_plugins/stratagem/action_warning.rs, iml-agent/src/action_plugins/stratagem/server.rs, iml-agent/src/cli.rs, iml-mailbox/src/lib.rs
This patch adds support for parsing and displaying
`LAT_ATTR_CLASSIFY` rules.
=> Add support for `LAT_ATTR_CLASSIFY` rules

python-iml-manager.spec
Ensure that upgraded systems have a version of rabbitmq-server that will
work with IML-5
=> Pin Rabbitmq-server

iml-agent/Cargo.toml, iml-agent/src/action_plugins/stratagem/action_purge.rs, iml-agent/src/action_plugins/stratagem/action_warning.rs
until fidlists are implemented as streaming JSON,
we need to parse them as space-separated.
=> Parse fids as non-JSON

chroma_core/lib/service_config.py, settings.py
Separate databases will be required in order to manage retention between
stats and stratagem scans. Create a unique database for stratagem scans.
=> Update influx db name for stratagem scans

Cargo.lock, iml-agent/src/action_plugins/stratagem/action_warning.rs, liblustreapi-sys/Cargo.toml, liblustreapi/Cargo.toml, liblustreapi/src/lib.rs
The ioctl call inside `mdc_stat` was not checking `errno` and instead
was treating the absolute value of the return code as the error.
Use errno if the return of the ioctl is < 0.
In addition there were some unsafe calls that could error. Make sure
those calls are handled properly and check their `errno`s.
=> Fixup mdc_stat call

liblustreapi/src/lib.rs
When copying the file name for an `IOC_MDC_GETFILEINFO` ioctl call,
we need to ensure we are using a `CString` so the file is null
terminated and Lustre doesn't try to read any garbage memory after it.
=> Ensure filename passed to IOC_MDC_GETFILEINFO is null terminated

liblustreapi/src/lib.rs
Purging takes place with a chunk of 10 and attempts to remove the fids.
If an error occurrs on any of the 10 fids, it will immediately return,
which means the remaining (up to 9) files may not have been
processed and thus will not have been removed. This is reproducable
every time due to phantom fids throwing errors. This patch will
instead log the information and continue to the next fid instead of
returning from the function immediately.
=> Fix fid error

chroma_core/lib/service_config.py
with the advent of `chronyd`, `ntpd`, which IML currently relies on may
be inactive.
Make sure we stop and disable chronyd on the manager.
=> Ensure ntpd is running

Cargo.lock, iml-agent-comms/Cargo.toml, iml-agent/Cargo.toml, iml-manager-cli/Cargo.toml, iml-rabbit/Cargo.toml, iml-services/Cargo.toml, iml-warp-drive/Cargo.toml, iml-warp-drive/src/locks.rs, iml-warp-drive/src/request.rs, iml-wasm-components/Cargo.lock, iml-wasm-components/iml-action-dropdown/Cargo.toml, iml-wasm-components/iml-action-dropdown/src/hsm_dropdown.rs, iml-wasm-components/iml-action-dropdown/src/model.rs, iml-wasm-components/iml-alert-indicator/Cargo.toml, iml-wire-types/Cargo.toml, iml-wire-types/src/lib.rs
Move the Lock types into wire-types so they can be shared between the
browser and server.
=> Move lock types into wire-types

iml-agent/src/action_plugins/stratagem/server.rs, iml-agent/src/cli.rs, iml-manager-cli/src/main.rs
Currently, the cli converts hours to seconds and days to seconds.
Stratagem uses milliseconds instead of seconds so the conversion needs
to be updated.
- Convert hours to milliseconds
- Convert days to milliseconds
=> Update manager cli to parse purge and report durations correctly

iml-manager-cli/src/manager_cli_error.rs
New validation codes are available and need to be added to the
RunStratagemCommandResult enum.
=> Add Validation cases to RunStratagemCommandResult enum

chroma_api/stratagem.py, iml-manager-cli/src/manager_cli_error.rs
Validation does not currently take into consideration that a client may
not have been added to IML. Running stratagem will result in a "Host not
found" error. Instead, the validation should ensure that a client has
been added with the stratagem client profile before running or
configuring stratagem.
=> Add Stratagem Client Validation

iml-wasm-components/iml-pie-chart/src/lib.rs
Division of f64 by 0 yields NaN.
Special case when total is 0 to not divide.
=> Avoid divide by 0 on pie chart

iml-wasm-components/iml-action-dropdown/src/deferred_action_dropdown.rs, iml-wasm-components/iml-action-dropdown/src/model.rs
Actions may be empty when a job is in progress. Make sure to filter those out as the label would still be there.
=> Filter out empty actions

.copr/Makefile, chroma_core/lib/stratagem.py, grafana/dashboards/iml-dashboards.yaml, grafana/dashboards/stratagem-dashboard-1.json, python-iml-manager.spec
Grafana allows for privisioning of dashboards as well as data sources.
This patch will provision grafana with a stratagem dashboard that will
be built and ready to go as soon as installation completes. This will
allow us to easily embed an iframe and create the chart component.
=> Add Grafana Dashboard Provisioning

chroma-manager.conf.template
Fixes #1056.
Description:
Since influxdb provides an http api, the reverse proxy feature of nginx
should be leveraged to allow a query to be run from the application.
This will allow components to be given a stream coming directly from the
database rather than having to go through realtime to get the data. The
end point should be restricted to GET only and should follow
authentication rules. Queries can be made in the form:
https://localhost:8443/influx/<dbname>/<query>
=> GH-1056 - Create nginx integration with influx

chroma_api/stratagem.py, chroma_core/models/stratagem.py, chroma_core/south_migrations/0046_auto__add_sendstratagemresultstoclientjob__add_stratagemconfiguration_.py, iml-manager-cli/src/manager_cli_error.rs
Fixes #1062.
GH-1062 - Stratagem duratiion models should be bigint
Since milleseconds will be used for duration and it's possible that a
number of years could be specified, the fields should be of the
BigInteger type instead of Integer. This patch will ensure that:
1. The duration fields on the models use BigInteger
2. The API will handle hydrating and dehydrating data from String to
BigInteger such that data is stored as a u64 in the database and
retrieved as a long instead of a string (Tastypie does not support
BigInteger in resources so it must be converted to a long)
3. Validation is added to ensure that no value > MAX_SAFE_INTEGER (9007199254740991)
can be used for either duration.
=> GH-1062 - Stratagem duration models should be bigint

iml-wasm-components/Cargo.lock, iml-wasm-components/Cargo.toml, iml-wasm-components/iml-environment/src/lib.rs, iml-wasm-components/iml-grafana-chart/Cargo.toml, iml-wasm-components/iml-grafana-chart/src/lib.rs, iml-wasm-components/iml-stratagem/Cargo.toml, iml-wasm-components/iml-stratagem/src/lib.rs
Fixes #1050.
Grafana charts will be inserted via an iframe. Create the `iml-grafana`
module that will return an iframe that loads the specified chart. Also
create the `iml-stratagem` module with a view function to load the size
distribution chart.
=> GH-1050 - Create grafana chart iframe and iml-stratagem module

iml-wasm-components/Cargo.lock, iml-wasm-components/Cargo.toml, iml-wasm-components/iml-alert-indicator/src/lib.rs, iml-wasm-components/iml-fs-page/Cargo.toml, iml-wasm-components/iml-fs-page/fs-page.rs, iml-wasm-components/iml-wasm/Cargo.toml, iml-wasm-components/iml-wasm/src/lib.rs
=> Implement the Filesystem page in seed

.gitignore, Cargo.lock, chroma_core/south_migrations/0040_table_update_notify.py, chroma_core/south_migrations/0047_table_json_notify.py, docker/iml-warp-drive.dockerfile, docker/iml-wasm-components.dockerfile, iml-manager-cli/src/api_utils.rs, iml-manager-cli/src/main.rs, iml-manager-client/src/lib.rs, iml-postgres/Cargo.toml, iml-postgres/src/lib.rs, iml-warp-drive/Cargo.toml, iml-warp-drive/src/cache.rs, iml-warp-drive/src/db_record.rs, iml-warp-drive/src/lib.rs, iml-warp-drive/src/listen.rs, iml-warp-drive/src/main.rs, iml-warp-drive/src/users.rs, iml-wire-types/src/lib.rs, tokio-runtime-shutdown/Cargo.toml, wsgi.py
Use the LISTEN NOTIFY functionality of Postgres
to drive push updates through warp-drive.
Since warp-drive is a persistent session, we should be able to
limit updates to the row-level instead of the rows-level as is currently
done in realtime.
=> Use warp-drive for notify updates

chroma_core/models/stratagem.py
Only start timer after unit start, not based on IML boot time.
Fixes #1117
=> Start timer after interval from unit activation

Cargo.lock, iml-agent/src/action_plugins/stratagem/server.rs, iml-fs/src/lib.rs, iml-mailbox/Cargo.toml
Fixes #1123.
By breaking the streaming of fidlists from one request per result thread
to one request per 5000 fids per result thread we can decrease streaming
time from ~3mins to ~1ms.
=> Update perf streaming from MDS to the manager

chroma_core/models/stratagem.py
If you re-add a timer, the old timer should be removed.  This allows "updating" a timer via running add a second time.
Fixes #1099
=> Statagem timer re-add removes old timer

chroma_api/stratagem.py, chroma_core/models/stratagem.py, chroma_core/services/job_scheduler/job_scheduler.py, chroma_core/south_migrations/0046_auto__add_sendstratagemresultstoclientjob__add_stratagemconfiguration_.py, iml-manager-cli/src/stratagem.rs, iml-wire-types/src/lib.rs
Fixes #1094.
If Stratagem is configured for the fs, it should have it's UnconfigureStratagemJob run as part of the fs removal.
=> When forgetting the filesystem in Monitored mode, also forget Stratagem

iml-wasm-components/iml-stratagem/src/inode_table.rs
Fixes #1096.
The top inode users table should be truncated after n users to deal with the case where there may be many users writing data to a client.
=> Top inode users table should be truncated after n users

chroma_api/stratagem.py, chroma_core/models/stratagem.py
they don't exist
Fixes #1137.
- Make sure values are not None before checking if they are negative in
validation
- Filter out action items if the mailbox file does not exist
=> Stratagem scan attempts to send fid and purge lists to client, even if

base_managed_ib_RH7.profile, lustre-client-mlnx.repo, posix_copytool_worker_mlnx.profile, robinhood_server_mlnx.profile
Add mellanox flavour client repo
Add client profiles to utilize mlnx client
=> Add Mellanox client profiles / repo

chroma_api/stratagem.py, chroma_core/services/job_scheduler/job_scheduler.py, chroma_core/services/job_scheduler/job_scheduler_client.py, iml-wasm-components/iml-duration-picker/duration-picker.rs, iml-wasm-components/iml-fs/src/fs_detail_page.rs, iml-wasm-components/iml-stratagem/src/delete_stratagem_button.rs, iml-wasm-components/iml-stratagem/src/enable_stratagem_button.rs, iml-wasm-components/iml-stratagem/src/lib.rs, iml-wasm-components/iml-stratagem/src/scan_now.rs, iml-wasm-components/iml-stratagem/src/update_stratagem_button.rs
Fixes #1100.
Clicking the Enable / Update or Delete buttons within Stratagem config should show the command modal. This way the user can be notified of progress.
=> Enable / Update / Delete stratagem config should show command modal

iml-wasm-components/iml-duration-picker/duration-picker.rs, iml-wasm-components/iml-stratagem/src/lib.rs
Fixes #1146.
- Refreshing now loads the value and maintains the unit.
- Enable minutes and seconds as an option in the duration picker
=> Stratagem duration values need to load using the maximuim unit that doesn't have a remainder.

chroma_core/south_migrations/0044_auto__del_bundle__del_unique_bundle_bundle_name__add_repo__add_unique_.py
It will be dropped with the table.
Fixes #1087.
=> Skip removal of bundle_name index

grafana/dashboards/stratagem-dashboard-1.json
There may be cases where the variance between buckets is so large that the bars are basically invisible. By adding a legend we can see the values in these cases.
=> GH-1157 - Show legend for file-size and space distribution charts

Cargo.lock, chroma-manager.conf.template, chroma_core/lib/service_config.py, iml-mailbox/src/main.rs
Instead of having the iml-mailbox service
send the static files, we can have nginx
send them directly instead. This cuts out a step.
=> Serve mailbox files from Nginx directly

Cargo.lock, iml-agent/Cargo.toml, iml-agent/src/http_comms/crypto_client.rs, iml-agent/src/http_comms/mailbox_client.rs, iml-fs/Cargo.toml, iml-fs/src/lib.rs, iml-mailbox/Cargo.toml, iml-mailbox/src/lib.rs, iml-mailbox/src/main.rs, iml-manager-client/Cargo.toml
Fixes #1169.
The stream-lines dep appears to slow down consuming a line oriented stream
quite a bit. Replace it with rw-stream-sink which returns something that
implements AsyncRead. By doing this we can use the LineCodec from tokio,
which appears to have much better perf.
=> Remove stream-lines dep

chroma_core/lib/service_config.py, grafana/dropin-iml.conf, python-iml-manager.spec
This replaces the use of /etc/sysconfig/grafana to setup grafana config file, to ensure that when grafana is upgraded, we maintain the same config.
Fixes #1156 
=> Add systemd drop-in to override grafana ExecStart

chroma_core/models/stratagem.py, chroma_core/services/job_scheduler/job_scheduler.py, chroma_core/south_migrations/0046_auto__add_sendstratagemresultstoclientjob__add_stratagemconfiguration_.py, iml-wasm-components/iml-fs/src/fs_detail_page.rs, iml-wasm-components/iml-stratagem/src/lib.rs, iml-wasm-components/iml-stratagem/src/scan_now.rs
Fixes #1152.
The buttons for stratagem should be disabled based on any write lock associated with the stratagem configuration, or the fs.
=> Stratagem buttons should be disabled based on write locks

chroma_api/target.py, iml-wasm-components/iml-fs/src/fs_detail_page.rs
Fixes #1160.
Stratagem info: "Scan Filesystem Now", "Top inode Users", "File Size Distribution", ... is all shown in filesystem detail page, but there's no stratagem profiles or components installed on servers.
To Reproduce
Steps to reproduce the behavior:
1. Create filesystem in managed mode.
2. See Stratagem components
Expected behavior
No stratagem components
=> Stratagem GUI should be hidden if not available

Cargo.lock, Cargo.toml, iml-util/Cargo.toml, iml-util/util.rs
This crate will provide a place to add traits and other useful features.
This can come in handy when a feature is only enabled for nightly rust,
for example. Implementing a trait here in the utils crate provides
the ability to use features we may not otherwise have access to.
=> Create util crate

chroma_api/authentication.py, chroma_cli/api.py
The python manager cli currently is expecting a sessionid
for a non-logged in user.
In more recent versions of Django, a sessionid is not provided
until a user has logged in.
In addition, we should update the csrftoken header after logging in to
match the csrftoken value passed back.
=> Fixup python cli

ci/azure-test-pipeline.yml
So tests can pass until 2.12.3 is available.
=> Use copr-lustre to build

tests/integration/core/chroma_integration_testcase.py
Adding debug to pacemaker and restarting after host addition is done in
parallel, which may be causing issues.
Instead use a serial restart for each node and check that the return
code is 0.
=> Use serial try-restart of pacemaker

base_managed_patchless.profile
Since we reference 7.6 in zfs repo, we shouldn't try to install
on any other rev-level
=> Lock patchless profile to el7.6

chroma_core/lib/service_config.py
=> GH-1246 - Stop services during setup before restarting rabbitmq

chroma_agent_comms/views.py, chroma_core/models/host.py, chroma_core/models/server_profile.py, chroma_core/services/lustre_audit/update_scan.py
Define "base" packages in a single location (ServerProfile)
base packages are packages that are ALWAYS installed on a host.
Fixes #1264 
=> Centrally define base packages

chroma_api/stratagem.py
`StratagemConfigurationResource` has a duplicate method `dehydrate_interval`. Remove it.
=> Remove duplicate method

tests/integration/core/remote_operations.py, tests/integration/installation_and_upgrade/test_update_with_yum.py
Add travis CI test that parses the Requires from the IML spec and ensures there are no newer versions available than what is pinned. Haven't done too much research but you should be able to use rpmspec to read the spec file.
=> GH-1248 Add package-upgrade check

Cargo.lock, iml-manager-cli/Cargo.toml, iml-manager-cli/src/api_utils.rs, iml-manager-cli/src/display_utils.rs, iml-manager-cli/src/error.rs, iml-wasm-components/Cargo.lock
Add a new fn, `wait_for_cmds` that will wait for all commands to complete
before returning.
The fn will also display cmd state for each command and update the
display at each tick.
=> Add support to display command progress for multiple commands

iml-gunicorn.service, python-iml-manager.spec, wsgi.py
When (re)starting gunicorn, there are cases where the service is marked
as ready before it can accept connections. This leads to 502 errors.
Update the gunicorn service to use systemd notications to tell when it's
ready for requests.
=> Wait for gunicorn

iml-wasm-components/Cargo.lock, iml-wasm-components/iml-pie-chart/src/lib.rs
There are a few SVG styles that no longer work with seed 0.4.1 and cause
a panic at runtime.
They should to be Attrs instead.
=> Fixup SVG styles

.github/actions/copr-rust/action.yml, .github/workflows/devel-release.yml, .github/workflows/prod-release.yml, .github/workflows/rust-ci.yml, .github/workflows/wasm-ci.yml
With the new release of rust we can now compile all rust code using
stable instead of beta. Update all azure templates to use stable.
=> Revert to rust stable

iml-wasm-components/iml-fs/src/fs_detail_page.rs, iml-wasm-components/iml-fs/src/fs_page.rs
* GH-1285 Update Wasm Components with metric data as it is polled
Certain metric properties of the filesystems are not updated live in
iml-warp-drive and thus must be polled and set every x seconds. This
data will be passed to wasm-components where it will be updated on both
the filesystem and filesystem detail page.
* - temporarily move the PolledMetric type into both fs_detail_page and
fs_page until it is in wire-types (if we decide to go that route).
* - client count should take into account the number of mdt's
* - Rust beta updated to 1.40 and uses new format rules. Updating to
account for this.
Signed-off-by: Will Johnson …
=> Gh 1285 (#1308)

docker/iml-warp-drive.dockerfile
- Update version from 1.38 to 1.39.
=> Update rust version for iml-warp-drive

tests/integration/utils/test_blockdevices/test_blockdevice_zfs.py
so pools won't enter a suspended state.
=> Set ZFS params for EFS testing

chroma_core/lib/job.py, chroma_core/models/lnet_configuration.py, chroma_core/models/ntp.py, tests/unit/chroma_core/jobs/test_jobs.py
When configuring servers, I sometimes see a trace like:
```
File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 282, in run
self._run()
File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 306, in _run
self.job.id, step_klass=klass, args=clean_args, step_index=step_index, step_count=len(self.steps)
File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 209, in getter
self.put(deepcopy((name, args, kwargs)))
File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
y = copier(x, memo)
File "/usr/lib64/python2.7/copy.py", line 237, in _deepcopy_tuple
y.append(deepcopy(a, memo))
File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
y = copier(x, memo)
File …
```
=> Avoid passing host

iml-agent/src/action_plugins/check_kernel.rs, iml-agent/src/action_plugins/mod.rs, iml-agent/src/cli.rs
Will iterate all installed kernels (found via rpm -q),
and check for listed modules, and will return kernel, that
supports ALL modules.
Fixes Issue #1293
=> Find latest kernel that supports listed modules

Cargo.lock, iml-util/Cargo.toml, iml-util/util.rs
Add a new module, tokio_utils to the iml-util crate.
Within it, add three new fns to deal with incoming socket streams of
different types.
We should use these fns when we don't know which type of stream we will
be using at runtime.
=> Add tokio_utils

iml-manager-cli/src/api_utils.rs, iml-manager-cli/src/server.rs, iml-manager-cli/src/stratagem.rs, iml-manager-client/src/lib.rs
We are using `error_for_status` to cooerce any unsuccessful status codes
into an `Err`.
However, using this method discards the response body, which may have
useful information in terms of the actual issue with the request /
response.
As a start, this patch will remove `error_for_status` from the top-level
post call to let downstream consumers deal with the error directly.
=> Remove error_for_status call from POST

Cargo.lock, iml-services/iml-action-runner/Cargo.toml, iml-services/iml-action-runner/src/main.rs
The action runner is currently configured to run strictly on a unix
domain socket. This will prevent the docker service from running
correctly. If the proces is being run in systemd then the LISTEN_PID
environment variable will be set and the war server can be spawned with
the unix socket. If the LISTEN_PID environment variable is not defined
it will instead launch the warp server over http (used in docker).
=> Support both unix socket and TCP communication in the action runner

iml-gui/crate/src/components/font_awesome.rs, iml-gui/crate/src/components/mod.rs
Add a new fn that can render a given font-awesome icon.
This fn will use the svg sprite sheet for rendering rather then CSS.
In addition, any attributes (classes, styles, etc...) can be passed in
as a param.
=> Add font-awesome componet

iml-gui/crate/LICENSE, iml-gui/crate/src/components/arrow.rs, iml-gui/crate/src/components/mod.rs, iml-gui/crate/src/components/popover.rs, iml-gui/crate/src/components/tooltip.rs
Implement a popover component in seed.
In addition, split out the arrow on the tooltip and popover which uses
common code to it's own file.
=> Implement popover

Cargo.lock, iml-agent/Cargo.toml, iml-agent/src/action_plugins/action_plugin.rs, iml-agent/src/action_plugins/mod.rs, iml-agent/src/daemon_plugins/action_runner.rs, iml-util/Cargo.toml, iml-util/util.rs
Extract the action plugin concept into iml_utils so it can be shared
between crates that run on the agent and the manager.
=> Extract Action plugin concept

Cargo.lock, chroma_core/lib/job.py, chroma_core/lib/util.py, chroma_core/models/host.py, chroma_core/services/job_scheduler/agent_rpc.py, iml-services/iml-action-runner/src/data.rs, iml-services/iml-action-runner/src/error.rs, iml-services/iml-action-runner/src/lib.rs, iml-services/iml-action-runner/src/local_actions.rs, iml-services/iml-action-runner/src/main.rs, iml-services/iml-action-runner/src/receiver.rs, iml-services/iml-action-runner/src/sender.rs, iml-services/iml-action-runner/tests/action_runner_tests.rs, tests/unit/chroma_core/lib/test_util.py
This patch adds a way to run any sort of Rust code as part of a step
within the manager.
From the Python side, two new methods are exposed that can be called
within a step:
`invoke_rust_local_action` and `invoke_rust_local_action_expect_result`.
They work basically the same as their remote counterparts:
`invoke_rust_agent` and `invoke_rust_agent_expect_result`
Except they run the plugins on the manager and don't require a fqdn to
route the call to.
The first two plugins deal with getting the current session and waiting
for a new session, but future plugins can basically be anything.
COPR Module Manager: managerforlustre/rust-local-plugins
=> Add local action plugins

iml-gui/crate/src/lib.rs, iml-gui/crate/src/page/home.rs, iml-gui/crate/src/page/partial/header.rs, iml-gui/crate/src/page/server_detail.rs, iml-gui/crate/src/route.rs
This patch enables us to use a route that contains data (meaning a route
enum variant can now carry some data).
This enables detail pages where we need to include an id in the route.
In addition, this patch renames `Page` enum to `Route`, which seems like
a better name, and extracts it to it's own file.
=> Enable detail routing

Cargo.lock, iml-agent-comms/src/messaging.rs, iml-rabbit/Cargo.toml, iml-rabbit/src/lib.rs, iml-services/iml-service-queue/src/service_queue.rs, iml-warp-drive/src/locks.rs
This patch ensures that service queues are purged when restarting.
It also removes the exclusive consumer flag, and adds a
single-active-consumer arg that will enforce a single consumer once we
start using rabbit 3.8.
=> Purge service queues when restarting

iml-gui/crate/src/components/breadcrumbs.rs, iml-gui/crate/src/lib.rs
The breacrumbs were merged after bab14f6989cd2d8ceec7b8cdee26f20040ae68dd
and thus would not compile.
In addition use explicit .clone() because the Route type no longer
implements Copy.
=> Fix breadcrumbs for new routing

settings.py
Fixes #1384.
The docker setup currently sets the ntp server to be the job scheduler. This is an issue because the server nodes will not be able to use the job scheduler as a time manager.
=> GH-1384 Setup NTP Storage Servers for Docker

iml-manager-cli/src/api_utils.rs, iml-manager-cli/src/display_utils.rs
Report error if cmd is "errored".
Command.complete is only set if commanded has completed, does not
indicate success.
=> IML CLI: Fix cmd error state

iml-agent/src/poller.rs, iml-agent/src/reader.rs
The intent is to have clean compilation to easily spot newly introduced warnings.
With `poller`, the behavior stays the same, since it's unclear how to fix the warnings w/o silencing them.
=> Fix or silence warnings in iml-agent

iml-gui/crate/rustfmt.toml
This is to make rustfmt understand async/.await (and other modern things) when running in Vim with rust.vim. Ref.: https://github.com/rust-lang/rust.vim/issues/368
=> Add edition to rustfmt.toml

iml-agent/src/action_plugins/action_plugin.rs, iml-agent/src/action_plugins/kernel_module.rs, iml-agent/src/action_plugins/mod.rs, iml-agent/src/cli.rs
This is another shot at point 3 of https://github.com/whamcloud/integrated-manager-for-lustre/issues/1187#issuecomment-559830336
Contrary to https://github.com/whamcloud/integrated-manager-for-lustre/pull/1371 this doesn't bind to native libraries and parses output of `lsmod`.
=> Implement checking of loaded kernel modules

iml-agent/Cargo.toml, iml-fs/Cargo.toml, iml-manager-cli/Cargo.toml, iml-rabbit/Cargo.toml, iml-util/Cargo.toml
So that individual crates can be built.
I suppose that when building the entire workspace cargo chooses the most
wide set of features and use it to build all members. And thus some crates
are buildable by accident, but they should list their dependencies explicitly.
=> Fix dependencies of subcrates

iml-wire-types/wire-types.rs
Implement `Label` for a few more wire-types and for borrowed versions.
This will allow us to generically refer to `Label` during usage.
=> Implement Label for some more wire-types.

iml-fs/src/lib.rs, iml-util/util.rs
`Option::flatten` is now stable on Rust 1.40. We can remove our custom
trait for it.
=> Remove Flatten Trait

iml-wasm-components/Cargo.lock
Rust is now at 1.40. Wasm-bindgen has also updated so the binary must
match the wasm file.
=> Update deps in wasm components

iml-mailbox/src/lib.rs
Fixes #1409
Call
https://docs.rs/tokio/0.2.6/tokio/io/trait.AsyncWriteExt.html#method.flush
after `write_all` which apparently is required to ensure all bytes have
been written to the file.
=> Flush after write-all in mailbox

iml-agent/src/action_plugins/action_plugin.rs, iml-agent/src/action_plugins/lpurge.rs, iml-agent/src/action_plugins/mod.rs, iml-agent/src/action_plugins/snapshots/lpurge_conf_tests__works.snap, iml-agent/src/cli.rs
Fixes #1381 
```
$ ../target/debug/iml-agent lpurge --help
iml-agent-lpurge 0.1.0
IML Team <iml@whamcloud.com>
Write lpurge configuration file
USAGE:
iml-agent lpurge --freehi <freehi> --freelo <freelo> --fs <fs> --ost <ost> --pool <pool>
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
--freehi <freehi>    
--freelo <freelo>    
--fs <fs>            Filesystem name
--ost <ost>          Object Storage Target name
--pool <pool>        OST pool name
```
```
$ ../target/debug/iml-agent lpurge --freehi 23 --freelo 56 --fs foo --ost bar --pool xxx
Permission denied (os error 13)
$ sudo ../target/debug/iml-agent lpurge --freehi 23 --freelo 56 --fs foo --ost bar --pool xxx
$ cat /etc/lpurge/bar.conf 
device=foo-bar
dryrun=true
freehi=23 …
```
=> Create `create_lpurge_conf` action plugin

iml-gui/crate/Cargo.lock, iml-gui/crate/Cargo.toml, iml-gui/crate/src/components/activity_indicator.rs, iml-gui/crate/src/components/font_awesome.rs, iml-gui/crate/src/components/tooltip.rs, iml-gui/crate/src/lib.rs, iml-gui/crate/src/notification.rs, iml-gui/crate/src/page/partial/header.rs, iml-gui/static/notification.sw.js
Closes #1363.
The logic is built around activity health. When the health worsens, a notification will be shown. When the health gets better a notification will be updated if shown, otherwise nothing will happen.  In a special case when no alert remains, a notification will be closed. When an alert that caused change of the health is known, details of such alert will be shown.
Implementation makes use of a Service Worker, because this is the only way to get a list of exiting notifications even after the page reloads, closes and opens.
Update seed because of futures.
Update js_sys because of Array.to_vec().
Demonstration:
=> Use browser notification API to show alerts

Cargo.lock, iml-gui/crate/Cargo.lock, iml-gui/crate/Cargo.toml, iml-gui/crate/src/components/activity_indicator.rs, iml-gui/crate/src/lib.rs, iml-gui/crate/src/notification.rs, iml-postgres/Cargo.toml, iml-warp-drive/Cargo.toml, iml-warp-drive/src/cache.rs, iml-warp-drive/src/locks.rs, iml-warp-drive/src/main.rs, iml-warp-drive/src/users.rs, iml-wasm-components/Cargo.lock, iml-wire-types/Cargo.toml, iml-wire-types/wire-types.rs
Fixes #1439.
The [`Cache`](https://github.com/whamcloud/integrated-manager-for-lustre/blob/8352ad767ff7c156168130413b8a91f547650411/iml-wire-types/wire-types.rs#L1982-L1995) is shared between `warp-drive` and `iml-gui` and serves as a way to send a fully populated dataset and then updates afterwards.
It is somewhat difficult to work with within the `iml-gui` seed app, as storing the relevant cache portion to a sub-component's model either means cloning (which is expensive at scale), or passing in a unique id to be stored (`id` in most cases) that implements `Copy`.
Using the later approach is non-trivial to implement, as the sub-component needs to locate the corresponding record by id before using / updating it in the model or view.
Another approach we can take is to use an immutable …
=> Use immutable data structures for warp-drive `Cache`

Cargo.lock, iml-gui/crate/Makefile.toml, iml-gui/crate/src/components/mod.rs, iml-gui/crate/src/components/table.rs
Fixes #1446.
Add new table component that implements look and feel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1447)
=> Add Table component

.gitignore, base.dockerfile.dockerignore, vagrant/.gitignore, vagrant/README.md, vagrant/Vagrantfile, vagrant/scripts/bootstrap_iscsi.sh, vagrant/scripts/configure_lustre_network.sh, vagrant/scripts/create_ldiskfs_fs_osts.sh, vagrant/scripts/deploy_hosts.sh, vagrant/scripts/disable_selinux.sh, vagrant/scripts/install_iml.sh, vagrant/scripts/install_iml_local.sh, vagrant/scripts/install_iml_tar.sh, vagrant/scripts/install_ldiskfs_no_iml.sh, vagrant/scripts/install_zfs_no_iml.sh, vagrant/scripts/key_config.sh, vagrant/scripts/load-diagnostics-db.sh, vagrant/scripts/use_vault.sh, vagrant/scripts/zfs_params.sh
Take the repo from https://github.com/whamcloud/Vagrantfiles and plop it
into `integrated-manager-for-lustre/vagrant`.
This will replace https://github.com/whamcloud/Vagrantfiles which will
be marked as deprecated.
Co-locating this repo is the first step of using it to run automated
testing instead of vagrant-libvirt which has been flakey and largely
unmaintained upstream.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1451)
=> Move Vagrantfiles repo into IML repo

iml-gui/crate/src/lib.rs
We currently remove a record inline, but send a message to child
components when one is removed.
We expect the child components to be able to access the record in the
cache before it's deleted, however the child message is async and
happens after the inline delete is processed.
Add a new Msg variant to remove the record. By doing this, we ensure the
remove is scheduled after the chilren can process the delete.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1452)
=> Use a separate order to remove a record

chroma_core/models/filesystem.py
Remove the `.save()` from the main model for `AddOstPoolJob` and
`RemoveOstPoolJob`.
This was causing an extra commit in the db on the main model, which
doesn't have any direct fk fields to the ost pool osts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1456)
=> Remove extra save from RemoveOstPoolJob and AddOstPoolJob

.copr/Makefile, rust-iml.spec
Also allow "make all" to work from non-docker builder
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1481)
=> Fix rpm build

Makefile, vagrant/scripts/install_iml_local.sh, vagrant/scripts/install_iml_local_agent.sh
Fixes #1483.
These changes should ensure the locally built packages get chosen (within a comparable range).
It also enables reinstall capabilities.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1484)
=> Fix: install-iml-local provisioner agent packages are overwritten

iml-agent/src/daemon_plugins/postoffice.rs
This is first part of #1479.
We could also use [`tokio::task::block_in_place`](https://docs.rs/tokio/0.2.9/tokio/task/fn.block_in_place.html) instead of [`futures::executor::block_on`](https://docs.rs/futures/0.3.1/futures/executor/fn.block_on.html) but that would require two features (`rt-threaded` and `blocking`) and it has less convenient API where you need to pass a closure returning a result. `async` closures are even unstable.
This PR improves code by making everything except `teardown` and `Debug::fmt` async. Making `teardown` async is not really viable IMO, as the future needs to outlive the data it refers to, and for teardown, it doesn't seem to make sense. With `fmt`, we're stuck with `std` signature where we can't sneak anything in or out.
Signed-off-by: Michael Pankov …
=> Replace parking_lot::Mutex in postoffice

chroma_api/alert.py
The `/api/alert_type` endpoint was returning multiple copies of
`AlertStateBase`.
This is because we weren't accounting for proxy objects when looking up
the content type.
Pass in `False` to looking up the proxy model correctly.
ref: https://docs.djangoproject.com/en/1.11/ref/contrib/contenttypes/#django.contrib.contenttypes.models.ContentTypeManager.get_for_model
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1503)
=> Fixup alert type endpoint

.copr/Makefile, Cargo.lock, Cargo.toml, docker/docker-compose.override.yml, docker/docker-compose.yml, docker/iml-postoffice.dockerfile, iml-manager.target, iml-postoffice.service, iml-services/iml-postoffice/Cargo.toml, iml-services/iml-postoffice/src/main.rs, python-iml-manager.spec, rust-iml.spec, vagrant/scripts/install_iml_local.sh
Fixes #1504.
After installing a new local RPM based installation of IML I added two MDS nodes that had been configured in monitored mode and noticed that the manager was receiving disconnects every few seconds. Looking into the logs, I discovered the following error message:
```
session create request for postoffice failed: Reqwest(reqwest::Error { kind: Status(502), url: "https://adm.local/agent2/message/" })
Jan 21 16:07:16 mds1.local iml-agent-daemon[8147]: Jan 21 16:07:16.529  INFO iml_agent::poller: session create request for ostpool failed: Reqwest(reqwest::Error { kind: Status(502), url: "https://adm.local/agent2/message/" })
Jan 21 16:07:16 mds1.local iml-agent-daemon[8147]: Jan 21 16:07:16.530  INFO iml_agent::poller: session create request for stratagem failed: …
```
=> GH-1504 Create post office manager plugin

chroma-manager.conf.template, chroma_core/lib/service_config.py, docker/docker-compose.yml, docker/grafana.dockerfile, docker/grafana/setup-grafana, docker/grafana/setup-grafana.sh, docker/setup-nginx, grafana/datasources/influxdb-iml-datasource.yml, python-iml-manager.spec, settings.py
Fixes #1388 
Grafana is currently only setup to run using a manager node. This is very restrictive and will not work on certain setups. In an effort to support systems without a management node, docker support should be added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1401)
=> Integrate grafana into docker stack

iml-gui/crate/src/breakpoints.rs, iml-gui/crate/src/lib.rs, iml-gui/crate/src/page/partial/header.rs
Add a new module that will track current breakpoint size via the window resize event.
This can be used to handle responsive rendering changes in Rust code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1519)
=> Add media breakpoint tracking

chroma_core/models/host.py, chroma_core/models/target.py, tests/unit/services/job_scheduler/host/test_host.py
Fixes #1523.
`replace_nids` is currently using the mgs nids for every target.
Instead we should use the most relevant target nids for the operation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1524)
=> Use target host nids instead of mgs nids

.github/workflows/rust-ci.yml, .github/workflows/wasm-ci.yml, README.md
This patch archives the artifacts of building RPMS using github actions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1527)
=> Archive RPM build results

vagrant/Vagrantfile
Client vm's are not able to be added to the server page when using
docker because they do not contain the "configure_docker_network"
provisioning script. Add this ability to the client vm's.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1531)
=> Allow Client vm's to be configured for docker networking

Vagrantfile
With new provisioning we want to ssh to host as root,
however we are currently using `Etc.getlogin` which returns the
login user instead of the current one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1532)
=> Use current user instead of login user

docker/systemd-base.dockerfile
Both the iml-timer and iml-mailbox docker containers are based on
systemd. Create a base systemd dockerfile that can be used as a base
when creating systemd-based containers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1533)
=> Create a base systemd dockerfile

tests/integration/utils/chroma_log_collector.py
Try to work around Jenkins archive step hanging by never expanding the
sosreports.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1542)
=> Keep sosreports in archive format

tests/framework/integration/installation_and_upgrade/run_tests
Try to collect xml reports in upgrade tests the way we do in other
testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1544)
=> Try to collect reports in upgrade tests

chroma_core/lib/stratagem.py
The aggregate_points function assumes that the series will always be in
the influxdb results. I ran into a case in which the series was not in
the results. We should check to make sure that series is not empty
before attempting to get the values and columns from it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1556)
=> Add Series Check to Stragem Library

vagrant/Vagrantfile
Even though it's not available on vagrant cloud yet, we can pull the
newest CentOS 7 Vbox directly from cloud.centos.org.
This should allow for us to skip updating the kernel on each vm before
installing Lustre.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1559)
=> Update to newer Vagrantfile

iml-gui/configs/tailwind.config.js, iml-gui/configs/webpack.config.js, iml-gui/crate/src/components/lock_indicator.rs, iml-gui/crate/src/components/popover.rs, iml-gui/crate/src/generated/css_classes.rs
Use `:focus-within` pseudo-class to show a popover.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1538)
=> Add lock indicator component

docker/Makefile, docker/base.dockerfile, docker/iml-mailbox.dockerfile, docker/rust-base.dockerfile, docker/systemd-base.dockerfile
Use Centos:7 for rust-base and systemd-base.
This will remove the Centos:8 image from being bundled and should
hopefully save a few hundred MBs in the final RPM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1565)
=> Use Centos:7 for rust-base and systemd-base

vagrant/scripts/install_iml_local.sh
Previously it wouldn't update the toolchain - my setup still had 1.40 because of it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1570)
=> Call rustup update after loading environment

vagrant/Vagrantfile
Caused errors where incorrect SRPMs would be processed during `install-iml-local`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1594)
=> Prevent mixing _topdir from host and adm

chroma_core/lib/detection.py, chroma_core/models/filesystem.py, chroma_core/models/target.py
Allow forgetting managed filesystems
Only require pacemaker config to be started if it exists for targets
Issue #1498
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1569)
=> Detect ha filesystems

Cargo.lock, iml-agent-comms/Cargo.toml, iml-agent-comms/src/main.rs, iml-agent-comms/src/messaging.rs, iml-agent/Cargo.toml, iml-api/Cargo.toml, iml-api/src/action.rs, iml-api/src/main.rs, iml-job-scheduler-rpc/src/lib.rs, iml-rabbit/Cargo.toml, iml-rabbit/src/lib.rs, iml-services/iml-action-runner/Cargo.toml, iml-services/iml-action-runner/src/main.rs, iml-services/iml-action-runner/src/receiver.rs, iml-services/iml-action-runner/src/sender.rs, iml-services/iml-action-runner/tests/action_runner_tests.rs, iml-services/iml-service-queue/src/service_queue.rs, iml-warp-drive/src/locks.rs
The lapin crate provides futures 03 compatibility behind a feature.
Switch to using lapin instead of lapin-futures which was futures 01 based
and need compatibility shims.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1601)
=> Use lapin instead of lapin-futures

iml-docker.service, iml-docker.spec
Instead, attempt to load them when starting the iml-docker.service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1602)
=> Do not load docker images in RPM %post block

.github/workflows/devel-release.yml
The rust-iml-gui deploy job is missing the correct `SRPM_TASK`.
Add it in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1611)
=> Fixup iml-gui deploy

iml-gui/crate/src/components/action_dropdown/mod.rs, iml-wire-types/src/warp_drive.rs
`Arc` already allows storing unsized objects in it.
Remove additional boxing so we avoid extra allocation and indirection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1615)
=> Remove extra layer of boxing

Cargo.lock, chroma_api/alert.py, iml-gui/crate/src/components/alert_indicator.rs, iml-gui/crate/src/page/filesystem.rs, iml-gui/crate/src/page/servers.rs, iml-wire-types/src/db.rs, iml-wire-types/src/lib.rs
It's easier to lookup alerts by composite ids than resource uris,
especially when fetching them from active alerts.
Update alert_indicator to take anything that implements
`ToCompositeId`, and update the /alert endpoint
to return the composite ids of effected items.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1612)
=> Update alert_indicator to take composite ids

chroma_api/stratagem.py
Update stratagem api validation so it checks `exascaler_server` profile
as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1634)
=> Update stratagem api validation

.github/workflows/iml-gui.yml, docker/iml-gui.dockerfile
Due to breaking change in a patch bump of the `quote` crate,
wasm-pack doesn't compile.
Switch to using precompiled binaries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1655)
=> Fixup wasm-pack install

iml-gui/crate/src/components/progress_circle.rs
If the progress circle receives a NaN value in `used_to_color` it will
crash the application. We should make sure the used value isn't NaN
before attempting to round the value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1658)
=> Fix NaN case in progress circle

iml-gui/crate/src/components/grafana_chart.rs
This will prevent "i" box from showing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1670)
=> Make grafana graphs "kiosk" mode

chroma_core/management/commands/print-settings.py, iml-api/src/main.rs, iml-gui/crate/src/lib.rs, iml-gui/crate/src/page/filesystem.rs, iml-gui/crate/src/page/login.rs, iml-gui/crate/src/page/partial/header.rs, iml-manager-env/src/lib.rs, iml-wire-types/src/lib.rs, settings.py
Add ability to include a config file in `/etc/iml-docker/setup/config`. This config should (at least for now) allow the installer to include: `BRANDING` and `STRATRAGEM_ENABLED`. These values will be loaded into environment variables along with the rest of the variables specified in `print-settings.py`. The gui app will additionally wait for these values to be loaded before the gui is loaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1687)
=> Api config

iml-gui/crate/src/components/resource_links.rs, iml-gui/crate/src/components/tree.rs, iml-gui/crate/src/page/volumes.rs
- remove link from volumes on filesystem detail, mgt, individual volumes in tree view
- Remove OST pools parent link in tree view
- Remove Target parent links (except MGT)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1693)
=> Remove volume links and other tree-view links that do not need to be shown

chroma-manager.conf.template, grafana/grafana-iml.ini
Let influx and grafana gzip their own data and pass that
through nginx.
Issue #1589
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1698)
=> Have nginx pass proxied gzip data from grafana and influx

iml-gui/crate/src/components/dashboard/mod.rs, iml-gui/crate/src/components/grafana_chart.rs, iml-gui/crate/src/components/stratagem/mod.rs, iml-gui/crate/src/page/dashboard.rs, iml-gui/crate/src/page/fs_dashboard.rs, iml-gui/crate/src/page/server_dashboard.rs, iml-gui/crate/src/page/target_dashboard.rs
The grafana charts are not updating. This is because the `var-` prefix
that was being automatically injected by serde was removed (to allow for
the `from` and `to` parameters). This patch updates the stratagem
charts to use the `create_chart_params` function instead of passing a
struct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1706)
=> Fix grafana charts

iml-gui/crate/src/page/filesystem.rs, iml-gui/crate/src/status_section.rs
Fixes #1708.
Description:
There are a couple of gui bugs that need immediate fixing:
- The right panel does not display properly in reponsive mode. For now, we should remove the right panel unless we are in a large view.
- The volume table cell is rendering as a single column of text when the window is scaled down. We should fix the volume cell and also remove both the primary and failover server columns unless the browser is open in a medium view or larger.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1709)
=> Address immediate GUI visual bugs

iml-gui/crate/src/components/breadcrumbs.rs, iml-gui/crate/src/lib.rs, iml-gui/crate/src/page/mod.rs, iml-gui/crate/src/page/partial/header.rs, iml-gui/crate/src/route.rs
Derive page title from the page's model rather
than from the route. Closes #1577.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1707)
=> Show page details in title and in breadcrumbs

Cargo.lock, agent-bootstrap-script.template, default_baseless.profile, iml-manager-cli/src/api_utils.rs, iml-manager-cli/src/error.rs, iml-manager-cli/src/filesystem.rs, iml-manager-cli/src/ostpool.rs, iml-manager-cli/src/server.rs, iml-manager-cli/src/update_repo_file.rs, iml-warp-drive/src/cache.rs, iml-warp-drive/src/main.rs
Fixes #1710
Add a new default (phase 1) profile called default_baseless.
It has no base repos and is used iff the server_profile (phase 2)
has no base repos as well.
In addition add a list endpoint for server profiles.
- Add `default_baseless.profile`
- Update bootstrap to not create repo or install agent if generated
repofile is empty
- Ensure iml cli returns correct error codes when commands fail.
- Ensure iml cli returns error when there are no hosts to add.
- Add some more debug to warp-drive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1711)
=> Add baseless profile

iml-manager-cli/src/api_utils.rs, iml-manager-cli/src/filesystem.rs, iml-manager-cli/src/ostpool.rs, iml-manager-cli/src/server.rs, iml-manager-cli/src/update_repo_file.rs
Fixes #1720.
The wait_for_cmds fn does not return the final command fetched, but
instead returns the original list of commands back.
When checking for final command state, we need the list generated on the
final tick.
Return the final command state from the fn.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1721)
=> wait_for_cmds fn does not return final command

iml-gui/crate/src/components/tree.rs, iml-gui/crate/src/lib.rs, iml-gui/crate/src/page/mod.rs, iml-gui/crate/src/page/volumes.rs, iml-gui/crate/src/route.rs
The route is `/servers/<server-id>/volumes`.
It opens a page listing the volumes on the specified server.
Closes #1688.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1713)
=> Add route to show per-host volumes

iml-warp-drive/Cargo.toml, iml-warp-drive/src/cache.rs
Fixes #1726.
Update the cache to use serial queries instead of being run in parallel.
This will hopefully prevent the service from hanging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1727)
=> Fix warp drive hanging

iml-agent/src/env.rs
Ensure we always generate the identity.pfx on rust agent startup to
avoid stale auth.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1730)
=> Always generate identity.pfx on rust agent startup

chroma_api/stratagem.py, chroma_core/models/stratagem.py, chroma_core/services/job_scheduler/job_scheduler.py
Fixes #1743.
Description:
Currently, stratagem verifies that the stratagem_client profile is installed on the client. We also have the stratagem_existing_client profile, which is also valid. This code should be updated to allow for either client to be installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1744)
=> Allow NTP to use the `stratagem_existing_client`

iml-gui/crate/src/page/filesystem.rs
- Update filesystem page to use correct label.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1747)
=> Change `MGTs` to `MDTs` on filesystem page

iml-gui/crate/src/page/filesystem.rs, iml-gui/crate/src/page/filesystems.rs
The queries were returning "null" for the number of connected clients.
Closes #1738.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1754)
=> Fix influx queries for FS stats

vagrant/README.md, vagrant/Vagrantfile, vagrant/scripts/create_ldiskfs_fs_osts.sh, vagrant/scripts/create_ldiskfs_lvm_fs.sh, vagrant/scripts/create_ldiskfs_lvm_mds_ha_setup.sh, vagrant/scripts/create_ldiskfs_lvm_oss_ha_setup.sh, vagrant/scripts/install_ldiskfs_no_iml.sh
Add provisioners to create MDT and MGT on LVMs
To create an ES-like system provision with the following steps:
create-ldiskfs-lvm-fs
ha-ldiskfs-lvm-fs-step1
ha-ldiskfs-lvm-fs-step2
Set lustre version to 2.12.4
Add documentation to README.md
Fixes #1746
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1751)
=> Vagrant: Add ldiskfs-lvm-fs provisioners

iml-system-tests/Cargo.lock, iml-system-tests/tests/vagrant.rs, vagrant/README.md, vagrant/Vagrantfile, vagrant/scripts/install_iml_repouri.sh
Add a new provisioner that will allow provisioning via a passed in
REPO_URI environment variable.
`vagrant provision --provision-with=install-iml-repouri`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1753)
=> Add repouri provisioner

docker/iml-gui.dockerfile, iml-gui/crate/Cargo.lock
The iml-gui docker image has started hitting
https://github.com/yarnpkg/yarn/issues/3189.
Make sure we update after adding the yarn source to avoid this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1769)
=> Fix docker GUI build

iml-gui/crate/src/components/breadcrumbs.rs, iml-gui/crate/src/lib.rs, iml-gui/crate/src/page/mod.rs, iml-gui/crate/src/page/user.rs
In general: update the current breadcrumb whenever the current page's title
changes.
In particular: when the user is updated, update the user page's title
Closes: #1734.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1739)
=> Update page title & breadcrumb with user

chroma_core/lib/detection.py
Fixup failed lv detection to print out lv uuid instead of missing var.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1776)
=> Fix detection logging

chroma_core/lib/service_config.py, docker/docker-compose.yml, docker/python-service-base.dockerfile, iml-job-scheduler.service, iml-manager.target, iml-settings-populator.service, python-iml-manager.spec, tests/framework/chroma_support.repo.in, tests/framework/services/runner.sh.in, tests/integration/core/api_testcase_with_test_reset.py, vagrant/scripts/install_iml_local.sh, vagrant/scripts/install_iml_repouri.sh
Update the RPM and docker installs to use postgres 9.6 instead of 9.2.
9.6 has improved JSON support and `INSERT ... ON CONFLICT DO NOTHING/UPDATE` support,
both of which are useful for upcoming features.
See https://www.postgresql.org/about/featurematrix/ for a more complete
comparision.
Centos 8 provides 9.6 in the appstream repo which should make migration
simpler as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1781)
=> Use postgres 9.6 instead of 9.2

iml-gui/crate/Cargo.lock, iml-gui/crate/src/lib.rs
When an alert is lowered it is not reflected in the IML GUI.
This is because we need to call `update_activity_health` in the
`Msg::RemoveRecord` variant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1789)
=> Lower Active alerts

docker/docker-compose.yml
Due to https://github.com/docker-library/postgres/issues/681, we need to
add `- POSTGRES_HOST_AUTH_METHOD=trust` to the docker-compose.yml.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1799)
=> Add POSTGRES_HOST_AUTH_METHOD environment var

iml-manager-cli/src/display_utils.rs
**Before:**
```
+------+-----------+------------------+---------+---------+------+------+
| Name | State     | Space            | Inodes  | Clients | MDTs | OSTs |
+------+-----------+------------------+---------+---------+------+------+
| fs   | available | 333 MiB / 46 GiB | 3K / 3M | 0       | 2    | 10   |
+------+-----------+------------------+---------+---------+------+------+
| fs2  | available | 332 MiB / 46 GiB | 3K / 3M | 0       | 1    | 10   |
+------+-----------+------------------+---------+---------+------+------+
```
**After:**
```
+------+-----------+------------------+---------+---------+------+------+
| Name | State     | Space            | Inodes  | Clients | MDTs | OSTs |
+======+===========+==================+=========+=========+======+======+
| fs   | available | 333 …
```
=> Use table titles in CLI

iml-gui/crate/src/components/action_dropdown/mod.rs, iml-gui/crate/src/page/partial/header.rs, iml-gui/crate/src/status_section.rs
50 - Modals
40 - Menu
30 - Side panel with alerts and logs
20 - Tooltips
10 - Popovers and dropdowns
0 - anything else (header, footer, main panels, etc.)
Closes #1748.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1786)
=> Fix z-index

docker/docker-compose.yml
The restart policy needs to be changed from `on-failure` to `any`.
`Setup` is an exception and should continue to have a restart policy of
`on-failure`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1811)
=> Update deploy restart policy

rust-iml.spec
The `rust-iml-agent` package provides the functionallity that
`iml-device-scanner-proxy` did.
Require newest `device-scanner` and obsolete `iml-device-scanner-proxy`
going forward.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1795)
=> Obsolete device-scanner-proxy

Cargo.lock, iml-fs/src/lib.rs, iml-manager-cli/Cargo.toml, iml-manager-cli/src/error.rs, iml-manager-cli/src/lib.rs, iml-manager-cli/src/profile.rs, iml-manager-cli/src/server.rs, iml-orm/src/lib.rs, iml-orm/src/models.rs, iml-orm/src/profile.rs, iml-orm/src/repo.rs
Add a new CLI command that will enable server profiles to be
loaded / removed post initial setup.
general format is:
```sh
cat profile.json > iml server profile load
```
and 
```sh
iml server profile remove <name>
```
Fixes #1680.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1821)
=> Add CLI commands for loading / removing profiles

iml-system-test-utils/src/vagrant.rs
The upgrade to 7.8 in the integration test causes the
lustre installation to fail. Do not upgrade the nodes in the integration
test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1837)
=> - Updating the vm's is causing CentOS to upgrade

iml-system-test-utils/src/lib.rs, iml-system-test-utils/src/ssh.rs, vagrant/scripts/create_iml_diagnostics.sh
sosreport should be run after every integration test. In addition, it
should be changed from `iml-diagnostics` to `sosreport --batch`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1840)
=> Always run sosreport at the end of any integration test

iml-settings-populator.service
The iml-settings file should be generated in a way that is atomic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1847)
=> Make settings populator call atomic

iml-gui/crate/src/page/activity.rs
When a command is active we should be able to click the button in the
activity sidebar to see it's status.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1856)
=> Always show the command_details button for commands

lustre-client-mlnx.repo, lustre-client.repo, lustre-server-mlnx.repo, lustre-server-patchless.repo, lustre-server.repo
Also set $releasever in place of 7 in most places.
Patchless still NEEDS to be 7, because of ZFS 0.7.x only tracked on 7.6 kmod.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1866)
=> Update Lustre to 2.12.4

iml-services/iml-service-queue/src/service_queue.rs
**BEFORE::**
```
DEBUG iml_service_queue::service_queue: Incoming message: [123, 34, 116, 121, 112, 101, 34, 58, 34, 83, 69, 83, 83, 73, 79, 78, 95, 67, 82, 69, 65, 84, 69, 34, 44, 34, 102, 113, 100, 110, 34, 58, 34, 111, 115, 115, 49, 46, 108, 111, 99, 97, 108, 34, 44, 34, 112, 108, 117, 103, 105, 110, 34, 58, 34, 100, 101, 118, 105, 99, 101, 34, 44, 34, 115, 101, 115, 115, 105, 111, 110, 95, 105, 100, 34, 58, 34, 54, 100, 52, 51, 98, 48, 48, 99, 45, 100, 54, 56, 53, 45, 52, 98, 55, 50, 45, 57, 99, 57, 50, 45, 53, 100, 49, 54, 100, 53, 99, 48, 99, 56, 99, 99, 34, 125]
```
**AFTER::**
```
DEBUG iml_service_queue::service_queue: Incoming message: {"type":"SESSION_CREATE","fqdn":"oss1.local","plugin":"device","session_id":"56973095-4bdc-490c-a6fe-16706531d580"}
```
Signed-off-by: Igor …
=> Service Queue: print debug string instead of vec

chroma_core/models/target.py
Ensure we select the target mount matching the failover node
instead of just assuming there is a single one.
Fixes #1884.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1885)
=> Fix target failover

Cargo.lock, iml-manager-cli/src/profile.rs, iml-orm/Cargo.toml, iml-orm/src/alerts.rs, iml-orm/src/lib.rs, iml-orm/src/profile.rs, iml-services/iml-ntp/src/main.rs
Add a new trait `Executable` that can be used as a return for Insert (Upsert)
statements.
This trait allows the execution of the insert to be decoupled from the
actual statement, which means the statements can be reused in both
transactional / non-transactional contexts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1889)
=> Add `Executable` trait to iml-orm

iml-services/iml-action-runner/src/data.rs, iml-services/iml-action-runner/src/sender.rs
The `iml-action-runner` service will put a new message onto the queue
before adding it to the internal bookkeeping table of RPCs in flight.
This opens the very small possibility that the RPC can complete before
the action runner can add it to the internal RPC table.
When this occurs, the RPC is never resolved to the caller and ends up
hanging since it looks like like an unknown response to the
action-runner.
Fixes #1870.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1894)
=> Race between agent and manager to resolve action

.copr/Makefile, vagrant/scripts/install_iml_local.sh
Bring down `install-iml-local` with hot no-op rebuild to ~4 minutes instead of ~13 minutes.
Fixes #1873 
Fixes #1880
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1881)
=> Optimize local builds

Cargo.lock, iml-api/Cargo.toml, iml-api/src/error.rs, iml-api/src/main.rs, iml-manager-cli/src/error.rs, iml-orm/Cargo.toml, iml-orm/src/fidtaskqueue.rs, iml-orm/src/job.rs, iml-orm/src/lib.rs
Extract the warp pool filter to the iml-orm crate and put behind a
feature flag.
This way, we can use the filter in other crates that need a db pool
connection per request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1904)
=> Extract the pool filter to iml-orm

chroma_core/migrations/__init__.py
There are cases (which are becoming more common with upsert + polling)
where rows have not actually changed.
When this occurs we send a pg_notify event, even though the OLD and NEW
rows are identical.
Add a new if branch that will return early if NEW is equal to OLD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1913)
=> Avoid pg_notify if rows are identical

iml-system-docker-tests/src/lib.rs, iml-system-rpm-tests/src/lib.rs, iml-system-test-utils/src/vagrant.rs
Fixes #1907.
Halt all nodes and destroy one by one to prevent resource from hanging
on iscsi.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1909)
=> Update how vm's are destroyed

Cargo.lock, iml-gui/crate/Cargo.lock, iml-orm/Cargo.toml, iml-orm/src/lib.rs, iml-orm/src/sfa/mod.rs, iml-sfa/src/main.rs, iml-wire-types/src/db.rs
- Save enclosures before disks to ensure FK constraint is valid.
- Use serde_repr to {de}serialize c-like enums.
- Publically expose EnclosureType through iml-wire-types.
- Remove `Additions` and `Updates` from `get_changes`, it's not possible to determine what's changed without a key fn. Instead, return an `Upsert` struct that can be used to do an upsert in the db.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1926)
=> SFA Integration fixups

iml-gui/configs/tailwind.config.js, iml-gui/crate/src/components/dashboard/dashboard_fs_usage.rs, iml-gui/crate/src/components/dashboard/mod.rs, iml-gui/crate/src/page/dashboard.rs, iml-gui/crate/src/page/fs_dashboard.rs, iml-gui/crate/src/page/server_dashboard.rs, iml-gui/crate/src/page/target_dashboard.rs
The dashboard charts do not fill the vertical space available to them
(they are hardcoded to 20rem).
This can leave a large vertical gap dependent on screen size.
The charts should default to 100% height and have a minimum height of
20rem (to be consistent in smaller viewports).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1928)
=> Make dashboard containers fill vertical space

iml-system-docker-tests/Cargo.lock, iml-system-docker-tests/src/lib.rs, iml-system-docker-tests/tests/ldiskfs_test.rs, iml-system-docker-tests/tests/stratagem_test.rs, iml-system-docker-tests/tests/zfs_test.rs, iml-system-rpm-tests/Cargo.lock, iml-system-rpm-tests/src/lib.rs, iml-system-rpm-tests/tests/ldiskfs_test.rs, iml-system-rpm-tests/tests/stratagem_test.rs, iml-system-rpm-tests/tests/zfs_test.rs, iml-system-test-utils/src/iml.rs, iml-system-test-utils/src/lib.rs, iml-system-test-utils/src/vagrant.rs
- Change Hashmap of profiles to services to a vec of tuples to maintain order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1927)
=> Update server list trait

chroma_api/host.py, chroma_core/lib/cache.py, chroma_core/migrations/0020_clientmounts_remove_fk.py, chroma_core/models/client_mount.py, chroma_core/models/host.py, chroma_core/models/stratagem.py, chroma_core/services/job_scheduler/job_scheduler.py, chroma_core/services/job_scheduler/job_scheduler_client.py, chroma_core/services/lustre_audit/update_scan.py, iml-orm/src/models.rs, iml-orm/src/schema.rs, tests/unit/chroma_api/test_client_management.py, tests/unit/chroma_core/models/test_advertised_jobs.py
We may learn about a lustreclientmount prior to learning about a fs. We
should remove the fk association so we can keep mounts before we have a fs.
Closes #1920.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1931)
=> Remove fk relation between lustreclientmount and fs

vagrant/Vagrantfile, vagrant/scripts/configure_lustre_network.sh
Provisioning ordering needs to be install-lustre-client then configure-lustre-network
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1940)
=> Allow vagrants clients to have thier lnet provisioned

Cargo.lock, iml-orm/src/lib.rs, iml-orm/src/sfa/disk_drive.rs, iml-orm/src/sfa/enclosure.rs, iml-orm/src/sfa/job.rs, iml-orm/src/sfa/power_supply.rs, iml-sfa/src/main.rs
Since SFA objects can come from multiple appliances, it's not sufficient
to delete just by index. Instead, we need to delete by using the primary
keys + the SfaEnclosure uuid.
In addition, make diffing objects a bit more generic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1941)
=> Properly handle SFA object deletions

chroma-manager.conf.template
Allow big device trees to be sent w/o issues.
Currently ~10 device trees with 10 zpools and datasets hit 1MB limit, so we're increasing this for production where much more devices are expected.
Fix #1939 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1947)
=> Increase max body size for Rust agent

iml-gui/crate/src/components/action_dropdown/mod.rs, iml-gui/crate/src/page/servers.rs
Rust 1.44 made `vec![]` expand to `Vec::new()` (rust-lang/rust#70632).
As such clippy is now (somewhat correctly) interpreting that the macro could be used points-free.
clippy should be smart enough to not substitute the expanded macro, but
for now we can silence the errors by using a points-free constructor.
Fixes #1949.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1953)
=> Fix GUI clippy issues

iml-gui/crate/Cargo.toml, iml-gui/crate/src/event_source.rs, iml-gui/crate/src/lib.rs, iml-gui/crate/src/resize_observer.rs
Implement wasm-bindgen bindings to the [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) API.
This will allow us to observe size changes to an Element independent of the
overall viewport, which is particularly useful for elements effected by
sidebar width changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1956)
=> Implement ResizeObserver Bindings

grafana/dashboards/iml-metrics.json
This fixes LNet performance and cleans up displays with lacking data.
Y-Axis is always 0 min.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1962)
=> Grafana Fixup

iml-gui/crate/src/components/datepicker.rs, iml-gui/crate/src/components/sfa_overview/enclosures/ss9012.rs, iml-gui/crate/src/components/sfa_overview/mod.rs
When an SFA component is healthy have the tooltip say Healthy instead of
No Issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1961)
=> Update state for SFA tooltips

iml-manager-client/src/lib.rs, iml-request-retry/examples/demo-server-client.rs, iml-request-retry/src/lib.rs
There may be a case in which the future factory may need to generate a
different future based on the incremented tries. For example, if there
are two url's that can be fetched for the same information but the first
url fails, we should retry using the second url. If both of the urls are
stored in a vec, then this becomes trivial to fetch using the
incrementing index.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1959)
=> Update iml-request-retry to pass iteration index

docker/nginx.dockerfile
Update docker online-help version from 5.1 to 6.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1965)
=> Update docker online-help version from 5.1 to 6.1

Cargo.lock, iml-sfa/Cargo.toml, iml-sfa/src/main.rs
There are currently two controllers, each with an endpoint that provide
access to the same api. We try to hit this api using the first
controller, but it's possible that the endpoint will fail. If it does,
it should retry using the second endpoint. If that also fails, then we
can fail overall.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1960)
=> Retry SFA Endpoint

iml-orm/src/sfa/controller.rs, iml-sfa/src/main.rs
Controllers need to be wrapped in a retry_future.
In addition, we need to update child health state when it changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1974)
=> Fixup controller monitoring

chroma_core/models/client_mount.py
Use the filesystem from the object cache when unmounting / mounting filesystems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1978)
=> Use the filesystem from the object cache when unmounting / mounting filesystems.

vagrant/Vagrantfile
Monitored clients should have ntp configured. It's useful to have this
provisioner on the client nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1977)
=> Add the configure_ntp provisioner to client nodes

wbem-client/fixtures/empty.xml, wbem-client/src/cim_xml.rs, wbem-client/src/snapshots/wbem_client__cim_xml__resp__tests__empty.snap
`EnumerateInstances` may return an empty `IRETURNVALUE`. This is a valid
scenario and we should default to an empty `Vec` in this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1980)
=> Allow for empty EnumerateInstances

docker/docker-compose.yml
Use a lower resource check.
Fixes #1984.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1986)
=> Update influxdb healthcheck

iml-gui/crate/src/components/tree.rs
Fixes #1983.
The chart icons in the tree-view should be blue to indicate that they can be clicked. They should also have a tooltip when they are hovered over.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1985)
=> Make chart icons blue in tree view

docker/docker-compose.yml, docker/influxdb.dockerfile, docker/wait-for-settings.sh
There are containers that do not depend on rabbitmq being available.
For these cases, we can use a wait-for-settings.sh that only waits for
shared settings to be available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1987)
=> Add wait-for-settings check

docker/Makefile, docker/docker-compose.yml, docker/rabbitmq.dockerfile
Instead of spawning a new erlang process once per 5s we can use curl to
check the rabbitmq api.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1990)
=> Update rabbit healthcheck

chroma_core/models/host_jobs/test_host_contact.py
There is a branch of _test_yum_rpm_sanity that returns a tuple of bool.
This causes issues in the CLI, which is expecting a single boolean.
Normalize the return to always return a single boolean.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1995)
=> Fix branch of _test_yum_rpm_sanity that returns a tuple of bool

chroma_core/management/commands/print-settings.py
We no longer use sourcemaps with the new GUI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1996)
=> remove SRCMAP_PATH

.copr/Makefile, docker/update-embedded.sh, iml-docker.spec
There are cases where we change a config value and need to update the
swarm.
Add a new shell script `embedded-update` that will update relevant
services with any config changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1997)
=> Create a command to update docker services

iml-agent/src/daemon_plugins/postoffice.rs
Closes #1838.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1989)
=> Fix file descriptor leak in the postoffice plugin

iml-agent/src/daemon_plugins/postoffice.rs
When someone tries to print the postoffice daemon plugin
it will take an internal lock and block the current thread.
This is at the very least suprising and should be removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2002)
=> Remove blocking debug in postoffice

Cargo.lock, iml-agent/Cargo.toml, iml-agent/README.md, iml-agent/src/http_comms/session.rs, iml-agent/src/poller.rs, iml-agent/src/reader.rs
If a daemon plugin executes for longer than a poll interval it will continue running in the background. This can cause buffering of resources in the case of a misbehaving call.
We've seen this when `lnetctl export` hangs due to large numbers of peers.
We can add an `in_flight` handle to active sessions.
If we hit the deadline while a plugin is in a poll, we can drop the pending future and poll the plugin again. This will ensure we don't buffer misbehaving resources when a deadline elapses.
Fixes #1998.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2001)
=> Add in_flight handle to active sessions

iml-agent/src/action_plugins/lamigo.rs, iml-agent/src/action_plugins/lpurge.rs, iml-agent/src/action_plugins/snapshots/iml_agent__action_plugins__lpurge__lpurge_conf_tests__works.snap, iml-agent/src/daemon_plugins/postoffice.rs, iml-agent/src/env.rs
We have a number of intermittently failing tests that are due to setting environment variables within the tests.
Rust tests run in parallel and the environment is basically a singleton. Therefore, these tests leak state with each other and are non-deterministic.
In addition, we are pulling items between action plugins, where we could factor it out into the env instead.
Fixes #1826.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2008)
=> Do not set environment variables in tests

chroma-manager.conf.template, docker/docker-compose.yml, iml-docker.spec, iml-manager-cli/src/snapshots/iml_manager_cli__nginx__tests__replace_template_variables.snap
Make favicons dynamic
Fixes #1700.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1988)
=> Make favicons dynamic

Cargo.lock, iml-warp-drive/README.md, iml-warp-drive/src/users.rs
In: https://github.com/whamcloud/integrated-manager-for-lustre/blob/83d065653a55ee4c1a6068c1d024f02a02c73172/iml-warp-drive/src/users.rs#L54-L58
We spawn a task to disconnect users. However, we move both the tx and rx
handles into the task and block on the tx being cancelled.
Due to this approach, we will not disconnect users and instead buffer
their handles.
Instead, we should use .retain when sending to users and remove the ones
that error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2006)
=> Fix user disconnects

rust-iml.spec
We only want to run systemctl preset on initial install and not upgrade. Use the systemd_post macro which does this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2022)
=> Use systemd_post instead of systemctl preset

Cargo.lock, chroma_core/services/lustre_audit/update_scan.py, device-scanner/device-scanner-daemon/src/state.rs, iml-services/iml-device/Cargo.toml, iml-services/iml-device/src/main.rs
Example:
```
chroma=> select * from chroma_core_lustreclientmount;
id |       state_modified_at       |  state  | immutable_state | not_deleted | mountpoint | content_type_id | filesystem | host_id
----+-------------------------------+---------+-----------------+-------------+------------+-----------------+---------------+---------
16 | 2020-05-18 16:01:10.768484+00 | mounted | f               | t           | /mnt/fs    |              35 |             fs |       5
17 | 2020-05-18 16:01:10.768484+00 | mounted | f               | t           | /mnt/fs2   |              35 |             fs2 |       5
```
```
may 19 10:18:29 adm.local iml-device[13087]: May 19 10:18:29.751 DEBUG iml_device: Client mounts at c1.local: [("fs2", Some("/mnt/fs2"))]
may 19 10:18:29 adm.local iml-device[13087]: May …
```
=> Monitor client mounts in iml-device

.copr/Makefile, .dockerignore, .github/workflows/rust-ci.yml, .gitignore, Cargo.lock, Makefile, iml-orm/src/models.rs, iml-services/iml-device/Cargo.toml, iml-services/iml-device/README.md, iml-services/iml-device/sqlx-data.json, iml-services/iml-device/src/error.rs, iml-services/iml-device/src/linux_plugin_transforms.rs, iml-services/iml-device/src/main.rs, settings.py, vagrant/scripts/install_iml_local.sh, vagrant/scripts/install_iml_local_agent.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2025)
=> Use sqlx for iml-devices

iml-gui/crate/src/auth.rs, iml-gui/crate/src/components/tree.rs, iml-gui/crate/src/lib.rs, iml-gui/crate/src/page/login.rs, iml-gui/crate/src/page/partial/footer.rs, iml-gui/crate/src/page/partial/header.rs
This includes logging in and logging out.
`logged_out` is removed because "disabled" is not working with `a` anyway.
Can be added to the auth::Model if needed.
Closes  #2030, #1805,  #1737, #1735 (supersedes https://github.com/whamcloud/integrated-manager-for-lustre/pull/1755).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2026)
=> Handle sessions in one place

iml-manager-client/src/lib.rs, iml-request-retry/Cargo.toml, iml-request-retry/examples/demo-server-client.rs, iml-request-retry/src/lib.rs, iml-sfa/src/main.rs
By updating retry_future to take ownership of it's policy,
we can allow for policies to be created within fns.
In addition, we can drop the `Send` bound.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2029)
=> Update retry_future to take ownership of policy

iml-manager-cli/src/server.rs, iml-system-test-utils/src/vagrant.rs, vagrant/scripts/deploy_hosts.sh
This affects commands:
1. iml server add
2. iml server remove
3. iml server force-remove
All of them now use multiple (one and more) hostlist expressions,
for example:
iml server remove mds[1,2].local c1.local
iml server add -p stratagem_client c1.local
Closes #2033.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2040)
=> Improve and unify server operations in CLI

chroma_core/services/job_scheduler/job_scheduler.py
Different types of sets were compared to each other:
objects and strings:
current set([<ManagedOst: fs-OST0000>]),
new set([u'fs-OST0000', u'fs-OST0001']),
add set([u'fs-OST0000', u'fs-OST0001']),
remove set([<ManagedOst: fs-OST0000>]).
Make sure to compare strings only.
There is a minor and likely unrelated issue when growing with the same OST: an empty job list results in an error:
```
[root@adm ~]# vim /var/log/chroma/job_scheduler.log
[root@adm ~]# iml filesystem pool grow fs fast fs-OST0002
Growing ost pool...
[1/1]   ✔ Updating OST Pool successful
[root@adm ~]# iml filesystem pool grow fs fast fs-OST0001
Growing ost pool...
✗ HTTP status client error (404 Not Found) for url (https://adm.local/api/ostpool/4/)
[root@adm ~]# iml filesystem pool show fs fast
+------------+------------+ …
```
=> Fix OST pool grow

vagrant/scripts/create_iml_diagnostics.sh
SOS reports use a docker plugin but this plugin does not include docker
logs by default. Ensure that all portions of docker are included.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2069)
=> Update sos reports

iml-services/iml-service-queue/src/service_queue.rs
host plugins will need to deal with the data directly, otherwise
valid messages may be dropped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2080)
=> Remove queue purge during startup

iml-agent/src/main.rs
Closes #1476.
```
jul 15 15:24:10 c1.local iml-agent-daemon[663]: Jul 15 15:24:10.810 DEBUG iml_agent::http_comms::crypto_client: resp headers: {"server": "nginx/1.16.1", "date": "Wed, 15 Jul 2020 15:24:10 GMT", "content-length": "0", "connection": "keep-alive"}
jul 15 15:24:13 c1.local systemd[1]: Stopping Rust IML Agent Daemon...
jul 15 15:24:13 c1.local iml-agent-daemon[663]: Jul 15 15:24:13.191  INFO iml_agent_daemon: Terminating...
jul 15 15:24:13 c1.local iml-agent-daemon[663]: Jul 15 15:24:13.191  INFO iml_agent::http_comms::session: Terminating all sessions
jul 15 15:24:13 c1.local iml-agent-daemon[663]: Jul 15 15:24:13.191  INFO iml_agent::http_comms::session: Terminating session PluginName("stats")/Id("40cf2205-aaee-44ef-9601-f6a38b306851")
jul 15 15:24:13 c1.local …
```
=> Agent to teardown sessions on signals

chroma_core/services/job_scheduler/job_scheduler.py
Ref: f10ba6b9a69c3c424fc50d21903f7178a014e763
Closes #2084.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2085)
=> Fix client mount in run_stratagem

iml-system-docker-tests/README.md, iml-system-rpm-tests/README.md, iml-system-test-utils/README.md
- Add README.md to docker-based integration tests
- Add README.md to rpm-based integration tests
- Add README.md to iml-system-test-utils discussing test architecture
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2091)
=> Add README.md to integration test crates

Cargo.lock, iml-agent/src/daemon_plugins/journal.rs, iml-services/iml-journal/src/main.rs, iml-wire-types/src/lib.rs
The Journal daemon plugin keeps a Mutex around the cursor of where it last read
from the journal.
However, when updating the session we attempt to take a lock on the
cursor before the first one has been dropped.
Wrap the acquistion of the cursor and clone the contents, so it's
expclitly dropped.
In addition, read all the journal response into text and then convert to
messages instead of streaming, as this is what we end up doing anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2092)
=> Fix Journal cursor deadlock

chroma_api/job.py, iml-gui/crate/src/components/stratagem/mod.rs
Closes #1762, #2090.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2095)
=> Show command modal when modifying file scan

iml-system-test-utils/src/ssh.rs
Update sosreport dir to include the prefix
Signed-off-by: root <root@onyx-25.onyx.whamcloud.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2088)
=> Update sosreport dir to include the prefix

docker/Makefile, docker/compose-deps.hcl
Use docker buildx and `bake` to paralellize compose dep building.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2101)
=> Use docker buildx for building

iml-docker.service, iml-docker.spec
`iml-images.tgz` currently lives under /var/tmp
and is marked as ok if it's missing.
This can cause an issue if the tarball is removed, as `iml-docker` will
not be able to load the images and startup.
Move the tarball to `/var/lib`, and make it non-optional.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2103)
=> Make docker image tarball a required file

vagrant/README.md, vagrant/Vagrantfile, vagrant/scripts/mount_lustre_client.sh
Fixes Issue #2093
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2094)
=> Add alternate client mount provisioners

Cargo.lock, iml-agent-comms/src/messaging.rs, iml-agent/src/http_comms/agent_client.rs, iml-agent/src/http_comms/session.rs, iml-agent/src/poller.rs, iml-agent/src/reader.rs, iml-wire-types/src/lib.rs
If the iml-agent gets a `SESSION_DESTROY` message, it will destroy the
session with a matching plugin name, even if the session id does not
match.
This could lead to the wrong session being destroyed.
Check if the currently held session id matches the one to be destroyed.
If so, destroy it, if not it's a noop.
In addition, Remove the `SessionInfo` struct and replace `Seq` with
`AtomicU64`. This allows us to drop a Mutex, as `AtomicU64` is lockless
and threadsafe.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2105)
=> Only destroy matching sessions

Cargo.lock, iml-system-docker-tests/src/lib.rs, iml-system-docker-tests/tests/ldiskfs_test.rs, iml-system-docker-tests/tests/stratagem_test.rs, iml-system-docker-tests/tests/zfs_test.rs, iml-system-rpm-tests/src/lib.rs, iml-system-rpm-tests/tests/ldiskfs_test.rs, iml-system-rpm-tests/tests/stratagem_test.rs, iml-system-rpm-tests/tests/zfs_test.rs, iml-system-test-utils/Cargo.toml, iml-system-test-utils/src/lib.rs, iml-system-test-utils/src/snapshots.rs, iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_ldiskfs_test_path_from_graph.snap, iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_stratagem_test_path_from_graph.snap, iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_zfs_test_path_from_graph.snap, iml-system-test-utils/src/ssh.rs, iml-system-test-utils/src/vagrant.rs, vagrant/README.md, vagrant/Vagrantfile
vagrant: Split mount from create for zfs backed fs
test: Check that the correct number of filesystems
were detected in detect_fs()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2102)
=> tests: Mount filesystem(s) during detect_fs

iml-manager-cli/src/main.rs, iml-manager-cli/src/server.rs
```
[root@adm ~]# /bin/iml server 
+----+------------+--------------+------------------+
| Id | FQDN       | State        | Nids             |
+====+============+==============+==================+
| 1  | mds1.local | monitored    | 10.73.20.11@tcp0 |
+----+------------+--------------+------------------+
| 2  | mds2.local | monitored    | 10.73.20.12@tcp0 |
+----+------------+--------------+------------------+
| 3  | oss1.local | monitored    | 10.73.20.21@tcp0 |
+----+------------+--------------+------------------+
| 4  | oss2.local | monitored    | 10.73.20.22@tcp0 |
+----+------------+--------------+------------------+
| 5  | c1.local   | managed      | 10.0.2.15@tcp0   |
+----+------------+--------------+------------------+
| 6  | c2.local   | unconfigured |                  | …
```
=> Make listing servers default command

iml-system-test-utils/src/lib.rs, vagrant/Vagrantfile, vagrant/scripts/install_iml_docker_local.sh, vagrant/scripts/install_iml_docker_repouri.sh
Due to an interesting bug in Vagrant, nodes that have a hexadecimal only
name have the chance to collide with an existing vm index name.
When this occurs, Vagrant confuses VMs with each other.
Rename `c[1-8]` nodes to `client[1-8]` to avoid this bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2113)
=> Rename client nodes to non hexadecimal characters

iml-system-docker-tests/tests/ldiskfs_test.rs, iml-system-docker-tests/tests/zfs_test.rs, iml-system-rpm-tests/tests/ldiskfs_test.rs, iml-system-rpm-tests/tests/zfs_test.rs, iml-system-test-utils/src/lib.rs
Without profiles for clients, they nothing is installed, and no
Bare snapshot is taken of them.  Any subsequent test that requires
a Bare snapshot will be without clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2111)
=> Tests: Add clients to ldiskfs zfs profile list

Cargo.lock, iml-action-client/Cargo.toml, iml-agent/Cargo.toml, iml-manager-cli/Cargo.toml, iml-manager-client/Cargo.toml, iml-request-retry/Cargo.toml, iml-services/iml-stats/Cargo.toml, wbem-client/Cargo.toml
Default features enable `default-tls` which is `native-tls`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2098)
=> Disable default features of reqwest

iml-system-test-utils/src/snapshots.rs, iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_ldiskfs_test_path_from_graph.snap, iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_stratagem_test_path_from_graph.snap, iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_zfs_test_path_from_graph.snap
Split FilesystemDetect state as shown:
Needed for Issue #1832 
Fixes #2117
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2118)
=> Split FilesystemDetect state into 3

Cargo.lock, iml-services/iml-journal/src/main.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2116)
=> Bump sqlx to latest

Cargo.lock, iml-action-client/Cargo.toml, iml-action-client/src/lib.rs, iml-services/iml-action-runner/src/lib.rs, iml-services/iml-action-runner/src/sender.rs, iml-services/iml-action-runner/tests/action_runner_tests.rs, iml-wire-types/src/lib.rs
This allows to break cyclic dependency of iml-action-runner and
iml-action-client which occurs when iml-action-runner wants to call
iml-action-client::invoke_rust_agent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2128)
=> Move ActionType to iml_wire_types

Makefile, iml-system-docker-tests/Cargo.lock, iml-system-rpm-tests/Cargo.lock, iml-system-test-utils/README.md, iml-system-test-utils/src/lib.rs, iml-system-test-utils/src/snapshots.rs, iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_ldiskfs_test_path_from_graph.snap, iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_stratagem_test_path_from_graph.snap, iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_zfs_test_path_from_graph.snap, iml-system-test-utils/src/ssh.rs, vagrant/scripts/install_ldiskfs_zfs_no_iml.sh
We should be able to do a single lustre install step for each monitored
test variant.
This should shave a bunch of time off test runs, as lustre will be
installed via snapshot for all branches.
Fixes #2119.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2124)
=> Use a single lustre install step

iml-services/iml-action-runner/src/lib.rs, iml-services/iml-action-runner/src/remote_action.rs, iml-services/iml-action-runner/src/sender.rs
Currently, the only way to run a `remote_action` is to call it through
the `action-runner`.
This means even if there is code within the `action-runner` that wants
to call a local action it will need to schedule it via HTTPS / UDS.
As a first step to making this more efficient, move the `remote_action`
code out to a directly callable fn.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2123)
=> Extract remote_action code from sender

iml-system-test-utils/src/snapshots.rs, iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_ldiskfs_test_path_from_graph.snap, iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_stratagem_test_path_from_graph.snap, iml-system-test-utils/src/snapshots/iml_system_test_utils__snapshots__tests__get_zfs_test_path_from_graph.snap
Since we now install all profiles always, we only need a single ImlConfigured node in the snapshot graph.
Related Issue #1832
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2130)
=> Tests: Unify iml-configured graph node

chroma_core/lib/cache.py, chroma_core/models/client_mount.py
The `LustreClientMount` uses `ObjectCache` for many of it's lookups.
However, we do not update this `ObjectCache` when we discover changes to client mounts.
It is easier to remove this indirection and just ask the DB directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2133)
=> Remove ObjectCache from ClientMount

iml-manager-cli/src/api.rs, iml-manager-cli/src/lib.rs, iml-manager-cli/src/main.rs, iml-manager-client/src/lib.rs
`debugapi` does not show up in help as it's for test/debug
Related #1832 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2132)
=> Add 'iml debugapi' to iml cli

Cargo.lock, iml-orm/README.md, iml-services/iml-action-runner/Cargo.toml, iml-services/iml-action-runner/src/db.rs, iml-services/iml-action-runner/src/error.rs, iml-services/iml-action-runner/src/lib.rs, iml-services/iml-action-runner/src/local_actions.rs, iml-services/iml-action-runner/src/main.rs, iml-services/iml-action-runner/src/sender.rs, iml-services/iml-action-runner/tests/integration_tests.rs, iml-wire-types/src/lib.rs, sqlx-data.json
Update local actions to pass in a `PgPool`. This will allow db calls to
be made and can be used in place of the Django ORM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2141)
=> Allow local actions to make db calls

chroma_core/models/host.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2140)
=> Implement Create/Destroy SnapshotStep

chroma_api/stratagem.py, chroma_core/models/client_mount.py, iml-agent/src/action_plugins/lustre/client.rs
Fixup the client mount action so it correctly
determines if a client is currently mounted.
In addition, remove the requirement for the stratagem client,
it will not be needed with the task queue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2148)
=> Fixup client mounts

iml-manager-cli/src/api.rs
Related #1832 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2149)
=> debuapi: Optionally read from stdin for Body

Cargo.lock, iml-api/src/main.rs, iml-mailbox/Cargo.toml, iml-mailbox/src/main.rs, iml-manager-env/src/lib.rs, iml-services/iml-action-runner/src/main.rs, iml-services/iml-device/src/main.rs, iml-services/iml-journal/src/main.rs, iml-services/iml-ntp/Cargo.toml, iml-services/iml-ntp/src/main.rs, iml-task-runner/Cargo.toml, iml-task-runner/src/main.rs, sqlx-data.json
Allow override of POOL_LIMIT on a per service basis
Adjust most limits down
Adjust task-runner limit up to 10
Fixes #2157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2158)
=> Make db pool size configurable

iml-task-runner/src/main.rs
We're hitting an issue that looks similar to
https://github.com/launchbadge/sqlx/issues/622
I was able to work around it by disabling fairness, but we can just
avoid the lookup entirely if active workers is >= the pool size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2165)
=> Don't use try_acquire alongside spawned task

iml-agent/src/action_plugins/high_availability/mod.rs, iml-wire-types/src/lib.rs
Also add wire-types for resource constraints.
Related #1464
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2166)
=> Add ops to ResourceAgentType

iml-agent/src/action_plugins/lustre/snapshot.rs
If `snapshot_list` is called when there are no snapshots, no output is
produced.
If this is fed into `parse_snapshot_list` it will produce an error like:
```
Parse error at 0
Unexpected `end of input`
Expected `:` or `whitespaces`
```
The easiest way to head this off is to make sure the input is non-empty
and return an empty `Vec` if it is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2170)
=> Ensure empty snapshots do not produce parse error

Cargo.lock, Cargo.toml, iml-change/Cargo.toml, iml-change/README.md, iml-change/src/lib.rs
This patch adds the `iml-change` crate that can be used to compare
collections for things that should be upserted or deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2171)
=> Introduce iml-change crate

vagrant/Vagrantfile
Fix #2175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2179)
=> Ignore .env

docker/docker-compose.yml
`sqlx::query=warn` was being tacked on to the wrong environment
variable, which is causing warp-drive to break in docker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2183)
=> Fix docker-compose.yml

chroma_core/migrations/0025_createsnapshotjob_destroysnapshotjob.py
so `./manage.py migrate` stop complaining.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2185)
=> Fix migration help text

.copr/Makefile, Cargo.lock, Cargo.toml, Makefile, docker/docker-compose.yml, docker/iml-corosync.dockerfile, iml-agent/src/daemon_plugins/corosync.rs, iml-agent/src/daemon_plugins/daemon_plugin.rs, iml-agent/src/daemon_plugins/mod.rs, iml-manager.target, iml-rust-corosync.service, iml-services/iml-corosync/Cargo.toml, iml-services/iml-corosync/src/main.rs, iml-wire-types/src/high_availability.rs, migrations/20200824170157_corosync_node.sql, python-iml-manager.spec, rust-iml.spec, sqlx-data.json, vagrant/scripts/install_iml_local.sh
Add a new daemon / service to Rust that will
continually get node info for any existing clusters.
Fixes #2139.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2184)
=> Add corosync daemon plugin to Rust

vagrant/scripts/install_iml_local.sh
It's already in `make local`
Fixes #2191.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2192)
=> Remove Device scanner make command from local build

iml-services/iml-device/src/lib.rs, iml-services/iml-device/src/main.rs
ref:
```
chroma=> select * from chroma_core_lustreclientmount;
id |       state_modified_at       |  state  | immutable_state | not_deleted | content_type_id | filesystem | host_id | mountpoints
----+-------------------------------+---------+-----------------+-------------+-----------------+------------+---------+--------------
1 | 2020-08-28 20:04:24.747547+00 | mounted | f               | t           |              41 | 35efda93   |       5 | {/mnt/wut}
2 | 2020-08-28 20:04:24.755229+00 | mounted | f               | t           |              41 | zfsmo      |       5 | {/mnt/zfsmo}
(2 rows)
``` 
The first mount here is a snapshot mount and should not make it into this table.
---
This change is [<img …
=> EX-1629 - Ensure client-mounts do not pickup snapshot mounts

Cargo.lock, iml-postgres/Cargo.toml, iml-postgres/src/lib.rs, iml-services/iml-device/Cargo.toml, iml-services/iml-device/tests/integration_tests.rs
Add a test_setup fn to iml_postgres that will run hand out a single
pool connection and run it within a transaction. When the connection is
closed the transaction is rolled back so it is safe to call in parllel
and will not pollute db testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2206)
=> Add test_setup fn to iml_postgres

Cargo.lock, iml-gui/crate/Cargo.lock, iml-influx/Cargo.toml, iml-influx/src/lib.rs, iml-services/iml-device/Cargo.toml, iml-services/iml-device/src/lib.rs, iml-services/iml-device/src/snapshots/iml_device__tests__deletions_only.snap, iml-services/iml-device/src/snapshots/iml_device__tests__upserts_and_deletions.snap, iml-services/iml-stats/src/main.rs
The MGS target has the same name for multiple filesystems. As an
example, a filesystem created with an MGT on MDS1 and a filesystem
created with an MGT on OSS1 will both have a target name of `MGS`. This
needs to be accounted for when building the target table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2196)
=> Account for multiple fs with the same target name

iml-agent/src/action_plugins/lustre/snapshot.rs, iml-agent/src/action_plugins/lustre/snapshot/parse.rs, iml-agent/src/daemon_plugins/snapshot.rs, iml-api/src/graphql.rs, iml-services/iml-snapshot/src/main.rs, iml-wire-types/src/snapshot.rs, sqlx-data.json
Don't need detailed views
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2222)
=> Simplify Snapshot structure

iml-api/src/error.rs, iml-api/src/graphql.rs, iml-api/src/main.rs, iml-rabbit/src/lib.rs, iml-wire-types/src/lib.rs, iml-wire-types/src/snapshot.rs, sqlx-data.json
With snapshot creation, there's issue of filesystem going `stopped` unexpectedly.
With everything else, there's potential to hit this issue: https://github.com/whamcloud/integrated-manager-for-lustre/issues/2218
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2177)
=> Implement entire Snapshot GraphQL API

iml-api/src/graphql.rs, iml-services/iml-device/src/lib.rs, iml-services/iml-device/src/main.rs, migrations/20200728203410_devices.sql, sqlx-data.json
Fixes #2198.
The table should be singular like the others for consistency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2216)
=> Rename "targets" table to "target"

Cargo.lock, iml-api/src/graphql.rs, iml-gui/crate/Cargo.lock, iml-gui/crate/src/components/stratagem/mod.rs, iml-gui/crate/src/lib.rs, iml-gui/crate/src/test_utils/fixtures.rs, iml-warp-drive/src/cache.rs, iml-warp-drive/src/db_record.rs, iml-warp-drive/src/main.rs, iml-wire-types/Cargo.toml, iml-wire-types/src/db.rs, iml-wire-types/src/sfa.rs, iml-wire-types/src/snapshot.rs, iml-wire-types/src/warp_drive.rs, migrations/20200831174542_snapshot.sql, sqlx-data.json
This patch adds snapshots to iml-warp-drive.
It also removes the dependency on tokio_postgres to fill initial cache
in favor or using sqlx to do so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2225)
=> Add Snapshots to iml-warp-drive

liblustreapi/src/lib.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2212)
=> PR-2211 Add llapi_path2fid support

Cargo.lock, liblustreapi-types/Cargo.toml, liblustreapi/Cargo.toml, liblustreapi/src/error.rs, liblustreapi/src/lib.rs
The latest version of `libloading` add it's own error type instead of
just returning `io::Error`. Due to this, we can just wrap / return that
error directly instead of creating a new variant.
In addition, update `LiblustreError` to use `thiserror`.
Fixes #2226.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2228)
=> Bump libloading to latest

iml-manager-cli/Cargo.toml, iml-manager-cli/src/api_utils.rs, iml-manager-cli/src/display_utils.rs, iml-manager-cli/src/lib.rs, iml-manager-cli/src/main.rs, iml-manager-cli/src/snapshot.rs, iml-manager-client/src/lib.rs
```
USAGE:
iml snapshot list <fsname> --display <display-type>
For more information try --help
[root@adm ~]# iml snapshot list zfsmo
+------------+----------+---------------------------------+-----------+-------------+
| Filesystem | Snapshot | Creation Time                   | State     | Comment     |
+============+==========+=================================+===========+=============+
| zfsmo      | foo1     | Wed, 09 Sep 2020 12:58:56 +0000 | unmounted | --          |
+------------+----------+---------------------------------+-----------+-------------+
| zfsmo      | foo2     | Wed, 09 Sep 2020 14:01:40 +0000 | unmounted | hello world |
+------------+----------+---------------------------------+-----------+-------------+
```
---
This …
=> Implement snapshot listing in CLI

Cargo.lock, iml-graphql-queries/src/lib.rs, iml-graphql-queries/src/snapshot.rs, iml-manager-cli/Cargo.toml, iml-manager-cli/src/api_utils.rs, iml-manager-cli/src/error.rs, iml-manager-cli/src/snapshot.rs, iml-manager-client/src/lib.rs
This patch implements iml-graphql-queries for all
snapshot queries and mutations. It also updates the `iml snapshot list`
command to use one of these queries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2237)
=> Implement graphql queries for all snapshot queries and mutations

iml-api/src/graphql.rs, iml-api/src/main.rs, iml-manager-env/src/lib.rs, iml-postgres/src/lib.rs, sqlx-data.json, vagrant/Vagrantfile
Implements GraphQL for commands.
Also fixes some clippy warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2240)
=> EX-1687 graphql commands

iml-graphql-queries/src/lib.rs, iml-manager-cli/src/api.rs, iml-manager-cli/src/main.rs, iml-manager-client/src/lib.rs
The -r option will result in `iml debugapi -r POST graphql DATA`
talking to /graphql instead of /api/graphql/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2209)
=> Add debugql subcommand to manager

Cargo.lock, iml-api/Cargo.toml, iml-api/src/graphql.rs, iml-graphql-queries/Cargo.toml, iml-graphql-queries/src/snapshot.rs, iml-gui/crate/Cargo.lock, iml-gui/crate/src/lib.rs, iml-gui/crate/src/test_utils/fixtures.rs, iml-warp-drive/src/cache.rs, iml-warp-drive/src/db_record.rs, iml-wire-types/Cargo.toml, iml-wire-types/src/graphql_duration.rs, iml-wire-types/src/lib.rs, iml-wire-types/src/snapshot.rs, iml-wire-types/src/warp_drive.rs, migrations/20200817164118_utils.sql, migrations/20200824170157_corosync.sql, migrations/20200831174542_snapshot.sql, sqlx-data.json, tests/unit/lib/iml_unit_test_case.py, vagrant/README.md
This patch adds support for creating and deleting snapshot intervals
and snapshot retention rules via the API.
It also adds support for these tables to warp-drive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2247)
=> Add snapshot configuration API

.github/workflows/devel-release.yml, .github/workflows/prod-release.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2252)
=> Fix docker releases so older compose is used

iml-gui/crate/Cargo.lock, iml-gui/crate/Cargo.toml, iml-gui/crate/src/page/snapshot/add_interval.rs, iml-gui/crate/src/page/snapshot/list_interval.rs, iml-gui/crate/src/page/snapshot/mod.rs, iml-gui/crate/src/page/snapshot/take.rs
Create a new add interval modal that will allow for snapshot intervals
to be created via the GUI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2256)
=> Create add interval modal

chroma_core/models/task.py
Only call RemoteTaskStep if state is not already removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2260)
=> Make task remove idempotent

Cargo.lock, iml-api/src/graphql.rs, iml-graphql-queries/src/snapshot.rs, iml-manager-cli/Cargo.toml, iml-manager-cli/src/display_utils.rs, iml-manager-cli/src/snapshot.rs, sqlx-data.json
```
[root@adm ~]# iml snapshot interval list
+----+------------+---------------------+-------------+----------+
| Id | Filesystem | Interval            | Use Barrier | Last Run |
+====+============+=====================+=============+==========+
| 1  | zfsmo      | 1 minute            | false       | --       |
+----+------------+---------------------+-------------+----------+
| 3  | zfsmo      | 1 week              | false       | --       |
+----+------------+---------------------+-------------+----------+
| 4  | zfsmo      | 1 year and 11 hours | false       | --       |
+----+------------+---------------------+-------------+----------+
[root@adm ~]# iml snapshot interval add zfsmo  10 year -b
[root@adm ~]# iml snapshot interval list …
```
=> Add snapshot interval operations to CLI

Cargo.lock, Cargo.toml, iml-command-utils/Cargo.toml, iml-command-utils/src/lib.rs, iml-manager-cli/Cargo.toml, iml-manager-cli/src/api_utils.rs, iml-manager-cli/src/error.rs
This patch extracts the command polling logic to it's own crate.
It doesn't use any feature flags, and does not duplicate the polling
logic.
The internal behavior is delegated to a mpsc channel, where the caller
can decide how to process completions and updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2251)
=> Extract command polling logic to it's own crate

Cargo.lock, iml-influx/Cargo.toml, iml-influx/src/lib.rs
Implement an influx client extenstion that allows for direct
serialization to a struct instead of needing to traverse the result and
build it by hand. Ex:
```rust
struct MgsFsTime {
time: u64,
}
let xs: Vec<MgsFsTime> = client
.query_into(
format!(
r#"
SELECT mgs_fs,is_mgs_fs
FROM target
WHERE mgs_fs='{}' AND is_mgs_fs=true
ORDER BY time ASC
LIMIT 2"#,
fs_names
)
.as_str(),
Some(Precision::Nanoseconds),
)
.await?
.unwrap_or_default();
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2262)
=> Implement influx client extension

Pipfile.lock, requirements.txt
Toolz just updated from 0.10.0 to 0.11.0 and it is causing failures. Pin
it to 0.10.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2270)
=> Pin Toolz dep to 0.10.0

iml-api/src/graphql.rs, iml-graphql-queries/src/snapshot.rs, iml-manager-cli/src/display_utils.rs, iml-manager-cli/src/snapshot.rs, iml-warp-drive/src/cache.rs, iml-wire-types/src/snapshot.rs, migrations/20200831174542_snapshot.sql, sqlx-data.json
```
[root@adm ~]# iml snapshot retention create zfsmo 50 g 10
[root@adm ~]# iml snapshot retention list
+----+------------+---------+------+----------+
| Id | Filesystem | Reserve | Keep | Last Run |
+====+============+=========+======+==========+
| 5  | zfsmo      | 50 GiB  | 10   | --       |
+----+------------+---------+------+----------+
[root@adm ~]# iml snapshot retention create zfsmo 10 % 10
[root@adm ~]# iml snapshot retention list
+----+------------+---------+------+----------+
| Id | Filesystem | Reserve | Keep | Last Run |
+====+============+=========+======+==========+
| 5  | zfsmo      | 10 %    | 10   | --       |
+----+------------+---------+------+----------+
```
---
This change is [<img …
=> Add snapshot retention ops to CLI

iml-api/src/graphql.rs
Fixes #2268.
Currently, the limit param allows you to specify a limit when retrieving items back from an API call. This is a numeric value that can be passed in but in some cases, we may want all results. To address this, postress allows us to pass in ALL instead of a numeric value, which is effectively the same as not passing a limit at all. Update all of the graphql API endpoints such that if None is passed in it will pass ALL to the LIMIT clause in the query. This will allow us to get all entries without modifying the existing api.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2269)
=> GH-2268 Update the limit param in graphql api's

iml-agent/src/daemon_plugins/snapshot.rs
Listing times on the agent. With 10 snapshots:
```
[root@mds1 vagrant]# time iml-agent snapshot list fs
{{[Snapshot
{ filesystem_name: "fs", snapshot_name: "test2", snapshot_fsname: "7941fd0f", modify_time: 2020-09-25T09:53:04Z, create_time: 2020-09-25T09:53:04Z, mounted: Some(false), comment: Some("") }
...
real 0m4.728s
user 0m0.610s
sys 0m0.408s
```
With 20 snapshots:
```
[root@mds1 vagrant]# time iml-agent snapshot list fs
[Snapshot
{ filesystem_name: "fs", snapshot_name: "test2", snapshot_fsname: "7941fd0f", modify_time: 2020-09-25T09:53:04Z, create_time: 2020-09-25T09:53:04Z, mounted: Some(false), comment: Some("") }
...
real 0m11.720s
user 0m1.571s
sys 0m0.905s
```
There's also some variance. For 20 snapshots, these are 5 times: 0m11.720s, 0m10.119s, 0m9.724s, 0m10.353s, 0m8.728s. …
=> Lower snapshot listing interval

iml-api/src/graphql.rs, sqlx-data.json
For the ids supplied return the commands, the order is guaranteed to be preserved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2265)
=> Implement fetching commands by ids

docker/iml-timer.dockerfile
The `iml-timer.service` is moved to a directory that has a volume
mounted over it.
Because of this, any changes to the service file from the image are
overwritten.
Move the service file to a dir that does not have a volume mounted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2284)
=> Write timer service to non volume mounted area

iml-gui/crate/src/page/snapshot/list.rs
The snapshot table should not display if there are no rows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2286)
=> Hide snapshot table if there are no rows to display.

iml-api/src/graphql.rs, sqlx-data.json
Return FQDNs instead of host IDs so that it can be used by
hotpools.
Related #2241 #1464  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2287)
=> graphql: Return fqdn from get_fs_cluster_hosts()

docker/docker-compose.yml, docker/iml-manager-cli.dockerfile
The docker iml cli had an extra layer of indirection where it would
source a profile before invoking the iml binary.
This may have been done prior to using .dotenv in the cli binary, but
it's no longer needed so we can remove all of it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2294)
=> Remove CLI indirection

Cargo.lock, wbem-client/Cargo.toml
Due to https://github.com/ctz/hyper-rustls/issues/84 and the fact that
we may use ip addresses for this endpoint, we need to switch the
wbem-client back to using openssl.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2301)
=> Use default-tls for wbem-client

iml-gui/crate/src/components/chart/fs_usage.rs, iml-gui/crate/src/components/progress_circle.rs, iml-gui/crate/src/page/filesystem.rs, iml-services/iml-snapshot/src/retention.rs
Update percentage on chart and in retention to match the percentage
displayed by lustre.
Fixes #2298.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2302)
=> GH-2298 - File used percentage slightly off

iml-gui/crate/src/components/dashboard/dashboard_fs_usage.rs
The text color for available space on the chart is currently black. This
leads to confusion whereas one might think that this value represents
the total space. This color should be closer to the gray value used in
the circle of the graph.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2297)
=> Update text color for available space on the chart

docker/docker-compose.yml, iml-api/src/graphql.rs
Implement Report query and deletion in graphql
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2304)
=> EX-1850 - Implement Report query and deletion

iml-agent/src/action_plugins/stratagem/server.rs
Latest version of lipe does not return Other bucket.
Update IML to not account for it on agent-side.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2306)
=> Remove "Other" bucket

iml-agent/src/cli.rs
filesync and cloudsync need at least one file specified
on iml-agent command line.  Enforce it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2308)
=> EX-1872 stratagem: require at least one file

iml-manager-cli/src/config-main.rs, iml-manager-cli/src/filesystem.rs, iml-manager-cli/src/lib.rs, iml-manager-cli/src/main.rs, iml-manager-cli/src/ostpool.rs, iml-manager-cli/src/profile.rs, iml-manager-cli/src/server.rs, iml-manager-cli/src/snapshot.rs, iml-manager-cli/src/update_repo_file.rs
- Determine executable name.
- Remove "IML" where possbile.
Separate packages would create a hard link for the executable and symlinks for shell completions.
Closes #2295.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2305)
=> Allow different names for IML CLI

iml-services/iml-device/src/lib.rs
The targets table is not populating the filesystem for multiple mgs's
spanning across multiple nodes. For example, take these two zfs filesystems:
```
chroma=> select * from target;
state  |      name      | active_host_id | host_ids | filesystems |         uuid         |      mount_path
---------+----------------+----------------+----------+-------------+----------------------+-----------------------
mounted | zfsmo-MDT0001  |              2 | {2,1}    | {zfsmo}     | 8695343810740655893  | /lustre/zfsmo/mdt1
mounted | zfsmo-MDT0000  |              1 | {1,2}    | {zfsmo}     | 4530718205682888275  | /lustre/zfsmo/mdt0
mounted | zfsmo-OST0000  |              3 | {3,4}    | {zfsmo}     | 9462550654203081538  | /lustre/zfsmo/ost0
mounted | zfsmo-OST0001  |              3 | {3,4}    | …
```
=> Fix target table

iml-agent/src/cli.rs
Report success and failures from iml-agent filesync and
cloudsync jobs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2310)
=> EX-1874 stratagem: iml-agent needs to be more verbose

Cargo.lock, iml-manager-cli/Cargo.toml, iml-manager-cli/src/api_utils.rs, iml-manager-cli/src/display_utils.rs, iml-manager-cli/src/stratagem.rs, iml-rabbit/Cargo.toml
The spinner lib unwraps term::stdout without checking if it's available.
In the case of running systemd within docker it is not available.
Switch to using the indicatif spinner, which seems to behave a bit
better in this scenario.
Fixes #2314.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2315)
=> Remove spinners lib from manager cli.

iml-agent/src/action_plugins/stratagem/action_filesync.rs, iml-agent/src/env.rs, iml-agent/systemd-units/settings.conf
Specify OPENMPI_PATH for the location of mpirun
Specify OPENMPI_COUNT for the number of threads to be used
defaults to /usr/mpi/gcc/openmpi-4.0.3rc4/bin
and 4
Since these are the default for 5.2 installs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2317)
=> EX-1911 filesync: create options to specify openmpi

iml-agent/src/action_plugins/stratagem/action_filesync.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2320)
=> Disable xattr copy in rsync

liblustreapi/src/lib.rs
When constructing an llapi instance from a random path
liblustreapi first resolves that path fully, including
symbolic links.  This causes a failure when trying to
get an llapi instance from a symbolic link that lives on
a lustre filesystem (ex /mnt/lustre/symbolic_link)
If the path passed into search_fsname is a link, use
the parent dir instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2325)
=> EX-1932 handle softlinks for llapi queries

iml-manager-cli/src/stratagem.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2327)
=> EX-1934 cloudsync: remove unused option from command line

docker/iml-cli-proxy.sh, docker/iml-manager-cli.dockerfile
iml-cli-proxy: calling direct prevents argument expansion
This also adds pathrough for RUST_LOG variable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2293)
=> Pass RUST_LOG to cli

Cargo.lock, iml-api/src/graphql.rs, iml-services/iml-device/src/lib.rs, iml-services/iml-device/src/main.rs, iml-services/iml-device/src/snapshots/iml_device__tests__deletions_only.snap, iml-services/iml-device/src/snapshots/iml_device__tests__upserts_and_deletions.snap, iml-services/iml-device/src/snapshots/iml_device__tests__upserts_only.snap, migrations/20201008184126_target_devpath_column.sql, sqlx-data.json
Add the devpath used to mount a target to the targets table.
This is useful for tasks where we need to know the underlying device for
a target.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2319)
=> Add devpath to targets

vagrant/Vagrantfile, vagrant/scripts/create_ldiskfs_lvm_mds_ha_setup.sh, vagrant/scripts/create_ldiskfs_lvm_oss_ha_setup.sh
Fencing is currently broken for vagrant installs.
This appears to be because the fence agent tries to use node.local as
the node to fence, but this does not coorespond to any vm name.
Instead it should use just node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2342)
=> Fix Vbox fencing

iml-api/src/graphql/mod.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2350)
=> Error on unknown FS

.copr/Makefile, Cargo.lock, Cargo.toml, docker/docker-compose.yml, docker/iml-network.dockerfile, iml-agent/src/daemon_plugins/daemon_plugin.rs, iml-agent/src/daemon_plugins/mod.rs, iml-agent/src/daemon_plugins/network.rs, iml-agent/src/network_interface_stats.rs, iml-agent/src/network_interfaces.rs, iml-manager.target, iml-network.service, iml-services/iml-network/Cargo.toml, iml-services/iml-network/src/main.rs, migrations/20201028182332_network_interface.sql, python-iml-manager.spec, rust-iml.spec, sqlx-data.json, vagrant/scripts/install_iml_docker_local.sh, vagrant/scripts/install_iml_docker_repouri.sh, vagrant/scripts/install_iml_local.sh
Now that the network logic / parsing lives on the rust side in the
iml-agent, the next step is to:
1. Create a daemon plugin to fetch the data
2. Ingest the data on the manager side:
a. Insert the interface data into the database
b. Insert the interface stats (rx/tx bytes) into influx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2353)
=> Integrate network interface data into IML

chroma_core/lib/graphql.py
Update the graphql python client to properly raise on error when the
query returns an error. In addition, provide a way to pass variables to
the client.
Finally, add a helper function to fetch all targets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2372)
=> Update graphql python client

python-iml-manager.spec
There is a beta version 2.0 in the "stable" repo which is incompartible by
CLI at least.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2377)
=> Require influx < 2

Cargo.lock, iml-agent/Cargo.toml, iml-agent/src/daemon_plugins/device.rs, iml-agent/src/device_scanner_client.rs, iml-agent/src/lib.rs, iml-services/iml-device/Cargo.toml
Extract a client that can be used to make requests to device-scanner on
the agent side.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2378)
=> Extract device-scanner client

iml-services/iml-stats/src/main.rs
There is currently a case in which a stale entries are being left in the
influx db. This takes place when a filesystem is mounted, data is pulled
into influx, and then another filesystem is mounted, and both
filesystems use the same mgs. For example:
time n:
mgs_fs: "fs"
time n+1:
mgs_fs: "fs2"
time n+2:
mgs_fs: "fs,fs2"
Currently, only items matching "fs,fs2" will be removed, since that's
the current input. This results in entries in the target table showing
that the filesystems are: "fs, fs2, fs,fs2".
This patch ensures that all subsets of the input filesystems are deleted
and all but the last of the current subset is deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Fix Stale Influx Entries

iml-agent/src/action_plugins/action_plugin.rs, iml-agent/src/action_plugins/high_availability/mod.rs
Move resource, wait for move completion, then remove move constraint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2391)
=> Add ha_resource_move action

iml-agent/src/action_plugins/ldev.rs, iml-api/src/graphql/mod.rs, iml-graphql-queries/src/target.rs, iml-manager-cli/src/display_utils.rs, iml-services/iml-device/src/lib.rs, iml-services/iml-device/src/main.rs, iml-services/iml-device/src/snapshots/iml_device__tests__deletions_only.snap, iml-services/iml-device/src/snapshots/iml_device__tests__upserts_and_deletions.snap, iml-services/iml-device/src/snapshots/iml_device__tests__upserts_only.snap, iml-system-docker-tests/Cargo.lock, iml-system-docker-tests/tests/zfs_test.rs, iml-system-rpm-tests/Cargo.lock, iml-system-rpm-tests/tests/zfs_test.rs, iml-system-test-utils/src/lib.rs, iml-system-test-utils/src/snapshots.rs, iml-wire-types/src/db.rs, iml-wire-types/src/lib.rs, migrations/20201021191942_fs_type_field.sql, sqlx-data.json
The fs_type data should be included in the targets table. This will be
used when creating the ldev conf and likely other things as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2343)
=> Add fs_type field to targets table

iml-agent/src/network_interfaces.rs
There are cases where the agent is deployed but lnetctl is not yet
installed.
In those cases we should just send empty data instead of failing the
plugin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2402)
=> Fix lnetctl not found

.rusty-hook.toml, README.md
Add some precommit checks using
[rusty-hook](https://github.com/swellaby/rusty-hook).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2409)
=> Add precommit with rusty-hook

.gitignore, Cargo.lock, Cargo.toml, iml-fs/src/lib.rs, iml-ssh/Cargo.toml, iml-ssh/src/lib.rs
Add new `iml-ssh` crate that allows for async execution
of ssh commands.
The following auth methods are supported:
- Private Key
- SSH agent
- Password
- Auto (for now just try id_rsa)
Internally, it uses [thrussh](https://pijul.org/thrussh/)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2410)
=> Add iml-ssh crate

Makefile, vagrant/Vagrantfile, vagrant/scripts/build_rust_rpms.sh
Building the rpms locally has been difficult becuase using the docker
container is significantly slower, even after increasing the available
ram and cpu's. In contrast, building in the adm vm appears to be nearly
as fast as building on the host. Furthermore, adding sccache appears to
maintain dependency builds across different branches, allowing for much
quicker builds. This patch adds a new provisioner to build the rust rpms
using the adm virtual machine and takes care of installing all necessary
dependencies, including sccache. To build the rust rpms, simply run the
following:
```
vagrant provision adm --provision-with build-rust-rpms
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Add rust rpm provisioner to adm node

docker/docker-compose.yml
This patch switches from the default `json-file` driver to the `journald` driver.
This means that all container logs will be written to the journal by
default, but will also still be available via `docker service logs ..`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2412)
=> Switch to using the journald driver for docker logging

vagrant/Vagrantfile
It looks to be leftover from before docker was moved into the adm vm.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2413)
=> Remove configure-docker-network-trigger

iml-system-docker-tests/tests/ldiskfs_test.rs, iml-system-docker-tests/tests/stratagem_test.rs, iml-system-docker-tests/tests/zfs_test.rs, iml-system-test-utils/src/lib.rs, iml-system-test-utils/src/ssh.rs, vagrant/Vagrantfile, vagrant/scripts/install_iml_docker_local.sh, vagrant/scripts/install_iml_docker_repouri.sh, vagrant/scripts/install_ntp.sh
The integration tests currently use the ntp server on the host when
running docker and the adm vm when running with RPMs.
Now that docker runs within the adm vm, we should always be able to use
adm to run the ntp server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2414)
=> Always use adm node as ntp server

Cargo.lock, iml-agent/src/daemon_plugins/device.rs, iml-agent/src/daemon_plugins/stats.rs, iml-services/iml-device/Cargo.toml, iml-services/iml-device/src/error.rs, iml-services/iml-device/src/lib.rs, iml-services/iml-device/src/main.rs, iml-services/iml-stats/src/main.rs
Instead of looking at influx for MGS info, send it inline with the
device service. This should help prevent races where devices and lctl
data is updated out-of-sync with each other.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2420)
=> Include MGS fs info with devices

iml-api/src/graphql/filesystem.rs, iml-api/src/graphql/mod.rs, iml-gui/crate/src/lib.rs, iml-gui/crate/src/page/filesystem.rs, iml-gui/crate/src/test_utils/fixture.json, iml-services/iml-corosync/src/lib.rs, iml-warp-drive/src/cache.rs, iml-warp-drive/src/db_record.rs, iml-wire-types/src/db.rs, iml-wire-types/src/warp_drive.rs, migrations/20201201204247_corosync_resource_ban.sql, migrations/20201204185824_corosync_listen_notify.sql, sqlx-data.json
The filesystem detail page does not currently take bans into account and
thus servers may be displayed even though they are not available for a
target. This patch will take resource bans into account and not display
a server if a resource is being banned on it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2408)
=> Handle Resource Bans on Filesystem Detail Page

chroma_core/services/http_agent/__init__.py
The http_agent service logs every access. This quickly becomes very
verbose. Silence the logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2424)
=> Silence python http agent logging

iml-agent/src/action_plugins/check_kernel.rs, iml-agent/src/action_plugins/check_stonith.rs, iml-agent/src/action_plugins/firewall_cmd.rs, iml-agent/src/action_plugins/high_availability/corosync_conf.rs, iml-agent/src/action_plugins/high_availability/mod.rs, iml-agent/src/action_plugins/kernel_module.rs, iml-agent/src/action_plugins/lustre/client.rs, iml-agent/src/action_plugins/stratagem/action_cloudsync.rs, iml-agent/src/action_plugins/stratagem/action_filesync.rs, iml-agent/src/action_plugins/stratagem/action_mirror.rs, iml-agent/src/action_plugins/stratagem/server.rs, iml-agent/src/daemon_plugins/device.rs, iml-agent/src/daemon_plugins/ntp.rs, iml-agent/src/daemon_plugins/stats.rs, iml-agent/src/high_availability.rs, iml-agent/src/lustre.rs, iml-agent/src/network_interfaces.rs, iml-agent/src/rpm.rs
If an action is cancelled, any associated child processes will keep
running.
Use
[kill_on_drop](https://docs.rs/tokio/0.3.5/tokio/process/struct.Command.html#method.kill_on_drop
) to make sure the child process is killed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2426)
=> Use kill_on_drop for all agent commands

iml-docker.service
The latest `docker-ce` adds an ordering constraint to `multi-user.target`.
`iml-docker` needs to add the same constraint, otherwise it a cycle is
created like the following:
```
Job iml-docker.service/start deleted to break ordering cycle starting with multi-user.target/start
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2433)
=> Ensure iml-docker starts after multi-user.target

device-scanner/iml-device-scanner.spec, iml-docker.spec, rust-iml.spec
Switch all remaining `systemctl preset` over to `%systemd_post` so we
don't trigger any preset files on upgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2431)
=> Switch all systemctl preset to systemd_post

docker/copy-embedded-settings, iml-docker.service
Update the IML docker setup to not print output while starting.
In addition, use a container that becomes stable earlier to copy
settings to the host.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2444)
=> Update docker setup

docker/copy-embedded-settings
`copy-embedded-settings` will find the trailer before looping. If the
container dies after entering the loop, then the loop will never exit as
the trailer is then non-existent.
Instead, we should find the trailer each turn of the loop to ensure we
are referencing a live container.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2448)
=> Fixup copy-embedded-settings

iml-agent/src/action_plugins/stratagem/action_filesync.rs
use dest_dir instead of src_dir when creating
paths to copy data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2449)
=> EX-2304 filesync: create the right path

iml-api/src/graphql/mod.rs, sqlx-data.json
Latest version of EXAScaler appears to have a number of new resource
constraints that weren't in the previous version.
This in turn has exposed a bug where we are not filtering by banned resource properly
and are picking up all target bans, not just the MGS one.
Instead, we should match the resource mount_point with the target
mount_path to only include the relevant resource.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2450)
=> Fix client mount generation

iml-api/src/graphql/stratagem.rs
Cloudsync lipe config had a few filesync references in it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2451)
=> EX-2312 cloudsync: Fix cloudsync lipe config
